### ISSUE TITLE
Unable to parse this statement that create a database

### ISSUE THREAD

**Issue by Hvision** [apache/shardingsphere#29289] opened 2023-12-05 08:16 UTC
CREATE TABLE "C##TPCC2"."TEST_BASIC2" 
   (	"BS_COL01" NUMBER, 
	"BS_COL02" NUMBER(38,6), 
	"BS_COL03" VARCHAR2(6), 
	"BS_COL04" VARCHAR2(6), 
	"BS_COL05" NUMBER, 
	"BS_COL06" NUMBER, 
	"BS_COL07" NUMBER, 
	"BS_COL08" NUMBER(10,4), 
	"BS_COL09" NUMBER(10,4), 
	"BS_COL10" BINARY_DOUBLE, 
	"BS_COL11" VARCHAR2(6), 
	"BS_COL12" CHAR(6), 
	"BS_COL13" CHAR(6), 
	 PRIMARY KEY ("BS_COL01")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TPCCTAB"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TPCCTAB"

**Comment by Hvision** [comment] 2023-12-05 08:16
this is oracle database.

**Comment by zihaoAK47** [comment] 2023-12-05 08:35
Hi, please provide more detailed information, such as version and error information, based on the problem template.

**Comment by Hvision** [comment] 2023-12-06 05:45
@zihaoAK47   version is master and err info：
 
![image](https://github.com/apache/shardingsphere/assets/24364787/bffd2e09-4ff3-47a8-9fd8-162060c51908)

**Comment by Hvision** [comment] 2023-12-06 05:47
my code 
![image](https://github.com/apache/shardingsphere/assets/24364787/0ad50092-e003-4727-abf4-64ff18145fc0)

**Comment by zihaoAK47** [comment] 2023-12-06 06:22
Thank you for your feedback. The above issue is caused by SQL not being parsed correctly. Would you be willing to improve this issue?

**Comment by Hvision** [comment] 2023-12-07 07:18
@zihaoAK47    sorry, I don't understand grammar of Antlr .

**Comment by ilyasahsan123** [comment] 2023-12-27 15:09
Hi @zihaoAK47,

I'm not sure if there's an issue with the provided query. I tested it with the following test case, and it passed. Could you please re-validate it?


**Case:**
```
    <create-table sql-case-id="create_table_with_issue_29289">
        <table name="TEST_BASIC2" start-delimiter="&quot;" end-delimiter="&quot;" start-index="13" stop-index="36">
            <owner name="C##TPCC2" start-delimiter="&quot;" end-delimiter="&quot;" start-index="13" stop-index="22" />
        </table>
        <column-definition type="NUMBER" start-index="43" stop-index="59">
            <column name="BS_COL01"/>
        </column-definition>
        <column-definition type="NUMBER" start-index="66" stop-index="82">
            <column name="BS_COL02"/>
        </column-definition>
        <constraint-definition start-index="89" stop-index="111">
            <primary-key-column name="BS_COL01" start-delimiter="&quot;" end-delimiter="&quot;" start-index="102" stop-index="111" />
        </constraint-definition>
    </create-table>
```

**SQL**
```
    <sql-case id="create_table_with_issue_29289" value="CREATE TABLE &quot;C##TPCC2&quot;.&quot;TEST_BASIC2&quot;
    (&quot;BS_COL01&quot; NUMBER,
    &quot;BS_COL02&quot; NUMBER,
    PRIMARY KEY (&quot;BS_COL01&quot;)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE &quot;TPCCTAB&quot; ENABLE
    ) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE &quot;TPCCTAB&quot;" db-types="Oracle" />
```

**Comment by zihaoAK47** [comment] 2023-12-28 01:31
@ilyasahsan123 Hi, thank you for your attention to this issue. Can you display a preview of antlr?

**Comment by ilyasahsan123** [comment] 2023-12-28 01:39
Sure, here is the ANTLR preview.

![image](https://github.com/apache/shardingsphere/assets/14249648/7f424d04-927d-4b1f-a661-5256459fa7c3)

**Comment by zihaoAK47** [comment] 2023-12-28 01:49
![2023-12-28_09-47](https://github.com/apache/shardingsphere/assets/106047330/34bec06e-53f7-4e5b-a697-91c454ed5306)

The second half of SQL seems to have not been parsed.

**Comment by ilyasahsan123** [comment] 2023-12-28 02:01
Got it, you are correct. Sorry for my mistake.

**Comment by zihaoAK47** [comment] 2023-12-28 02:06
Would you be willing to investigate this issue? I will assign it to you

**Comment by ilyasahsan123** [comment] 2023-12-28 02:10
Sure, please assign this to me.

**Comment by zihaoAK47** [comment] 2023-12-28 02:12
@ilyasahsan123 Thank you.

**Comment by ilyasahsan123** [comment] 2023-12-28 09:10
Hi @zihaoAK47 @strongduanmu, i have sent the PR, could you please take a look?

**Closed** 2023-12-28 10:37 UTC
Labels: type: enhancement, in: SQL parse, db: Oracle
