### ISSUE TITLE
Configuring read / write separation can create tables and write data normally, but an error is reported after restarting shardingspere

### ISSUE THREAD

**Issue by Asteven-zn** [apache/shardingsphere#11737] opened 2021-08-10 03:02 UTC
## Bug Report

**
Configuring read / write separation can create tables and write data normally, but an error is reported after restarting shardingspere. Only the data in the table can be deleted before restarting. Only when there is no table in the library can it be started successfully**.

## error
Starting the ShardingSphere-Proxy ...
The port is 3306
The classpath is /opt/shardingsphere-proxy/conf:.:/opt/shardingsphere-proxy/lib/*:/opt/shardingsphere-proxy/ext-lib/*
Please check the STDOUT file: /opt/shardingsphere-proxy/logs/stdout.log
tail: unrecognized file system type 0x794c7630 for ‘/opt/shardingsphere-proxy/logs/stdout.log’. please report this to bug-coreutils@gnu.org. reverting to polling
10:14:23,101 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:14:23,143 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.shardingsphere] to INFO
10:14:23,143 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.shardingsphere] to false
10:14:23,143 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger[org.apache.shardingsphere]
10:14:23,144 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - ROOT level set to INFO
10:14:23,144 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [console] to Logger[ROOT]
10:14:23,144 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:14:23,145 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@19dc67c2 - Registering current configuration as safe fallback point

[INFO ] 2021-08-09 10:14:23.269 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[INFO ] 2021-08-09 10:14:23.725 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[INFO ] 2021-08-09 10:14:23.727 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[INFO ] 2021-08-09 10:14:23.743 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[INFO ] 2021-08-09 10:14:23.744 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
[INFO ] 2021-08-09 10:14:23.749 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
[INFO ] 2021-08-09 10:14:23.751 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
[INFO ] 2021-08-09 10:14:23.766 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
[INFO ] 2021-08-09 10:14:23.767 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
[INFO ] 2021-08-09 10:14:23.779 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
[INFO ] 2021-08-09 10:14:23.780 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown initiated...
[INFO ] 2021-08-09 10:14:23.782 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown completed.
[INFO ] 2021-08-09 10:14:23.783 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Starting...
[INFO ] 2021-08-09 10:14:23.797 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Start completed.
[INFO ] 2021-08-09 10:14:23.798 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Starting...
[INFO ] 2021-08-09 10:14:23.806 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Start completed.
[INFO ] 2021-08-09 10:14:23.807 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Shutdown initiated...
[INFO ] 2021-08-09 10:14:23.808 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Shutdown completed.
[INFO ] 2021-08-09 10:14:23.809 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Starting...
[INFO ] 2021-08-09 10:14:23.823 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Start completed.
[INFO ] 2021-08-09 10:14:23.824 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Starting...
[INFO ] 2021-08-09 10:14:23.834 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Start completed.
[INFO ] 2021-08-09 10:14:23.834 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Shutdown initiated...
[INFO ] 2021-08-09 10:14:23.836 [main] com.zaxxer.hikari.HikariDataSource - HikariPool-4 - Shutdown completed.
Exception in thread "main" org.apache.shardingsphere.infra.exception.ShardingSphereException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.appendDialectRemainTables(SchemaBuilder.java:125)
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.appendRemainTables(SchemaBuilder.java:97)
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.build(SchemaBuilder.java:78)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.buildSchema(MetaDataContextsBuilder.java:136)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.buildMetaData(MetaDataContextsBuilder.java:101)
	at org.apache.shardingsphere.infra.context.metadata.MetaDataContextsBuilder.build(MetaDataContextsBuilder.java:90)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.createMetaDataContexts(AbstractBootstrapInitializer.java:84)
	at org.apache.shardingsphere.proxy.initializer.impl.AbstractBootstrapInitializer.init(AbstractBootstrapInitializer.java:67)
	at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:48)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.appendDialectRemainTables(SchemaBuilder.java:120)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaData(MySQLTableMetaDataLoader.java:95)
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaDataMap(MySQLTableMetaDataLoader.java:77)
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadTableMetaDataMap(MySQLTableMetaDataLoader.java:59)
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.load(MySQLTableMetaDataLoader.java:54)
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.lambda$appendDialectRemainTables$1(SchemaBuilder.java:116)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by menghaoranss** [comment] 2021-08-10 08:06
Which version did you use? Could it be reproduced every time?

**Comment by Asteven-zn** [comment] 2021-08-11 09:47
we use docker verison sharding-proxy:5.0.0，Configure read-write separation. Sharding will fail every time you restart. You can only delete tables in the database

**Comment by Asteven-zn** [comment] 2021-08-12 08:12
### There are two databases that need to be read-write separated
config-data-simulator-dev.yaml
`schemaName: data_simulator_test
    
    dataSources:
      write_ds:
        #url: jdbc:mysql://mysql-mgr-1.mysql-mgrservice:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://mgr-mysql-primary:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000
      read_ds_0:
        #url: jdbc:mysql://mysql-mgr-2.mysql-mgrservice:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://mgr-mysql-replica:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000`

config-readwrite-splitting2.yaml
`    schemaName: open_platform_test
    
    dataSources:
      write_ds:
        #url: jdbc:mysql://mysql-mgr-1.mysql-mgrservice:3306/open_platform_test?serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://mgr-mysql-primary:3306/open_platform_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000
      read_ds_0:
        #url: jdbc:mysql://mysql-mgr-2.mysql-mgrservice:3306/open_platform_test?serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://mgr-mysql-replica:3306/open_platform_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000`

**Comment by RaigorJiang** [comment] 2021-08-12 08:34
Hi  @Asteven-zn 
Thanks for your report, but I don't see your rule configuration, may be you can refer to [example1](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-readwrite-splitting.yaml) and [example2](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-proxy-example/shardingsphere-proxy-boot-mybatis-example/src/main/resources/conf/config-readwrite-splitting.yaml).

**Comment by Asteven-zn** [comment] 2021-08-12 09:34
server.yaml
`    rules:
      - !AUTHORITY
        users:
          - root@%:tcsaMysql8016
          - sharding@:sharding
        provider:
          type: NATIVE
`

config-data-simulator-dev.yaml
`schemaName: data_simulator_test
    dataSources:
      write_ds:
        url: jdbc:mysql://mgr-mysql-primary:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000
      read_ds_0:
        url: jdbc:mysql://mgr-mysql-replica:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000
    rules:
    - !READWRITE_SPLITTING
      dataSources:
        pr_ds:
          writeDataSourceName: write_ds
          readDataSourceNames:
            - read_ds_0`

**Comment by Asteven-zn** [comment] 2021-08-12 09:37
# server.yaml
`    rules:
      - !AUTHORITY
        users:
          - root@%:tcsaMysql8016
          - sharding@:sharding
        provider:
          type: NATIVE`
# config-data-simulator-dev.yaml
`    schemaName: data_simulator_test
    dataSources:
      write_ds:
        #url: jdbc:mysql://mysql-mgr-1.mysql-mgrservice:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://mgr-mysql-primary:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000
      read_ds_0:
        #url: jdbc:mysql://mysql-mgr-2.mysql-mgrservice:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://mgr-mysql-replica:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000
    rules:
    - !READWRITE_SPLITTING
      dataSources:
        pr_ds:
          writeDataSourceName: write_ds
          readDataSourceNames:
            - read_ds_0`

**Comment by RaigorJiang** [comment] 2021-08-12 09:39
Hi @Asteven-zn 
I saw your project. The homepage mentioned `config-readwrite-splitting.yaml` in the configmap directory, but there is no such file in that directory?

**Comment by Asteven-zn** [comment] 2021-08-12 09:50
#### config-server.yaml
`

    rules:
      - !AUTHORITY
        users:
          - root@%:tcsaMysql8016
          - sharding@:sharding
        provider:
          type: NATIVE
`

#### config-data-simulator-dev.yaml
`

    schemaName: data_simulator_test
    dataSources:
      write_ds:
        #url: jdbc:mysql://mysql-mgr-1.mysql-mgrservice:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://mgr-mysql-primary:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000
      read_ds_0:
        #url: jdbc:mysql://mysql-mgr-2.mysql-mgrservice:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://mgr-mysql-replica:3306/data_simulator_test?serverTimezone=UTC&useSSL=false
        username: root
        password: tcsaMysql8016
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 3500
        minPoolSize: 3500
        maintenanceIntervalMilliseconds: 30000
    rules:
    - !READWRITE_SPLITTING
      dataSources:
        pr_ds:
          writeDataSourceName: write_ds
          readDataSourceNames:
            - read_ds_0
`

**Comment by RaigorJiang** [comment] 2021-08-12 10:48
@Asteven-zn    Ok, i will try to reproduce your problem.

**Comment by RaigorJiang** [comment] 2021-08-16 02:30
@Asteven-zn 
Sorry to keep you waiting,
I tested but did not reproduce the problem. The problem you described may have been solved in this PR #11597. Can you try to build a Docker image from the master branch and do your test?

**Comment by Asteven-zn** [comment] 2021-08-18 09:24
Don't you have the latest build image?

**Comment by RaigorJiang** [comment] 2021-08-18 10:45
> Don't you have the latest build image?

Yes, I built the docker image from the master branch and tested the scenario you described.
But because the image on the docker hub is not up to date, you have to build one yourself and use it for testing.

**Comment by RaigorJiang** [comment] 2021-08-18 10:50
Please refer to https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/docker/

**Comment by RaigorJiang** [comment] 2021-09-22 08:42
Hi @Asteven-zn 
If your problem is solved, can we close this issue?

**Comment by Asteven-zn** [comment] 2021-09-26 06:15
Not resolved，failed to build ，Can you build the latest version of the bin file?

**Comment by RaigorJiang** [comment] 2021-09-26 06:21
Yes, I can build successfully.

> Please refer to https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/docker/

**Comment by Asteven-zn** [comment] 2021-09-26 07:33
ok，close

**Closed** 2021-09-26 07:35 UTC
Labels: type: question, feature: readwrite-splitting
