### ISSUE TITLE
Read/write separation does not obtain the data source

### ISSUE THREAD

**Issue by future94** [apache/shardingsphere#11039] opened 2021-06-28 02:35 UTC
I look this [github demo address](https://github.com/apache/shardingsphere/blob/5.0.0-beta/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources/application-sharding-readwrite-splitting.properties)，but I found some problems。

sql
```
CREATE TABLE ds_0.t_read_write (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
 
CREATE TABLE ds_1.t_read_write (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

pom
```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.4.5</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>druid</artifactId>
    <version>1.2.6</version>
</dependency>
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.0.0-beta</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
```

entity
```
package org.example.shardingsphere.entity;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Data
@Table(name = "t_read_write")
public class ReadWrite {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
}
```
repository
```
package org.example.shardingsphere.repository;

import org.example.shardingsphere.entity.ReadWrite;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * @author weilai
 * @date 2021/6/25 6:30 下午
 */
public interface ReadWriteRepository extends JpaRepository<ReadWrite, Long> {
}
```
test
```
@SpringBootTest
class OrderRepositoryTest {

    @Autowired
    private ReadWriteRepository readWriteRepository;

    @Test
    public void readWrite() {
        ReadWrite readWrite = new ReadWrite();
        readWrite.setName("name");
        readWriteRepository.save(readWrite);
    }
}
```

## question1
use broadcast-tables :  java.lang.IllegalArgumentException: Read data source names are required.

config
```
#数据源
spring.shardingsphere.datasource.names=test1,test2
spring.shardingsphere.datasource.common.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.cj.jdbc.Driver

spring.shardingsphere.datasource.test1.url=jdbc:mysql://xxx:3306/ds_0?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.test1.username=dev
spring.shardingsphere.datasource.test1.password=
spring.shardingsphere.datasource.test1.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.test1.driver-class-name=com.mysql.cj.jdbc.Driver

spring.shardingsphere.datasource.test2.url=jdbc:mysql://xxx:3306/ds_1?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.test2.username=dev
spring.shardingsphere.datasource.test2.password=
spring.shardingsphere.datasource.test2.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.test2.driver-class-name=com.mysql.cj.jdbc.Driver

spring.shardingsphere.props.sql-show=true
# 读写分离
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds.write-data-source-name=test1
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds.read-data-source-name=test2
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds.load-balancer-name=load-balancer-name
# 负载均衡算法配置
spring.shardingsphere.rules.readwrite-splitting.load-balancers.load-balancer-name.type=ROUND_ROBIN
spring.shardingsphere.rules.sharding.broadcast-tables[0]=t_read_write
spring.shardingsphere.rules.sharding.tables.t_read_write.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.t_read_write.key-generate-strategy.key-generator-name=snowflake
```
## question2
use actual-data-nodes :  org.apache.shardingsphere.infra.exception.ShardingSphereException: Cannot find data source in sharding rule, invalid actual data node is: 'ds.t_read_write'

config
```
spring.shardingsphere.datasource.names=test1,test2
spring.shardingsphere.datasource.common.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.common.driver-class-name=com.mysql.cj.jdbc.Driver

spring.shardingsphere.datasource.test1.url=jdbc:mysql://xxx:3306/ds_0?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.test1.username=dev
spring.shardingsphere.datasource.test1.password=
spring.shardingsphere.datasource.test1.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.test1.driver-class-name=com.mysql.cj.jdbc.Driver

spring.shardingsphere.datasource.test2.url=jdbc:mysql://xxx:3306/ds_1?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
spring.shardingsphere.datasource.test2.username=dev
spring.shardingsphere.datasource.test2.password=
spring.shardingsphere.datasource.test2.type=com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.test2.driver-class-name=com.mysql.cj.jdbc.Driver

spring.shardingsphere.props.sql-show=true
# 读写分离
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds.write-data-source-name=test1
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds.read-data-source-name=test2
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds.load-balancer-name=load-balancer-name
# 负载均衡算法配置
spring.shardingsphere.rules.readwrite-splitting.load-balancers.load-balancer-name.type=ROUND_ROBIN

spring.shardingsphere.rules.sharding.tables.t_read_write.actual-data-nodes=ds.t_read_write
spring.shardingsphere.rules.sharding.tables.t_read_write.key-generate-strategy.column=id
spring.shardingsphere.rules.sharding.tables.t_read_write.key-generate-strategy.key-generator-name=snowflake
```

**Comment by RaigorJiang** [comment] 2021-06-28 06:13
Hi @future94 
Welcome to shardingsphere.

According to your information, you only need to use the readwrite-splitting scenario.
- question1
`broadcast` is the configuration used with the sharding scene, you don't need it here.
- question2
ds configuration is incorrect, and it is for `sharding` scene too.

please refer to another example:
https://github.com/apache/shardingsphere/blob/5.0.0-beta/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources/application-readwrite-splitting.properties

**Comment by future94** [comment] 2021-06-28 08:04
> Hi @future94
> Welcome to shardingsphere.
> 
> According to your information, you only need to use the readwrite-splitting scenario.
> 
> * question1
>   `broadcast` is the configuration used with the sharding scene, you don't need it here.
> * question2
>   ds configuration is incorrect, and it is for `sharding` scene too.
> 
> please refer to another example:
> https://github.com/apache/shardingsphere/blob/5.0.0-beta/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources/application-readwrite-splitting.properties

Hi @RaigorJiang 
Thank you for your reply.

I want to sharding and read/write the table, So I went to watch t_read_write configuration `spring.shardingsphere.rules.sharding.tables.t_read_write.actual-data-nodes=ds.t_read_write`, But it does not recognize the database resource DS. I'm watching this demo [https://github.com/apache/shardingsphere/blob/5.0.0-beta/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources/application-sharding-readwrite-splitting.properties](https://github.com/apache/shardingsphere/blob/5.0.0-beta/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-jpa-example/src/main/resources/application-sharding-readwrite-splitting.properties)

ds configuration， What's the problem with configuration？Looking forward to your reply.

**Comment by RaigorJiang** [comment] 2021-06-28 08:17
@future94 
Actual data nodes correspond to the `datasource.names`, your datasource names are `test1,test2`, then actual data nodes should be `test$->{1..2}. t_read_write`

It is recommended that you read the official document first, and then try to modify the configuration.
https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/

**Comment by RaigorJiang** [comment] 2021-06-30 01:53
Hi @future94 
Is your problem solved?

**Comment by pkwenda** [comment] 2021-07-01 04:38
I have the same problem , If the real database name different alias database name, you can use `type: com.zaxxer.hikari.HikariDataSource` to do your dataSource, I not know why maybe is a BUG.

reason :
![image](https://user-images.githubusercontent.com/14212375/124065337-2b6e4400-da69-11eb-9f18-6b34b4d28749.png)
after i change dataSource , it work now

**Comment by RaigorJiang** [comment] 2021-07-01 05:06
Hi @pkwenda 
Do you mean datasource name `msg-center` can not work, but `msg_center` works well?

**Comment by pkwenda** [comment] 2021-07-01 05:25
If the real database name of the configuration file has an underscore, it is processed by an alias, for example, like this

```yaml
shardingsphere:
        datasource:
            msg-center:
                driver-class-name: com.mysql.jdbc.Driver
                jdbc-url: jdbc:mysql://**.**.**.**:3306/msg_center
                password: Kyig&pnlGnaHaJ
                type: com.zaxxer.hikari.HikariDataSource
                username: test_rw
            names: msg-center
```

because names not allowed underscore ，error , i change datasource it works

com.alibaba.druid.pool.DruidDataSource  --- > com.zaxxer.hikari.HikariDataSource

**Comment by RaigorJiang** [comment] 2021-07-01 05:57
@pkwenda  Thanks for your information, I 'll check it.

**Comment by RaigorJiang** [comment] 2021-07-09 08:38
Hi @pkwenda  
This is not a connection pool problem, it is that underscore configuration parameters are no longer allowed to be used above springboot2.0.
> Invalid characters: '_'
    Bean: org.apache.shardingsphere.spring.boot.ShardingSphereAutoConfiguration
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

So it's not a bug.

@future94
Is your problem solved?  Can we close this issue?

**Closed** 2021-09-22 10:54 UTC
