### ISSUE TITLE
show tables like xxx% can not return correct result

### ISSUE THREAD

**Issue by yujun110** [apache/shardingsphere#8982] opened 2021-01-11 11:54 UTC
show tables like xxx% can not return correct result

LogicTablesMergedResult:

```
@Override
    protected final List<MemoryQueryResultRow> init(final ShardingRule shardingRule, final SchemaMetaData schemaMetaData, 
                                                    final SQLStatementContext sqlStatementContext, final List<QueryResult> queryResults) throws SQLException {
        List<MemoryQueryResultRow> result = new LinkedList<>();
        Set<String> tableNames = new HashSet<>();
        for (QueryResult each : queryResults) {
            while (each.next()) {
                MemoryQueryResultRow memoryResultSetRow = new MemoryQueryResultRow(each);
                String actualTableName = memoryResultSetRow.getCell(1).toString();
                Optional<TableRule> tableRule = shardingRule.findTableRuleByActualTable(actualTableName);
                if (!tableRule.isPresent()) {
                    if (shardingRule.getTableRules().isEmpty() || schemaMetaData.containsTable(actualTableName) && tableNames.add(actualTableName)) {
                        result.add(memoryResultSetRow);
                    }
                } else if (tableNames.add(tableRule.get().getLogicTable())) {
                    memoryResultSetRow.setCell(1, tableRule.get().getLogicTable());
                    setCellValue(memoryResultSetRow, tableRule.get().getLogicTable(), actualTableName);
                    result.add(memoryResultSetRow);
                }
            }
        }
        return result;
    }
```

**Comment by yujun505646964** [comment] 2021-01-11 11:59
<dependency>
			<groupId>org.apache.shardingsphere</groupId>
			<artifactId>sharding-jdbc-spring-boot-starter</artifactId>
			<version>4.1.1</version>
		</dependency>

**Comment by strongduanmu** [comment] 2021-01-12 00:49
@yujun505646964 Can you try to upgrade to version 5.0.0-alpha? This version has better support for show tables statement.

**Comment by yujun505646964** [comment] 2021-01-12 01:20
where to download? the latest in mvnrepository is 4.1.1？

**Comment by yujun505646964** [comment] 2021-01-12 02:02
@strongduanmu ok, thanks

**Comment by tristaZero** [comment] 2021-01-12 03:19
Hi @yujun505646964 

I guess you have targeted the cause. Indeed, `show tables like xxx% ` is unsupported currently. From my perspective, it is not a simple one. 

Although Databases help us get the tables like xxx%, ShardingSphere still needs to apply it to merging the final result in `LogicTablesMergedResult`.

Therefore, we need to add members in `ShowTableStatement` labeling prefix %, suffix % or both. After that, we can consider filtering the resultSet by `regular expression` with % labels of `ShowTableStatement` in `LogicTablesMergedResult`.

Does anyone **have an interest in this enhancement feature**? Welcome your trying.

**Comment by MingxingLAI** [comment] 2021-04-29 06:51
Hi @tristaZero, May I try this issue?

**Comment by strongduanmu** [comment] 2021-04-29 09:25
> Hi @tristaZero, May I try this issue?

@MingxingLAI Welcome. 👍

**Comment by MingxingLAI** [comment] 2021-05-07 02:55
> Hi @yujun505646964
> 
> I guess you have targeted the cause. Indeed, `show tables like xxx% ` is unsupported currently. From my perspective, it is not a simple one.
> 
> Although Databases help us get the tables like xxx%, ShardingSphere still needs to apply it to merging the final result in `LogicTablesMergedResult`.
> 
> Therefore, we need to add members in `ShowTableStatement` labeling prefix %, suffix % or both. After that, we can consider filtering the resultSet by `regular expression` with % labels of `ShowTableStatement` in `LogicTablesMergedResult`.
> 
> #### Does anyone have an interest in this enhancement feature?
> Welcome your trying.

I am ready to start solving this problem, are there any more tips and suggestions？ @strongduanmu @tristaZero

**Comment by tristaZero** [comment] 2021-05-09 13:33
Hi @MingxingLAI ,
Thanks for your attention here, sorry for my late coming.
Let consider this issue with the following scenario,

Suppose here are some tables,
```
t_order (a sharding logic table, including t_order_0, t_order_1)
t_order_item (a sharding logic table, including t_order_item_0, t_order_item_1)
t_order_number(a single table)
t_order_metadata(a broadcast table, each instance has this table)
t_item_order(a single table)
```
Now, how to filter and return all the `logic tables` to users by `show tables like '%t_order%"?

Firstly,  we need to put maybe two (?) `flags`(`%`) in 'showStatement` to mark it for usage later on.
Secondly, `show tables like '%t_order%" will be sent to all the DB instances to get all the `actual` tables.
Thirdly, we need to deal with these results in  `LogicTablesMergedResult`, including,
- Merge some of the actual tables into `sharding tables` by sharding rules
- Filter all the target `logic tables` (sharding tables, single tables, broadcast tables) with the two of  `%` marks in  `showStatement` and sharding rules
Last but not least, do not forget unit tests to verify your modification.

**Comment by tristaZero** [comment] 2021-05-09 13:42
Hi @MingxingLAI ,
Thanks for your attention here, sorry for my late coming.
Let consider this issue with the following scenario,

Suppose here are some tables,
```
t_order (a sharding logic table, including t_order_0, t_order_1)
t_order_item (a sharding logic table, including t_order_item_0, t_order_item_1)
t_order_number(a single table)
t_order_metadata(a broadcast table, each instance has this table)
t_item_order(a single table)
```
Now, how to filter and return all the `logic tables` to users by `show tables like '%t_order%"?

Firstly,  we need to put maybe two (?) `flags`(`%`) in 'showStatement` to mark it for usage later on.
Secondly, `show tables like '%t_order%" will be sent to all the DB instances to get all the `actual` tables.
Thirdly, we need to deal with these results in  `LogicTablesMergedResult`, including,
- Merge some of the actual tables into `sharding tables` by sharding rules
- Filter all the target `logic tables` (sharding tables, single tables, broadcast tables) with the two of  `%` marks in  `showStatement` and sharding rules
Last but not least, do not forget unit tests to verify your modification.

**Comment by MingxingLAI** [comment] 2021-05-10 03:17
> @strongduanmu ok, thanks,but,I compare the code above,it is the same with 4.1.1, show tables still only returns the logical table name,my project [https://github.com/yujun505646964/sharding-jdbc-2.git](url)

Hi，Could you give me more info? What is your config and input，and What's output is your expect ？@yujun110

**Comment by MingxingLAI** [comment] 2021-05-10 12:02
I tested the code and it seems to be able to return the correct result. Can you give a test case?  @tristaZero @strongduanmu

**Comment by tristaZero** [comment] 2021-05-13 10:17
@MingxingLAI Thanks for your effort. If so, looks like we can close this one, right?
@yujun110 While, I have week confidence you will give some feedbacks here, @MingxingLAI did much work to test on our master branch and this SQL worked well. That means the incoming release will support it. 
If this msg could reach you, could you give a double-check?

**Comment by MingxingLAI** [comment] 2021-05-19 09:42
Yes, you can close the one if no more info.

**Closed** 2021-05-20 04:30 UTC
Labels: feature: sharding, status: volunteer wanted, type: enhancement
