### ISSUE TITLE
Use @Aspect  can cause start so slow

### ISSUE THREAD

**Issue by huazx** [apache/shardingsphere#20666] opened 2022-08-31 03:03 UTC
using ShardingSphere JDBC 5.1.2
when i use @Aspect, the spring boot program start so slow

`
@Aspect
@Component
public class AspectjLog {
    @Pointcut("execution(* org.apache.shardingsphere.example.core.mybatis.service.*.*(..))")
    public void chtrollerPict(){
    }
    @Around("chtrollerPict()")
    public Object around(ProceedingJoinPoint point) throws Throwable {
        return point.proceed();
    }
}
`

**Comment by linghengqian** [comment] 2022-09-01 07:34
- Could you submit a PR stating the direction of improvement?  👀

**Comment by huazx** [comment] 2022-09-01 08:31
> 

Adding @ aspect code will prolong startup for more than 30s.
You can try it in shardingsphere-example

**Comment by linghengqian** [comment] 2022-09-01 08:58
- Are you referring to the master branch or the 5.1.2 tag?  Because https://github.com/apache/shardingsphere/issues/18653 made adjustments to jooq, the actual performance of the master branch and the tag of 5.1.2 deviates.

**Comment by linghengqian** [comment] 2022-10-10 07:24
- Unable to reproduce this issue in master branch, this issue can be closed.

**Comment by TeslaCN** [comment] 2022-12-26 05:14
If this is caused by JooQ, then it was fixed in later version. Please try the latest version.

**Closed by TeslaCN** 2022-12-26 05:14 UTC
