### ISSUE TITLE
Exception occurred when querying information_schema.schemata

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#25899] opened 2023-05-25 14:46 UTC
## Bug Report
```sql
mysql> select * from information_schema.schemata;
ERROR 30000 (HY000): Unknown exception: Index: 5, Size: 5
```

### Which version of ShardingSphere did you use?
Master.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy.

### Expected behavior
Query successful.

### Reason analyze (If you can)
<img width="486" alt="image" src="https://github.com/apache/shardingsphere/assets/19788130/af886f2b-638e-46e5-926a-2453ccbcf724">
Some rows have only 5 columns, normal is 6 columns.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Execute `select * from information_schema.schemata;` in proxy.

**Comment by boyjoy1127** [comment] 2023-06-11 02:16
Will this issue be completed before June 15 which is the final date of version 5.4.0?

**Comment by zhangfengcdt** [comment] 2023-08-02 00:25
I think the root cause of this issue is that the `SCHEMATA .DEFAULT_ENCRYPTION` was newly added to MySQL 8.0.16 (2019-04-25, General Availability). 

The current code (master) add default columns based on this new schema, however, when users use the older version of MySQL, the merged rows does not contain such column. Also, the `schemata.yaml` file failed to include the new column as well (see this [PR](https://github.com/apache/shardingsphere/pull/27620) to add it).

 @FlyingZC What MySQL version did you use for this bug report?

**Comment by FlyingZC** [comment] 2023-08-02 04:47
@zhangfengcdt Hi,I have a problem testing on mysql 5.7,you can test whether this sql can be executed correctly on mysql5.7 and mysql8 by shardingsphere-proxy.

**Closed** 2023-08-02 08:02 UTC
Labels: type: bug, in: metadata
