### ISSUE TITLE
Range from 0 to more than Integer.MAX_VALUE occur exception

### ISSUE THREAD

**Issue by xiaoxiong581** [apache/shardingsphere#5544] opened 2020-05-12 03:50 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-proxy
### Expected behavior
query success
### Actual behavior
throw exception
![image](https://user-images.githubusercontent.com/19368482/81636431-6cab2b00-9446-11ea-8df6-23b6493dc38f.png)
![image](https://user-images.githubusercontent.com/19368482/81636474-8ba9bd00-9446-11ea-8d20-6be5ed47634c.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
query data range from 0 to 3147483647 （more than Integer.MAX_VALUE）
#### config-xxx.yaml
```yaml
schemaName: databasemanager

dataSources:
  ds_0:
    url: jdbc:mysql://192.168.137.102:3306/databasemanager?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://192.168.137.102:3307/databasemanager?serverTimezone=UTC&useSSL=false
    username: root
    password: xxxxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50

shardingRule:
  tables:
    t_cluster:
      actualDataNodes: ds_${0..1}.t_cluster
      tableStrategy:
        none:
      databaseStrategy:
        complex:
          shardingColumns: clusterId
          algorithmClassName: org.apache.shardingsphere.shardingproxy.algorithm.complex.AutoPartitionByLong
    t_cluster_instance:
      actualDataNodes: ds_${0..1}.t_cluster_instance
      tableStrategy:
        none:
      databaseStrategy:
        inline:
          shardingColumn: clusterId
          algorithmExpression: ds_${clusterId.hashCode().abs() % 2}
  bindingTables:
    - t_cluster,t_cluster_instance
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:


```

#### table
```sql
create table `t_cluster` (
	`clusterId` bigint (20),
	`clusterName` varchar (384),
	`projectId` varchar (192),
	`createTime` datetime ,
	`updateTime` datetime 
); 
```

#### execute sql
```sql
select * from t_cluster t where  t.clusterId > 3 and t.clusterId < 3147483647
```

**Comment by kimmking** [comment] 2020-05-12 04:48
It can't load the images. Can you show a text there?

**Comment by xiaoxiong581** [comment] 2020-05-12 05:32
```shell
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at java.lang.Integer.compareTo(Integer.java:52)
	at com.google.common.collect.Range.compareOrThrow(Range.java:683)
	at com.google.common.collect.Cut.compareTo(Cut.java:75)
	at com.google.common.collect.Range.<init>(Range.java:361)
	at com.google.common.collect.Range.create(Range.java:153)
	at com.google.common.collect.Range.intersection(Range.java:569)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.WhereClauseShardingConditionEngine.mergeRangeRouteValues(WhereClauseShardingConditionEngine.java:171)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.WhereClauseShardingConditionEngine.mergeRouteValues(WhereClauseShardingConditionEngine.java:146)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.WhereClauseShardingConditionEngine.createShardingCondition(WhereClauseShardingConditionEngine.java:122)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.WhereClauseShardingConditionEngine.createShardingConditions(WhereClauseShardingConditionEngine.java:93)
	at org.apache.shardingsphere.sharding.route.engine.condition.engine.WhereClauseShardingConditionEngine.createShardingConditions(WhereClauseShardingConditionEngine.java:73)
	at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.getShardingConditions(ShardingRouteDecorator.java:82)
	at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:62)
	at org.apache.shardingsphere.sharding.route.engine.ShardingRouteDecorator.decorate(ShardingRouteDecorator.java:53)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.executeRoute(DataNodeRouter.java:91)
	at org.apache.shardingsphere.underlying.route.DataNodeRouter.route(DataNodeRouter.java:76)
	at org.apache.shardingsphere.underlying.pluggble.prepare.SimpleQueryPrepareEngine.route(SimpleQueryPrepareEngine.java:54)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.executeRoute(BasePrepareEngine.java:96)
	at org.apache.shardingsphere.underlying.pluggble.prepare.BasePrepareEngine.prepare(BasePrepareEngine.java:83)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.doShardingRoute(StatementExecutorWrapper.java:80)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.wrapper.StatementExecutorWrapper.route(StatementExecutorWrapper.java:63)
	at org.apache.shardingsphere.shardingproxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:74)
	at org.apache.shardingsphere.shardingproxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:52)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:73)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:93)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by strongduanmu** [comment] 2020-05-18 15:04
@xiaoxiong581 Hi, can you provide the source code of AutoPartitionByLong?

**Comment by xiaoxiong581** [comment] 2020-05-18 23:45
> @xiaoxiong581 Hi, can you provide the source code of AutoPartitionByLong?

```java
package org.apache.shardingsphere.shardingproxy.algorithm.complex;

import org.apache.shardingsphere.api.sharding.complex.ComplexKeysShardingAlgorithm;
import org.apache.shardingsphere.api.sharding.complex.ComplexKeysShardingValue;

import java.util.Collection;

public class AutoPartitionByLong implements ComplexKeysShardingAlgorithm<Long> {
    @Override
    public Collection<String> doSharding(Collection<String> availableTargetNames, ComplexKeysShardingValue<Long> shardingValue) {
        System.out.println(availableTargetNames);
        System.out.println(shardingValue);
        return availableTargetNames;
    }
}
```

**Comment by strongduanmu** [comment] 2020-05-20 13:17
Hi, I reproduced the problem. I found that when ANTLR parses numeric values, it will parse text into different numeric types based on its value. The parsing code is as follows:

```java
private Number getNumber(final String value) {
    try {
        return getBigInteger(value);
    } catch (final NumberFormatException ex) {
        // TODO make sure with double and float
        return new BigDecimal(value);
    }
}

private static Number getBigInteger(final String value) {
    BigInteger result = new BigInteger(value);
    if (result.compareTo(new BigInteger(String.valueOf(Integer.MIN_VALUE))) >= 0 && result.compareTo(new BigInteger(String.valueOf(Integer.MAX_VALUE))) <= 0) {
        return result.intValue();
    }
    if (result.compareTo(new BigInteger(String.valueOf(Long.MIN_VALUE))) >= 0 && result.compareTo(new BigInteger(String.valueOf(Long.MAX_VALUE))) <= 0) {
        return result.longValue();
    }
    return result;
}
```

When the user executes the range query sql, multiple ranges will be merged by the mergeRouteValues method. Because the different types, the intersection method will report a ClassCastException exception. the code is as follows:

```java
private Range<Comparable<?>> mergeRangeRouteValues(final Range<Comparable<?>> value1, final Range<Comparable<?>> value2) {
    return null == value2 ? value1 : value1.intersection(value2);
}
```

For better compatibility, can I use BigInteger to parse all numeric values? I need some help to fix this issue. @kimmking @tristaZero 😀

**Comment by tristaZero** [comment] 2020-05-21 11:32
@strongduanmu Hi Thanks for your attention. 

From my understanding, there are two of ways to fix this issue.
1. Like you said, `getBigInteger()` always return `BigInteger` instead of `longValue()` and `intValue()`. But you need to check whether this way impacts other functions or modules.
2. Give a check and typecast (If needed) of `value1` and `value2` in `mergeRangeRouteValues()`
, which will only take effect on `WhereClauseShardingConditionEngine`. 

Since it locates in the core module, we should pay more attention to it. For me, I prefer the first one, and welcome your comment and PR! 😉

**Comment by strongduanmu** [comment] 2020-05-21 14:30
@tristaZero Thank you very much for your suggestions, I also prefer the first way. The second way can quickly solve the problem in this issue, but there may be other similar scenarios where the error will occur, such as using between and in the where statement.
The impact of the first method is relatively large, I will carefully check it, and then submit a pr. 😁

**Comment by strongduanmu** [comment] 2020-05-21 16:07
@tristaZero Thank you for your suggestion.  Because this change has a great impact, and the long and int types have better performance in calculations than the biginteger type, so I may prefer the second way now.  
In the range query, we should initialize range class with the same data type to avoid such exception.
I will try to solve this issue in the second way, do you have any other suggestions?😀

**Comment by tristaZero** [comment] 2020-05-22 02:49
> In the range query, we should initialize range class with the same data type to avoid such exception.
@strongduanmu Hi, which class does do you mean?

**Comment by strongduanmu** [comment] 2020-05-23 16:18
> Hi, which class does do you mean?

@tristaZero Sorry for the late reply, I originally planned to modify the `createRouteValueMap` method in `WhereClauseShardingConditionEngine` class, based on the same column as a group, and then generate the same numeric type in the group. But after trying, I found that there are many implementation classes of the PredicateSegment class, I need to do a lot of meaningless judgment to get the values in the group, and then generate same numeric type value.

```java
private Map<Column, Collection<RouteValue>> createRouteValueMap(final SQLStatementContext sqlStatementContext, final AndPredicate andPredicate, final List<Object> parameters) {
    Map<Column, Collection<RouteValue>> result = new HashMap<>();
    for (PredicateSegment each : andPredicate.getPredicates()) {
        Optional<String> tableName = sqlStatementContext.getTablesContext().findTableName(each.getColumn(), schemaMetaData);
        if (!tableName.isPresent() || !shardingRule.isShardingColumn(each.getColumn().getIdentifier().getValue(), tableName.get())) {
            continue;
        }
        Column column = new Column(each.getColumn().getIdentifier().getValue(), tableName.get());
        Optional<RouteValue> routeValue = ConditionValueGeneratorFactory.generate(each.getRightValue(), column, parameters);
        if (!routeValue.isPresent()) {
            continue;
        }
        if (!result.containsKey(column)) {
            result.put(column, new LinkedList<>());
        }
        result.get(column).add(routeValue.get());
    }
    return result;
}
```

So I tried the second solution you suggested, and made some conversions where the Range operation was performed. I have submitted a [PR](https://github.com/apache/shardingsphere/pull/5770), can you help me review it? 😃 

BTW, I also tried the first solution, and all returned BigInteger types, which would cause many existing unit tests to report errors, so I still prefer the second method.

**Closed** 2020-05-26 08:23 UTC
Labels: bug, volunteer wanted
