### ISSUE TITLE
Print error SQL when throwing exception.SQLParsingException

### ISSUE THREAD

**Issue by Mr-Yu-95** [apache/shardingsphere#18455] opened 2022-06-20 09:01 UTC
Hi community：
     Now，the ShardingSphere can print exception log when we want to excute error SQL.
     For example Cause: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax.
    However, when throwing error sql exception, the shardingSphere cant print error sql needing to parser   to help developer modify sql. I hope the shardingSphere can have the feature. Now,"sql-show:true "cant achieve the goal.  
    My shardingSphere version is 5.0.0

**Comment by terrymanu** [comment] 2022-06-23 13:20
It is better to throw the root cause of SQL parser Exception. 
@yuzhiping95 Do you interest to do the enhancement?

**Comment by xuup** [comment] 2022-06-25 15:19
Could you please assign this issue to me?

**Comment by ninjaboy97** [comment] 2022-06-25 19:59
Hey @terrymanu, raised a PR for this. I wasn't sure what needs to be done in case of FeaturedDistSQLStatementParserEngine throwing a SQLParseException since any of the instances from FeaturedDistSQLStatementParserFacadeFactory could be throwing the exception. Let me know what needs to be done here. Can you please also approve the CI workflows?

Also @xuup apologies, I started working on this and missed your comment before raising the PR.

**Comment by terrymanu** [comment] 2022-07-05 04:47
Hi @ninjaboy97 the screenshot from MySQL cli to report error is necessary.
I don't make sure the result when exception thrown.

**Comment by terrymanu** [comment] 2022-08-12 04:07
Hi community, this issue still open for pick up.

**Closed** 2022-08-31 07:08 UTC
Labels: in: SQL parse, good first issue
