### ISSUE TITLE
sql hint and other strategies are configured at the same time, regardless of the order of strategies, they are routed by sqlhint

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#19303] opened 2022-07-18 01:52 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_282
ShardingSphere-5.1.3-SNAPSHOT
Commit ID: 7c67365b394d2e3ac562329b550c135c31ea764d
Commit Message: Avoid overhead of invoking method in Optional.orElse (#18921)
Branch: 7c67365b394d2e3ac562329b550c135c31ea764d
Build time: 2022-07-08T19:24:17+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
sql hint and other strategies are configured at the same time, routed by the order of strategies
### Actual behavior
sql hint and other strategies are configured at the same time, regardless of the order of strategies, they are routed by sqlhint
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1、create traffic rule
```
drop traffic rule sql_hint_traffic;
drop traffic rule sql_match_traffic;
create traffic rule sql_match_traffic (labels(sharding2),
traffic_algorithm(type(name=sql_match,properties("sql" = "SELECT * FROM t_order WHERE content IN (?, ?);update t_order set content='test11' where user_id=11;"))),
load_balancer(type(name=round_robin)));
create traffic rule sql_hint_traffic(labels(sharding1),
traffic_algorithm(type(name=SQL_HINT)),
load_balancer(type(name=round_robin)));
show traffic rules;
```

2、ss-jdbc excute sql，hint:useTraffic=true
```
	@Test
	public void testTraffic_22() throws SQLException {
		String sql = "/* shardingsphere hint:useTraffic=true */SELECT * FROM t_order WHERE content IN (?, ?)";
		String sql2 = "/* shardingsphere hint:useTraffic=true */update  t_order   set content='test11'   where   user_id=11;";
		for (int i = 0; i < 10; i++) {
			PreparedStatement statement = getPreparedStatement(sql, Arrays.asList("test1", "test10"));
			statement.executeQuery();
			getStatement().executeUpdate(sql2);
		}
	}
```

3、change traffic rules's order
```
drop traffic rule sql_hint_traffic;
drop traffic rule sql_match_traffic;
create traffic rule sql_hint_traffic(labels(sharding1),
traffic_algorithm(type(name=SQL_HINT)),
load_balancer(type(name=round_robin)));
create traffic rule sql_match_traffic (labels(sharding2),
traffic_algorithm(type(name=sql_match,properties("sql" = "SELECT * FROM t_order WHERE content IN (?, ?);update t_order set content='test11' where user_id=11;"))),
load_balancer(type(name=round_robin)));
show traffic rules;
```

4、repeat step 2

**Comment by strongduanmu** [comment] 2022-07-18 01:55
@peilinqian Thank you for your feedback, I will investigate this issue.

**Comment by strongduanmu** [comment] 2022-07-18 02:59
Hi @peilinqian, I have test your case. Since SQL comments are also part of the SQL content, `/* shardingsphere hint:useTraffic=true */SELECT * FROM t_order WHERE content IN (?, ?)` cannot match the SQL_MATCH algorithm. You can modify the parameters in the SQL_MATCH algorithm, or adjust the SQL for the test.

**Comment by strongduanmu** [comment] 2022-07-18 03:01
This is not a bug, but a misuse of the SQL_MATCH algorithm, so I will close this issue.

**Closed by strongduanmu** 2022-07-18 03:01 UTC
Labels: status: invalid, in: kernel
