### ISSUE TITLE
name LIKE ?  escape '!'  Exception "java.lang.String cannot be cast to java.lang.Integer"

### ISSUE THREAD

**Issue by Pancratius** [apache/shardingsphere#19795] opened 2022-08-02 08:21 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
`            <dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
                <version>5.1.1</version>
            </dependency>
`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-JDBC`

### Expected behavior
`
natvie SQL query : SELECT * FROM record  WHERE name LIKE ?  escape '!'  LIMIT ? OFFSET ? 
`

### Actual behavior
`
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at org.apache.shardingsphere.infra.binder.segment.select.pagination.PaginationContext.getValue(PaginationContext.java:57)
	at org.apache.shardingsphere.infra.binder.segment.select.pagination.PaginationContext.<init>(PaginationContext.java:51)
	at org.apache.shardingsphere.infra.binder.segment.select.pagination.engine.LimitPaginationContextEngine.createPaginationContext(LimitPaginationContextEngine.java:38)
	at org.apache.shardingsphere.infra.binder.segment.select.pagination.engine.PaginationContextEngine.createPaginationContext(PaginationContextEngine.java:57)
	at org.apache.shardingsphere.infra.binder.statement.dml.SelectStatementContext.setUpParameters(SelectStatementContext.java:338)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.createLogicSQL(ShardingSpherePreparedStatement.java:478)
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.executeQuery(ShardingSpherePreparedStatement.java:207)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2297)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2050)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
	at org.hibernate.loader.Loader.doQuery(Loader.java:948)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349)
	at org.hibernate.loader.Loader.doList(Loader.java:2843)
	at org.hibernate.loader.Loader.doList(Loader.java:2825)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2657)
	at org.hibernate.loader.Loader.list(Loader.java:2652)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2141)
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1169)
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:176)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1604)
	at org.hibernate.query.Query.getResultList(Query.java:165)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:126)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:155)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:143)
`

### Reason analyze (If you can)
`
SELECT * FROM record  WHERE name LIKE ?  escape '!'  LIMIT ? OFFSET ? 
`
throw java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer

but 
`
SELECT * FROM record  WHERE name LIKE ?   LIMIT ? OFFSET ? 
`
run success.

**Comment by strongduanmu** [comment] 2022-08-02 08:28
@Pancratius Thank you for your feedback, I will check this exception.

**Comment by strongduanmu** [comment] 2022-08-03 08:07
@Pancratius Can you try 5.1.2 or master branch, this bug has been fixed.

**Comment by Pancratius** [comment] 2022-08-04 06:30
I change version to 5.1.2, it is not ok.


I tested the other cases, the situation is as follows：

**success sql**：

1. SELECT * FROM record WHERE name LIKE ? escape '!' 
2. SELECT * FROM record WHERE name LIKE ? escape '!' LIMIT 20 OFFSET 0
3. SELECT * FROM record WHERE name LIKE ? LIMIT ? OFFSET ?


**failure sql:**

SELECT * FROM record WHERE name LIKE ? escape '!' LIMIT ? OFFSET ?


Looking forward to reply, thank you.

**Comment by Pancratius** [comment] 2022-08-04 06:31
> I change version to 5.1.2, it is not ok.
> 
> I tested the other cases, the situation is as follows：
> 
> **success sql**：
> 
> 1. SELECT * FROM record WHERE name LIKE ? escape '!'
> 2. SELECT * FROM record WHERE name LIKE ? escape '!' LIMIT 20 OFFSET 0
> 3. SELECT * FROM record WHERE name LIKE ? LIMIT ? OFFSET ?
> 
> **failure sql:**
> 
> SELECT * FROM record WHERE name LIKE ? escape '!' LIMIT ? OFFSET ?
> 
> Looking forward to reply, thank you.

@strongduanmu

**Comment by strongduanmu** [comment] 2022-08-04 06:56
@Pancratius Can you provide your test code? I can't reproduce this exception with 5.1.2.

**Comment by Pancratius** [comment] 2022-08-04 08:54
@strongduanmu  This is a simple demo.

[sharding1.zip](https://github.com/apache/shardingsphere/files/9258167/sharding1.zip)

**Comment by Pancratius** [comment] 2022-08-09 06:52
@strongduanmu Looking forward to reply, thank you.

**Comment by strongduanmu** [comment] 2022-08-09 06:59
@Pancratius Thank you for your remind, I will test your demo program.

**Comment by strongduanmu** [comment] 2022-08-09 09:02
Hi @tianhao960, are you interested in this issue?

**Comment by tianhao960** [comment] 2022-08-16 04:05
@strongduanmu , sure , I‘ll try

**Comment by strongduanmu** [comment] 2022-08-16 04:08
That's great, I will assign this issue to you.

**Closed** 2022-08-17 14:31 UTC
Labels: in: SQL parse
