### ISSUE TITLE
About routing errors in Sharding-Proxy in master

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#13200] opened 2021-10-21 09:04 UTC
when I execute the sql:
 select * from t_order o inner join t_order_item t on o.order_id=t.order_id and t.order_id=1 and o.user_id=1;
It did not route properly，I did not set these two tables as binding tables
A strange phenomenon occurred：
![image](https://user-images.githubusercontent.com/45256940/138245763-4113f979-3cc2-4f5c-b425-17eb55ea1a3f.png)
 it turned out that the real table is t_order, t_order_item. and It was executed incredibly successfully  ！！These two tables are not in my real database,
![image](https://user-images.githubusercontent.com/45256940/138247515-778fd06e-4f6a-451d-b732-5d394fccf11e.png)

And the logic of the sub-database is also invalid,According to the fragmentation rules, it will only be routed to ds_1 and t_order_1, t_order_item_1

here are my configuration:
![image](https://user-images.githubusercontent.com/45256940/138246099-65b57da6-6adf-401c-9d09-768117e4bb12.png)
![image](https://user-images.githubusercontent.com/45256940/138246166-64419544-a1cb-4a70-a779-a24a815140cb.png)
![image](https://user-images.githubusercontent.com/45256940/138246209-17774c48-18b6-4bf0-b3ef-b4874bfe2c93.png)

**Comment by strongduanmu** [comment] 2021-10-21 10:44
@marker-wu Thank you for your feedback, this is not a bug. When two sharding tables are not configured with a binding table relationship, the federation execution engine will be used, and the logical sql will not be rewritten at this time.

**Comment by CrackerSuperior** [comment] 2021-10-22 03:55
> > @marker-wu Thank you for your feedback, this is not a bug. When two sharding tables are not configured with a binding table relationship, the federation execution engine will be used, and the logical sql will not be rewritten at this time.
> 
> But there is no t_order and t_order_item tables in my database when the sql is actually executed, why is it executed successfully?

"Sharding" can of course find it. Didn't you configure it in the configuration file?

**Comment by terrymanu** [comment] 2022-02-20 16:04
I just close the issue because of no feedback for long time.

**Closed by terrymanu** 2022-02-20 16:04 UTC
Labels: type: question
