### ISSUE TITLE
2Unknown exception: [Cannot invoke method hashCode() on null object]

### ISSUE THREAD

**Issue by duzhanfei** [apache/shardingsphere#8913] opened 2021-01-06 08:31 UTC
### Which version of ShardingSphere did you use?
5.0.0-alpha
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

When I insert data with shardingproxy5.0.0-alpha, the null pointer is prompted, but my sharding key is not empty. Everything works fine with shardingproxy4.1.1

config：

schemaName: sharding_db

dataSourceCommon:
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50
  minPoolSize: 1
  maintenanceIntervalMilliseconds: 30000

dataSources:
  ds_0:
    url: jdbc:mysql://192.2.171.54:3306/db_0?serverTimezone=UTC&useSSL=false
    username: crmuser
    password: crm123
  ds_1:
    url: jdbc:mysql://192.2.171.55:3306/db_1?serverTimezone=UTC&useSSL=false
    username: crmuser
    password: crm123
  ds_2:
    url: jdbc:mysql://192.2.171.56:3306/db_2?serverTimezone=UTC&useSSL=false
    username: crmuser
    password: crm123
  ds_3:
    url: jdbc:mysql://192.2.171.57:3306/db_3?serverTimezone=UTC&useSSL=false
    username: crmuser
    password: crm123

rules:
- !SHARDING
  tables:
    PBCST_QRY_INFO:
      actualDataNodes: ds_${0..3}.PBCST_QRY_INFO_${0..15}
      tableStrategy:
        standard:
          shardingColumn: ECIF_CUST_NO
          shardingAlgorithmName: PBCST_QRY_INFO_inline
      databaseStrategy:
        standard:
          shardingColumn: ECIF_CUST_NO
          shardingAlgorithmName: database_inline          
      keyGenerateStrategy:
        column: ECIF_CUST_NO
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    standard:
      shardingColumn: ECIF_CUST_NO
      shardingAlgorithmName: database_default	    
  defaultTableStrategy:
    none:
  shardingAlgorithms:
    database_default:
      type: INLINE
      props:
        algorithm-expression: ds_0
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${Math.abs(ECIF_CUST_NO.hashCode() % 4)}
    PBCST_QRY_INFO_inline:
      type: INLINE
      props:
        algorithm-expression: PBCST_QRY_INFO_${Math.abs(ECIF_CUST_NO.hashCode() % 16)}		
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123

**Comment by tristaZero** [comment] 2021-01-07 05:17
Hi @duzhanfei ,

Please provide your sql and exception info. The detailed log after setting `sql-show` = `true` is preferred. 

Thanks.

**Comment by duzhanfei** [comment] 2021-01-07 06:53
sql:
INSERT INTO PBCST_QRY_INFO (
	ECIF_CUST_NO,
	CUST_APLTN,
	CUST_TYP_CD,
	MP_NBR,
	CTFTP_CD,
	CRTF_NBR,
	BLTO_PROV_ADMDV_CD,
	BLTO_CITY_ADMDV_CD,
	BLTO_DSTCY_ADMDV_CD,
	CUST_ADDR
)
VALUES
	('642054011658', '梅', '01', '1219123', '111', '6106060118', null, null, null, null)




log：
[INFO ] 14:51:32.907 [pool-79-thread-1] ShardingSphere-SQL - Logic SQL: SET PROFILING=1;
[INFO ] 14:51:32.907 [pool-79-thread-1] ShardingSphere-SQL - SQLStatement: MySQLSetStatement()
[INFO ] 14:51:32.907 [pool-79-thread-1] ShardingSphere-SQL - Actual SQL: ds_0 ::: SET PROFILING=1;
[INFO ] 14:51:32.907 [pool-79-thread-1] ShardingSphere-SQL - Actual SQL: ds_1 ::: SET PROFILING=1;
[INFO ] 14:51:32.907 [pool-79-thread-1] ShardingSphere-SQL - Actual SQL: ds_2 ::: SET PROFILING=1;
[INFO ] 14:51:32.907 [pool-79-thread-1] ShardingSphere-SQL - Actual SQL: ds_3 ::: SET PROFILING=1;
[INFO ] 14:51:32.926 [pool-79-thread-1] ShardingSphere-SQL - Logic SQL: SHOW STATUS
[INFO ] 14:51:32.926 [pool-79-thread-1] ShardingSphere-SQL - SQLStatement: MySQLShowOtherStatement()
[INFO ] 14:51:32.926 [pool-79-thread-1] ShardingSphere-SQL - Actual SQL: ds_0 ::: SHOW STATUS
[INFO ] 14:51:32.940 [pool-79-thread-1] ShardingSphere-SQL - Logic SQL: SHOW STATUS
[INFO ] 14:51:32.940 [pool-79-thread-1] ShardingSphere-SQL - SQLStatement: MySQLShowOtherStatement()
[INFO ] 14:51:32.940 [pool-79-thread-1] ShardingSphere-SQL - Actual SQL: ds_0 ::: SHOW STATUS
[ERROR] 14:51:33.080 [pool-79-thread-1] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.NullPointerException: Cannot invoke method hashCode() on null object
        at org.codehaus.groovy.runtime.NullObject.hashCode(NullObject.java:174)
        at org.codehaus.groovy.runtime.NullObject$hashCode.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at java_lang_String$hashCode.call(Unknown Source)
        at Script40$_run_closure1.doCall(Script40.groovy:1)
        at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:420)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.apache.shardingsphere.sharding.algorithm.sharding.inline.InlineShardingAlgorithm.doSharding(InlineShardingAlgorithm.java:69)
        at org.apache.shardingsphere.sharding.route.strategy.type.standard.StandardShardingStrategy.doSharding(StandardShardingStrategy.java:67)
        at org.apache.shardingsphere.sharding.route.strategy.type.standard.StandardShardingStrategy.doSharding(StandardShardingStrategy.java:56)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeDataSources(ShardingStandardRoutingEngine.java:203)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route0(ShardingStandardRoutingEngine.java:191)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeByShardingConditionsWithCondition(ShardingStandardRoutingEngine.java:114)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeByShardingConditions(ShardingStandardRoutingEngine.java:107)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.getDataNodes(ShardingStandardRoutingEngine.java:84)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route(ShardingStandardRoutingEngine.java:69)
        at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:70)
        at org.apache.shardingsphere.sharding.route.engine.ShardingSQLRouter.createRouteContext(ShardingSQLRouter.java:55)
        at org.apache.shardingsphere.infra.route.engine.impl.PartialSQLRouteExecutor.route(PartialSQLRouteExecutor.java:59)
        at org.apache.shardingsphere.infra.route.engine.SQLRouteEngine.route(SQLRouteEngine.java:57)
        at org.apache.shardingsphere.infra.context.kernel.KernelProcessor.generateExecutionContext(KernelProcessor.java:52)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:77)
        at org.apache.shardingsphere.proxy.backend.text.query.QueryBackendHandler.execute(QueryBackendHandler.java:61)
        at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:62)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:100)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO ] 14:51:42.764 [pool-73-thread-1] ShardingSphere-SQL - Logic SQL: SELECT @@session.transaction_read_only
[INFO ] 14:51:42.764 [pool-73-thread-1] ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(limit=Optional.empty, lock=Optional.empty)
[INFO ] 14:51:42.764 [pool-73-thread-1] ShardingSphere-SQL - Actual SQL: ds_0 ::: SELECT @@session.transaction_read_only
[ERROR] 14:51:42.767 [pool-73-thread-1] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.NullPointerException: Cannot invoke method hashCode() on null object
        at org.codehaus.groovy.runtime.NullObject.hashCode(NullObject.java:174)
        at org.codehaus.groovy.runtime.NullObject$hashCode.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.NullObject$hashCode.call(Unknown Source)
        at Script40$_run_closure1.doCall(Script40.groovy:1)
        at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:420)
        at groovy.lang.Closure.call(Closure.java:414)
        at org.apache.shardingsphere.sharding.algorithm.sharding.inline.InlineShardingAlgorithm.doSharding(InlineShardingAlgorithm.java:69)
        at org.apache.shardingsphere.sharding.route.strategy.type.standard.StandardShardingStrategy.doSharding(StandardShardingStrategy.java:67)
        at org.apache.shardingsphere.sharding.route.strategy.type.standard.StandardShardingStrategy.doSharding(StandardShardingStrategy.java:56)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.routeDataSources(ShardingStandardRoutingEngine.java:203)
        at org.apache.shardingsphere.sharding.route.engine.type.standard.ShardingStandardRoutingEngine.route0(ShardingStandardRoutingEngine.java:191)

**Comment by tristaZero** [comment] 2021-01-08 03:53
Hi @duzhanfei ,

Thanks for your feedback. Is that an entire log? You don't skip something, do you?

Could you try a SQL without null value (`VALUES
('642054011658', '梅', '01', '1219123', '111', '6106060118', null, null, null, null)`)?

Besides, it looks like we have inadequate support for `MySQLShowOtherStatement` and `SELECT @@session.transaction_read_only` in `ShardingRouteEngineFactory`, which needs in-depth debugging.

**Comment by tristaZero** [comment] 2021-01-08 04:01
Hi community,

### Tasks
Are you interested in digging into `ShardingRouteEngineFactory` to verify whether ShardingProxy can run the following SQLs well?
```SQL
SHOW STATUS;
SELECT @@session.transaction_read_only;
```

### How
- Start ShardingProxy with a sharding rule example
- Execute the SQLs above one at a time
- Check whether they can work well
- If not, please provide an exception log here, and we could consider fixing them. (My speculation is there is incorrect handling in `ShardingRouteEngineFactory`, so please give a breakpoint there if you want to do debugging.)

Thanks for your interaction and waiting for your any comments. :)

**Comment by duzhanfei** [comment] 2021-01-11 14:19
@tristaZero 

The sharding key is of type String, and  sharding rules are made by hashing values
 The following  scenarios will cause  NullPointerException 
①When querying, the sharding key is lowercase,
such as:
PBCST_QRY_INFO_${Math.abs(ecif_cust_no.hashCode() % 16)}
② When inserting data, the sharding key is uppercase
such as:
PBCST_QRY_INFO_${Math.abs(ECIF_CUST_NO.hashCode() % 16)}

**Comment by duzhanfei** [comment] 2021-01-11 14:26
https://github.com/apache/shardingsphere/issues/8303

**Comment by tristaZero** [comment] 2021-01-12 07:02
Hi, More exception log is needed to locate the cause. But if I still unsure whether your issue is related to inline expression `PBCST_QRY_INFO_${Math.abs(ECIF_CUST_NO.hashCode() % 16)}`. I suggest you give `InlineExpressionParser` attention when you debug or test.

**Comment by duzhanfei** [comment] 2021-01-12 12:47
I have provided all the exception logs

**Comment by duzhanfei** [comment] 2021-01-12 13:02
I wanna have a try. Thx.

**Comment by duzhanfei** [comment] 2021-01-12 13:27
I wanna have a try. Thx.



At 2021-01-08 12:01:44, "Juan Pan(Trista)" <notifications@github.com> wrote:

Hi community,

Tasks

Are you interested in digging into ShardingRouteEngineFactory to verify whether ShardingProxy can run the following SQLs well?

SHOW STATUS;
SELECT @@session.transaction_read_only;
How
Start ShardingProxy with a sharding rule example
Execute the SQLs above one at a time
Check whether they can work well
If not, please provide an exception log here, and we could consider fixing them. (My speculation is there is incorrect handling in ShardingRouteEngineFactory, so please give a breakpoint there if you want to do debugging.)

Thanks for your interaction and waiting for your any comments. :)

**Comment by tristaZero** [comment] 2021-01-13 03:27
Hi @duzhanfei ,
Welcome, I assigned this issue to you.



> I have provided all the exception logs

Hi, do you think the exception came from `InlineExpressionParser`?

**Comment by alongsoCJR** [comment] 2021-05-20 08:57
i meeting the same questions，please help me

**Comment by tristaZero** [comment] 2021-05-23 13:09
Hi @alongsoCJR 
Please be careful of the inputted value and the InlineExpression you configured.

**Comment by duzhanfei** [comment] 2021-05-25 00:39
you can try  to   uppercase instead of lowercase










At 2021-05-23 21:09:54, "Juan Pan(Trista)" ***@***.***> wrote:

Hi @alongsoCJR
Please be careful of the inputted value and the InlineExpression you configured.

**Closed** 2022-06-24 15:13 UTC
Labels: feature: sharding
