### ISSUE TITLE
Atomikos distributed transaction failed: java.sql.SqlException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowStreaming is still active.

### ISSUE THREAD

**Issue by frankwang314** [apache/shardingsphere#24215] opened 2023-02-17 08:30 UTC
### Which version of ShardingSphere did you use?
5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Our project is depending on shardingsphere-proxy(5.2.1) with atomikos to support distributed transactions, we hope the feature of distributed transactions work well.

### Actual behavior
I'm very sure most the apis in the condition of crossing db updating work very well, but one failed, 
the details as following:
java.sql.SqlException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowStreaming is still active.
No statements may be issued when any streaming result sets are open and in use on a given connection. 
Ensure that you have  called .close() on any active streaming results set before atempting more queries.

### Reason analyze (If you can)
The same request works well just when comments the 2 transaction annotations(as following), so I guess something wrong with proxy and atomikos.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
client: 
(1) we use spring annotation @Transactional(rollbackFor=Exception.class) and @ShardingTransactionType(TransactionType.XA) for the service method that needs distributed transaction.
(2) mysql driver: mysql-connector-java:8.0.16
(3). mysql server: 8.0.9
(4). in this method, we have 9 db queries or updatings among multiple mysqls, and the sql of the failed one is:
select a.*
from white_cust_info a,white_company b 
where a.whitecompany_id = b.id and a.whitecust_name ='test9'
and ((a.card_no = '530112197405073731' and b.demand_level = 'A') 
or (b.demand_level='B' and (a.card no ='530112197405073731' or a.phonenumber ='14754740881'))
or (b.demand_level='C' and (a.card no ='530112197405073731' or a.phonenumber ='14754740881')))
even though I dont't think there is something to do with the sql.
(5) no streaming or cursor queries.

### Example codes for reproduce this issue (such as a github link).
none

=====================================
Additional information:
when I try to change XA Provider type from Atomikos to Narayana, with the rest unchanged, the same sql failed again,

Part of stacktrace as following:
java.sql.SQLException: javax.transaction.RollbackException: ARJUNA016083: Cannot register synchronization beacause the transaction is in aborted state.
...

So It's highly possible a severe bug about xa transaction in shardingsphere-proxy, hope this could be fixed.

**Comment by zhaojinchao95** [comment] 2023-02-18 13:32
@FlyingZC Hi, can you look this? Thx.

**Comment by FlyingZC** [comment] 2023-02-23 09:19
I will investigate this issue, please assign it to me. @strongduanmu

**Comment by FlyingZC** [comment] 2023-02-28 01:38
@frankwang314 Hi,can you provide more information about the atomikos error. This error does not seem to be a transaction-related problem, but a problem with the merge engine. You can provide more exception stacks or reproducible demos.
About naryana, please refer to the official documentation of ShardingSphere, configure the corresponding file `jbossts-properties.xml` and then use it.

**Comment by FlyingZC** [comment] 2023-05-15 07:22
Closed due to no reply.

**Closed by FlyingZC** 2023-05-15 07:22 UTC
Labels: type: question, feature: transaction
