### ISSUE TITLE
v5.2, If a druid datasource has some filters, then create a ShardingSphereDataSource will occur exception

### ISSUE THREAD

**Issue by caol64** [apache/shardingsphere#21211] opened 2022-09-27 01:31 UTC
### Which version of ShardingSphere did you use?
v5.2.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Create a druid datasource, and then add some filters.
```java
DruidDataSource druidDataSource = new DruidDataSource();
// ...
druidDataSource.setProxyFilters(buildFilters());
```
2. Create a shardingsphere datasource by ShardingSphereDataSourceFactory
3. Exception occurs: Can't construct a java object for tag:yaml.org,2002:com.alibaba.druid.filter.stat.StatFilter; exception=Class is not accepted: com.alibaba.druid.filter.stat.StatFilter.

### Example codes for reproduce this issue (such as a github link).
https://github.com/caol64/sharding-test

**Comment by caol64** [comment] 2022-09-30 01:36
Can someone take a time to give some suggestion? The main reason is this method has a strong validation:

![image](https://user-images.githubusercontent.com/6183265/193169843-370353c6-2ab1-438d-b075-76b1cce02d2f.png)

In this case, Druid datasource was added some filters (eg: StatFilter). When entered this method, the rootClass is a map and the className is a druid filter, validated failed.

@strongduanmu @linghengqian

**Comment by linghengqian** [comment] 2022-09-30 06:43
@caol64 

- Do you mean that we should set up an ArrayList to put Alibaba Druid's plugin-related classes into it, and then add a judgment about the array to this if judgment?  

- But it would surprise me if ShardingSphere 5.1.2 is normal, because this code is there before 5.1.2, it sounds like the problem happens when the java class ( Of course, I mean Alibaba Druid's class ) is serialized to yaml.

- I don't have time to troubleshoot this problem these days. I have several issues of my own that need to be dealt with on my timeline.

**Comment by caol64** [comment] 2022-09-30 08:24
> @caol64
> 
> * Do you mean that we should set up an ArrayList to put Alibaba Druid's plugin-related classes into it, and then add a judgment about the array to this if judgment?
> * But it would surprise me if ShardingSphere 5.1.2 is normal, because this code is there before 5.1.2, it sounds like the problem happens when the java class ( Of course, I mean Alibaba Druid's class ) is serialized to yaml.
> * I don't have time to troubleshoot this problem these days. I have several issues of my own that need to be dealt with on my timeline.

Thank you for replying. The same code run in 5.1.2 is OK. Only when upgrading to 5.2.0 will cause this error.

**Comment by hyz1994121** [comment] 2022-09-30 09:38
> Can someone take a time to give some suggestion? The main reason is this method has a strong validation:
> 
> ![image](https://user-images.githubusercontent.com/6183265/193169843-370353c6-2ab1-438d-b075-76b1cce02d2f.png)
> 
> In this case, Druid datasource was added some filters (eg: StatFilter). When entered this method, the rootClass is a map and the className is a druid filter, validated failed.
> 
> @strongduanmu @linghengqian

这个问题解决方式多个，xml配置改为java api方式配置数据源 亲测可用
那个snakeyaml版本升级到1.32好像也可以
in my issue， i solved the problem, change druid datasource from spring-bean-namespace.xml to java api config
or change the snake-yaml version from 1.30 to 1.32

**Comment by linghengqian** [comment] 2022-09-30 09:46
@hyz1994121 

- Interesting point, I tested @sluk3r  's example three days ago with a commit from https://github.com/apache/shardingsphere/pull/21048 and the issue was not resolved.  I'm not sure if it's a problem with my local environment.

**Comment by linghengqian** [comment] 2022-10-05 16:33
@caol64 

- I noticed that the problem actually came from https://github.com/apache/shardingsphere/blob/master/infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/YamlEngine.java#L107  , the treatment here is interesting.  If an `Object` is not a `Collection`, it is directly serialized into a `Yaml 1.1 Map`.  How do you think we should deal with it?  As a tool class, it is impossible to call Alibaba Druid classes in this place.  

- Of course, https://github.com/apache/shardingsphere/pull/21351 has nothing to do with this.

**Comment by Scorpiord** [comment] 2022-11-30 09:42
@linghengqian 
hello, I have met the same problem.Is there a plan to support this issue?

**Comment by linghengqian** [comment] 2022-11-30 10:31
> @linghengqian 
> hello, I have met the same problem.Is there a plan to support this issue?

- I don't know what the originator of the current issue is thinking, and I don't know how to fix it, so it's not on my priority list. 

- If you have PR, you can submit it directly.

**Comment by linghengqian** [comment] 2023-01-04 17:29
- I looked back and looked at this problem, which mainly needs to be aligned with the yaml processing of the druid springboot starter, `com.alibaba.druid.filter.logging.LogFilter`, `com.alibaba.druid.filter.stat.StatFilter`, `com.alibaba.druid. wall.WallConfig` is serialized into YAML 1.1 Map according to a set of rigid process, which is somewhat similar to https://github.com/baomidou/dynamic-datasource-spring-boot-starter/tree/master/src%2Fmain%2Fjava %2Fcom%2Fbaomidou%2Fdynamic%2Fdatasource%2Fspring%2Fboot%2Fautoconfigure%2Fdruid .

- This almost has to import druid's springboot starter as a test dependency into the shardingsphere master branch, because only druid will have this situation. 

- Considering that the PR involved in https://github.com/alibaba/druid/issues/4673 has not been merged for a long time, I don't really want to deal with it in a very unfriendly way, unless some friends know how to bypass the druid's springboot starter which is actually not available.

**Comment by study-renjie** [comment] 2023-08-10 02:44
> Can someone take a time to give some suggestion? The main reason is this method has a strong validation:
> 
> ![image](https://user-images.githubusercontent.com/6183265/193169843-370353c6-2ab1-438d-b075-76b1cce02d2f.png)
> 
> In this case, Druid datasource was added some filters (eg: StatFilter). When entered this method, the rootClass is a map and the className is a druid filter, validated failed.
> 
> @strongduanmu @linghengqian
hello 


> > @caol64
> > 
> > * 你的意思是我们应该建立一个ArrayList，把阿里巴巴Druid的插件相关的类放进去，然后在这个if判断中添加一个关于数组的判断？
> > * 但如果ShardingSphere 5.1.2正常的话，我会感到惊讶，因为这段代码在5.1.2之前就有，听起来是java类（当然我指的是阿里巴巴Druid的类）序列化到yaml时出现的问题。
> > * 这些天我没有时间解决这个问题。我自己有几个问题需要在我的时间表上处理。
> 
> 谢谢您的回复。相同的代码在5.1.2中运行是可以的。只有升级到5.2.0时才会出现这个错误。

**Comment by study-renjie** [comment] 2023-08-10 02:49
> > @caol64
> > 
> > * 你的意思是我们应该建立一个ArrayList，把阿里巴巴Druid的插件相关的类放进去，然后在这个if判断中添加一个关于数组的判断？
> > * 但如果ShardingSphere 5.1.2正常的话，我会感到惊讶，因为这段代码在5.1.2之前就有，听起来是java类（当然我指的是阿里巴巴Druid的类）序列化到yaml时出现的问题。
> > * 这些天我没有时间解决这个问题。我自己有几个问题需要在我的时间表上处理。
> 
> 谢谢您的回复。相同的代码在5.1.2中运行是可以的。只有升级到5.2.0时才会出现这个错误。

Hello, I also encountered this problem, did you solve this problem? what is the solution? thx

**Comment by study-renjie** [comment] 2023-08-10 02:50
> @caol64
> 
> * 我注意到问题实际上来自[https://github.com/apache/shardingsphere/blob/master/infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/YamlEngine.java# L107](https://github.com/apache/shardingsphere/blob/master/infra/util/src/main/java/org/apache/shardingsphere/infra/util/yaml/YamlEngine.java#L107)   ，这里的处理很有趣。如果 an`Object`不是 a `Collection`，则直接序列化为 a `Yaml 1.1 Map`。您认为我们应该如何处理？作为一个工具类，不可能在这个地方调用阿里巴巴Druid类。
> * 当然，[将 Snakeyaml 更新到 1.33 并开放 YAML 3MB 限制 #21351](https://github.com/apache/shardingsphere/pull/21351)与此无关。

hello, is this problem has been solved and what is the solution?

**Comment by linghengqian** [comment] 2023-08-10 12:11
> > > @caol64
> > > 
> > > * 你的意思是我们应该建立一个ArrayList，把阿里巴巴Druid的插件相关的类放进去，然后在这个if判断中添加一个关于数组的判断？
> > > * 但如果ShardingSphere 5.1.2正常的话，我会感到惊讶，因为这段代码在5.1.2之前就有，听起来是java类（当然我指的是阿里巴巴Druid的类）序列化到yaml时出现的问题。
> > > * 这些天我没有时间解决这个问题。我自己有几个问题需要在我的时间表上处理。
> > 
> > 
> > 谢谢您的回复。相同的代码在5.1.2中运行是可以的。只有升级到5.2.0时才会出现这个错误。
> 
> Hello, I also encountered this problem, did you solve this problem? what is the solution? thx

- @study-renjie  For Alibaba Druid, I think the answer to this question is No. If you have a fixed PR, you can open it directly.

**Comment by hsld9527** [comment] 2023-10-27 10:26
org.apache.shardingsphere:shardingsphere-jdbc-core:5.2.1
com.alibaba:druid:1.2.18
snakeyaml1.32or1.33
springboot2.7.12

The same problem is reproduced

**Comment by freenet-233** [comment] 2024-01-10 15:22
I solved it via Java API, there are not better ways to handle it so far

**Comment by hsld9527** [comment] 2024-01-19 06:40
> I solved it via Java API, there are not better ways to handle it so far

well, nice avatar, I did not update to 5.x finally. I solved snakeyaml2.0 problem by override org.yaml.snakeyaml.representer.Representer

**Comment by linghengqian** [comment] 2024-02-06 17:32
- Druid 1.2.21 with https://github.com/alibaba/druid/pull/5603 was released last month, so I can introduce druid's spring boot starter on the shardingsphere side for unit testing. Druid's connection pool does not include YAML property parsing, so I expect a comparable result. 

- Not only that, shardingsphere is implicitly passing the test dependency of druid 1.2.6, which requires more investigation.

**Comment by linghengqian** [comment] 2024-02-07 14:06
- @caol64 I verified it at https://github.com/linghengqian/sharding-test/commit/37731ed5cb419eb0de8146fb13b065f60032f8da . Although this issue exists in ShardingSphere 5.4.1, the current master branch of ShardingSphere 5.4.2-SNAPSHOT has fixed this issue. You can verify it by following the steps below.
```bash
sdk install java 21.0.2-graalce
sdk use java 21.0.2-graalce

git clone git@github.com:apache/shardingsphere.git
cd ./shardingsphere/
git reset --hard 4870f418997d07c61fbcc4f1a49ef812be084f47
./mvnw clean install -Prelease -T1C -DskipTests -Djacoco.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true

cd ../

git clone git@github.com:linghengqian/sharding-test.git
cd ./sharding-test/
./gradlew clean test
```
- Since there is no PR associated with this issue, I can only label this issue as fixed. If anyone finds a new problem in the master branch, they can open a new issue with unit tests.
```shell
$ ./gradlew clean test

BUILD SUCCESSFUL in 3s
3 actionable tasks: 3 executed
```

**Closed** 2024-02-07 14:07 UTC
Labels: type: bug, in: JDBC, type: fixed
