### ISSUE TITLE
when using h2 database mode=MySQL ColumnMetaDataLoader.generateEmptyResultSQL get wrong result

### ISSUE THREAD

**Issue by whg903** [apache/shardingsphere#6839] opened 2020-08-14 07:43 UTC
with shardingspere 4.1.0 or 4.1.1，
spring.datasource.url=jdbc:h2:mem:db;MODE=MySQL;DB_CLOSE_DELAY=-1
the error is :
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "t_order" not found; SQL statement:
SELECT * FROM "t_order" WHERE 1 != 1; [42102-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	... ...
	at org.apache.shardingsphere.sql.parser.binder.metadata.column.ColumnMetaDataLoader.load(ColumnMetaDataLoader.java:75)
	at org.apache.shardingsphere.sql.parser.binder.metadata.table.TableMetaDataLoader.load(TableMetaDataLoader.java:46)
	at org.apache.shardingsphere.core.metadata.ShardingMetaDataLoader.load(ShardingMetaDataLoader.java:83)
	at org.apache.shardingsphere.core.metadata.ShardingMetaDataLoader.loadShardingSchemaMetaData(ShardingMetaDataLoader.java:134)
	at org.apache.shardingsphere.core.metadata.ShardingMetaDataLoader.load(ShardingMetaDataLoader.java:125)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.context.ShardingRuntimeContext.loadSchemaMetaData(ShardingRuntimeContext.java:65)

in H2 MySQL compatible mode, should use ` for table or field name

**Comment by Lucas-307** [comment] 2020-08-14 09:39
@whg903 ,From the stack log, I think it's cause by you didn't init h2 database. you should create table "t_order" first.
`Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "t_order" not found`

**Comment by whg903** [comment] 2020-08-14 12:43
@Lucas-307
I'm sure the table t_order has been created.
I test with sql [select * from t_order where 1 != 1] got ok,  but with [select * from "t_order" where 1 != 1] got fail.
So, it may be fault of ColumnMetaDataLoader.generateEmpytResultSQL, it add synatx ["] around table name.
In h2 mysql mode, should use [`] but not ["]. 
Should pass databaseType.getTrunkDatabaseType() to method generateEmptyResultSQL?

**Comment by Lucas-307** [comment] 2020-08-15 01:46
@whg903 Yes, I think you are right. Please Let @tristaZero to give a look.

**Comment by tristaZero** [comment] 2020-08-15 03:31
@whg903 Hi, I am glad to see your debugging result instead of just a question or pointless exception info, nice!
I give a glance at`ColumnMetaDataLoader.generateEmpytResultSQL`.  My feeling is that it is an excellent work by using literal judgment and handling. What's more, It seems to affect your issue. Maybe we can ping the author of this function to give us an explanation. Thanks @tuohai666

**Comment by tuohai666** [comment] 2020-08-17 09:26
ColumnMetaDataLoader in SQL Parser module only accept database type input, no more information (MODE=MySQL) will be transferred.
If ColumnMetaDataLoader receive an H2 type, delimiter (") will be added.

**Comment by whg903** [comment] 2020-08-19 00:57
I feel disappointed for won't fix this bug. 
Version 4.0.0 is ok, but 4.1.0+ has this problem, that's important for unit test.
Why not change "String databaseType" to "DatabaseType databaseType" of TableMetaDataLoader.load and ColumnMetaDataLoader.load, then can use "instanceof BranchDatabaseType" and "BranchDatabaseType.getTrunkDatabaseType" to get actual database type info.
If H2 mysql mode is not supported,  what's  the use of H2DatabaseType.getTrunkDatabaseType?

**Comment by tuohai666** [comment] 2020-08-19 03:22
@whg903 You are right, let's reopen this issue. Since you have analyzed this problem, would you like to submit a pull request?

**Comment by whg903** [comment] 2020-08-19 03:26
OK, I'll try submit pull request this weekend, tks.

**Comment by tuohai666** [comment] 2020-08-19 03:43
I found that integrated test of ShardingSphere has already used MODE=MySQ, and didn't meet problem.
It seems like version 1.4.196 is OK. What's your h2 version?

**Comment by tuohai666** [comment] 2020-08-19 04:15
Strange, I have tested from 1.1.x to 1.4.x, but can't reproduce this problem.

**Comment by whg903** [comment] 2020-08-19 06:18
@tuohai666 Thank you very much.
After test more, I finally found:
1. h2 1.4.196 and before not support mysql ` ` syntax.
2. h2 1.4.197~1.4199 support `` but not ""
3. h2 1.4.200 all is ok
Unfortunately the version i am using is 1.4.199.
After update to 1.4.200 , the problem disappeared
I can't find  related issue or pr in changelog of h2 1.4.200.

**Comment by tuohai666** [comment] 2020-08-19 07:47
It seems like H2 decide to support both from 1.4.200. So, let's change to 1.4.200 to resolve this problem. What do you think?

**Closed** 2020-08-21 03:25 UTC
Labels: won't fix
