### ISSUE TITLE
shardingsphere-sql-parser-binder 4.1.1  generateEmptyResultSQL make a mistake Error: ralation "snapshot" does not exist gaussdb

### ISSUE THREAD

**Issue by chenyao1234** [apache/shardingsphere#25006] opened 2023-04-04 08:22 UTC
snapshot is a schema, not a table

**Comment by strongduanmu** [comment] 2023-04-10 04:39
Hi @chenyao1234, 4.1.1 is too old, please try the latest 5.3.2 version.

**Comment by strongduanmu** [comment] 2023-04-10 04:39
Besides, please submit an issue according to bug template, and provide the step to reproduce exception.

**Comment by strongduanmu** [comment] 2023-04-10 04:40
Because this issue is not standard and does not provide enough information, I will close it first. If there are still problems with the new version, welcome to submit the new issue.

**Closed by strongduanmu** 2023-04-10 04:40 UTC
Labels: status: invalid
