### ISSUE TITLE
With binding table configuration ，Failed to start proxy，“Invalid binding table configuration in ShardingRuleConfiguration”

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#20746] opened 2022-09-03 08:10 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_292
ShardingSphere-5.1.3-SNAPSHOT
Commit ID: dirty-635d9db1bc423ad1d55d6f986d71bc2b47acf922
Commit Message: Fix RUL DistSQL execution failure in transaction(#19831) (#19834)
Tag: 5.2.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
With binding table configuration ，Start proxy normally；

### Actual behavior
With binding table configuration ，Failed to start proxy；

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![9QK9_UJFF9 6SMETQOSJJC6](https://user-images.githubusercontent.com/97432411/188262057-2ff2af8e-d16f-41a2-aa8e-f0636c941ec6.png)

9dd0d3990c849d50c17c6dc7c92ec2d4ce0ad7e5 is normal：
![_%0NWDF$I IDZ P$%VDA`%2](https://user-images.githubusercontent.com/97432411/188262068-141ac126-3ff2-4c83-af2c-0888027f3da4.png)

### Example codes for reproduce this issue (such as a github link).
```
rules:
- !SHARDING
  tables:
    t_single:
      actualDataNodes: ds1_0.t_single
    t_ssdb_tb:
      actualDataNodes: ds1_${0..1}.t_ssdb_tb_${0..1}
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
      tableStrategy:
        standard:
          shardingColumn: c_id
          shardingAlgorithmName: ts_t_ssdb_tb_inline
    t_ssdb_tb_view:
      actualDataNodes: ds1_${0..1}.t_ssdb_tb_view_${0..1}
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
      tableStrategy:
        standard:
          shardingColumn: c_id
          shardingAlgorithmName: ts_t_ssdb_tb_view_inline
    t_ssdb:
      actualDataNodes: ds1_${0..1}.t_ssdb
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
    t_ssdb_view:
      actualDataNodes: ds1_${0..1}.t_ssdb_view
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
    t_ssdb_tb1:
      actualDataNodes: ds1_${0..1}.t_ssdb_tb1_${0..1}
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
      tableStrategy:
        standard:
          shardingColumn: c_id
          shardingAlgorithmName: ts_t_ssdb_tb1_inline

  broadcastTables:
    - t_broadcast
    - t_broadcast_view
  bindingTables:
    - t_ssdb_tb, t_ssdb_tb1
    - t_ssdb_tb, t_ssdb_tb_view
  defaultTableStrategy:
    none:
  defaultDatabaseStrategy:
    none:
  shardingAlgorithms:
    ds1_database_inline:
      type: INLINE
      props:
        algorithm-expression: ds1_${id % 2}
        allow-range-query-with-inline-sharding: true
    ts_t_ssdb_tb_inline:
      type: INLINE
      props:
        algorithm-expression: t_ssdb_tb_${c_id % 2}
        allow-range-query-with-inline-sharding: true
    ts_t_ssdb_tb1_inline:
      type: INLINE
      props:
        algorithm-expression: t_ssdb_tb1_${c_id % 2}
        allow-range-query-with-inline-sharding: true
    ts_t_ssdb_tb_view_inline:
      type: INLINE
      props:
        algorithm-expression: t_ssdb_tb_view_${c_id % 2}
        allow-range-query-with-inline-sharding: true
```

**Comment by strongduanmu** [comment] 2022-09-05 02:50
@peilinqian Thank you for your feedback, this bug is caused by #19423, I will fix it in 5.2.0-release branch.

**Comment by strongduanmu** [comment] 2022-09-05 03:52
Fixed by https://github.com/apache/shardingsphere/pull/20784.

**Closed by strongduanmu** 2022-09-05 03:52 UTC
Labels: type: bug, feature: sharding

**Comment by wsm12138** [comment] 2022-09-05 06:50
8dee990098fd2cb000079ce1a933c530e8d0a704

<img width="741" alt="image" src="https://user-images.githubusercontent.com/86462784/188382272-69066c18-34b9-4d72-8d24-45683ba2c4e1.png">

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/86462784/188382653-4071af01-b652-43cc-b6ab-673487fc4f67.png">

fixed

**Comment by peilinqian** [comment] 2022-09-12 06:09
```
[INFO ] 2022-09-12 13:58:33.652 [HikariPool-7 connection adder] o.o.core.v3.ConnectionFactoryImpl - [90.90.44.175:56838/90.90.44.171:14000] Connection is established. ID: dc353984-0721-4dd2-b96b-9d1b006b2b89
[INFO ] 2022-09-12 13:58:33.655 [HikariPool-7 connection adder] o.o.core.v3.ConnectionFactoryImpl - Connect complete. ID: dc353984-0721-4dd2-b96b-9d1b006b2b89
Exception in thread "main" java.lang.IllegalArgumentException: Invalid binding table configuration in ShardingRuleConfiguration.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at org.apache.shardingsphere.sharding.rule.ShardingRule.<init>(ShardingRule.java:135)
        at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:41)
        at org.apache.shardingsphere.sharding.rule.builder.ShardingRuleBuilder.build(ShardingRuleBuilder.java:35)
        at org.apache.shardingsphere.infra.rule.builder.database.DatabaseRulesBuilder.build(DatabaseRulesBuilder.java:58)
        at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabase.create(ShardingSphereDatabase.java:86)
        at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.createGenericDatabases(ShardingSphereDatabasesFactory.java:80)
        at org.apache.shardingsphere.infra.metadata.database.ShardingSphereDatabasesFactory.create(ShardingSphereDatabasesFactory.java:68)
        at org.apache.shardingsphere.mode.metadata.MetaDataContextsFactory.create(MetaDataContextsFactory.java:68)
        at org.apache.shardingsphere.mode.manager.cluster.ClusterContextManagerBuilder.build(ClusterContextManagerBuilder.java:57)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.createContextManager(BootstrapInitializer.java:67)
        at org.apache.shardingsphere.proxy.initializer.BootstrapInitializer.init(BootstrapInitializer.java:57)
        at org.apache.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:52)
[peilq_sharding@openGauss175 peilq_olk]$
[peilq_sharding@openGauss175 peilq_olk]$ bash /usr2/peilq_all/peilq_olk/apache-shardingsphere-5.1.3-SNAPSHOT-shardingsphere-proxy-bin/bin/start.sh --version
we find java version: java8, full_version=1.8.0_342, full_path=/home/peilq_sharding/bisheng-jdk1.8.0_342//bin/java
ShardingSphere-5.1.3-SNAPSHOT
Commit ID: dirty-fd06e5551667fc54da2125e3139b9748ba95b3f4
Commit Message: add valid for alter rename view (#20791)
Branch: fd06e5551667fc54da2125e3139b9748ba95b3f4
Build time: 2022-09-09T11:49:22+0800

```

**Comment by wsm12138** [comment] 2022-09-13 02:49
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/86462784/189795929-5b70920b-51a6-4028-8141-adbcdb361947.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/86462784/189796414-34f36ee5-497b-4f2a-a117-583897ad6bbf.png">

@peilinqian  
 Fixed  in PR https://github.com/apache/shardingsphere/pull/20886.

**Comment by peilinqian** [comment] 2022-09-13 08:37
Passed

```
[peilq_sharding@openGauss175 peilq_olk]$ bash /usr2/peilq_all/peilq_olk/apache-shardingsphere-5.2.1-SNAPSHOT-shardingsphere-proxy-bin/bin/start.sh --version
we find java version: java8, full_version=1.8.0_342, full_path=/home/peilq_sharding/bisheng-jdk1.8.0_342//bin/java
ShardingSphere-5.2.1-SNAPSHOT
Commit ID: dirty-f44e5d3c09a38139dbb2e1b0548816aa572ccc3c
Commit Message: Release 5.2.0 and prepare for next development iteration (#20886)
Branch: f44e5d3c09a38139dbb2e1b0548816aa572ccc3c
Build time: 2022-09-13T11:31:41+0800
```
