### ISSUE TITLE
'Proxy project' should be compatible with the IDEA database editor and DataGrid 

### ISSUE THREAD

**Issue by hywr** [apache/shardingsphere#14740] opened 2022-01-13 09:23 UTC
In the current version (5.0.0), there are two problems when MySQL adopts the idea database editor:

1. It can't list the database without selecting the database, and report the error: [3D000][1046] No database selected.

2. When the selected database is selected, the table cannot be listed and an error is reported: [c1997] [1997] runtime exception: [unsupported table: ` tables']

I'd be happy if the bosses could revise it.

 --Translated by Baidu, original text: #14734 

Images:
![alt 未选图片时](https://pic.aaxp.cn/zxs-ks/unselected.png)
![alt 已选图片时](https://pic.aaxp.cn/zxs-ks/selected.png)

**Comment by terrymanu** [comment] 2022-01-13 15:42
Is ShardingSphere-Proxy throw exception? Or could you provide the debug level log here?

**Comment by terrymanu** [comment] 2022-01-13 15:42
Maybe need to capture MySQL packet and analyze the SQL to debug the problem.

**Comment by hywr** [comment] 2022-01-14 01:38
Here are two files, one is the packets when the database is not selected, and the other is the packets when the database is selected, as follows:

[unselected.log](https://github.com/apache/shardingsphere/files/7867029/unselected.log)

[selected.log](https://github.com/apache/shardingsphere/files/7867030/selected.log)

**Comment by CrackerSuperior** [comment] 2022-01-14 03:26
@hywr If it doesn't work, make sure to use the following configuration:
![image](https://user-images.githubusercontent.com/45088781/149446306-e759fcad-8c32-47f2-8797-a770d3e27efa.png)
![image](https://user-images.githubusercontent.com/45088781/149446468-bf4ab325-e730-408b-a17c-0abe877ad3a3.png)
![image](https://user-images.githubusercontent.com/45088781/149446397-bcf059d1-2703-4d23-84c8-d99af48696cd.png)

**Comment by hywr** [comment] 2022-01-14 10:20
> @hywr If it doesn't work, make sure to use the following configuration: ![image](https://user-images.githubusercontent.com/45088781/149446306-e759fcad-8c32-47f2-8797-a770d3e27efa.png) ![image](https://user-images.githubusercontent.com/45088781/149446468-bf4ab325-e730-408b-a17c-0abe877ad3a3.png) ![image](https://user-images.githubusercontent.com/45088781/149446397-bcf059d1-2703-4d23-84c8-d99af48696cd.png)

Thank you. It's useful

**Comment by RaigorJiang** [comment] 2022-01-16 08:55
There are instructions in the [FAQ](https://shardingsphere.apache.org/document/current/en/reference/faq/#proxy-how-to-use-a-suitable-database-tools-connecting-shardingsphere-proxy).
As the issue is resolved, I will close it.

**Closed by RaigorJiang** 2022-01-16 08:55 UTC
