### ISSUE TITLE
An error About custom sharding algorithm in 5.0.0-beta

### ISSUE THREAD

**Issue by marker-wu** [apache/shardingsphere#12491] opened 2021-09-16 10:25 UTC
An error was reported at runtime, when the generic type of PreciseShardingValue is Long
![image](https://user-images.githubusercontent.com/45256940/133595828-12c5ec53-c874-4939-abe5-cc4fe8000993.png)
When the type is changed to Integer, it can run normally
This is my table structure：
![image](https://user-images.githubusercontent.com/45256940/133596047-4c290ae8-b20e-4652-b4ca-365c08c6247b.png)

**Comment by taojintianxia** [comment] 2021-09-16 10:30
you may take a look of the [FAQ](https://shardingsphere.apache.org/document/current/en/others/faq/)

**Comment by marker-wu** [comment] 2021-09-16 10:45
![image](https://user-images.githubusercontent.com/45256940/133598769-042a7ccb-ba79-40aa-bdb1-f6d7cc846e92.png)
My field type is bigint, why do I still report this error?

**Comment by RaigorJiang** [comment] 2021-09-16 10:45
The problem is `+1`, please try `+1L`.

**Comment by marker-wu** [comment] 2021-09-16 10:47
> The problem is `+1`, please try `+1L`.

it does not work

**Comment by RaigorJiang** [comment] 2021-09-16 10:55
Let me check it.

**Comment by RaigorJiang** [comment] 2021-09-16 11:02
Hi @marker-wu 
Please check your fields type of Java entity, may not long?

**Comment by marker-wu** [comment] 2021-09-16 11:09
> Hi @marker-wu
> Please check your fields type of Java entity, may not long?

I did not create the table object in the code，I just set the routing rules in yaml
![image](https://user-images.githubusercontent.com/45256940/133601817-160d8212-a643-487e-99c4-8ddc01f6e281.png)

**Comment by RaigorJiang** [comment] 2021-09-16 11:12
> I did not create the table object in the code，I just set the routing rules in yaml

So you shoud find the entity definition and determine the type of the fields, so that you can determine the type of sharding key, rather than just define the sharding algorithm.

**Comment by marker-wu** [comment] 2021-09-16 11:15
> > I did not create the table object in the code，I just set the routing rules in yaml
> 
> So you shoud find the entity definition and determine the type of the fields, so that you can determine the type of sharding key, rather than just define the sharding algorithm.

Where is the entity defined? Is the configuration information in config-sharding.yaml?

**Comment by RaigorJiang** [comment] 2021-09-16 11:17
😀 How did you get the SQL?

**Comment by RaigorJiang** [comment] 2021-09-16 11:20
For example, the type of entity field, which affects the parameter type you set in PreparedStatement. 
This type should be consistent with the sharding key type defined by the sharding algorithm.
![image](https://user-images.githubusercontent.com/5668787/133603256-f39c355f-3d05-46c5-9bfc-0c3f57d6c475.png)

**Comment by marker-wu** [comment] 2021-09-16 11:27
I ran it in the terminal
![image](https://user-images.githubusercontent.com/45256940/133604225-bed78ca1-035a-4b67-9342-d4dbed50d82e.png)

**Comment by marker-wu** [comment] 2021-09-16 11:43
If I use sql tool (navicat) to connect to proxy, an error will be reported when the source sql is executed

**Comment by RaigorJiang** [comment] 2021-09-17 06:42
Hi @marker-wu 
I investigated this issue and I have the following information to give you feedback:
1. In the SQL parse progress, ANTLR recognizes ‘5’ as a Number type;
2. The most suitable type corresponding to ‘5’ is Integer, so it becomes Interger;
3. Although your table field type is bigint, meta data has not been used during parse progress, so it has not been converted to Long type.
4. The sharding algorithm specifies that Long is required, so a conversion exception occurs.

I think this problem needs to be corrected. Before that, you can also temporarily solve this problem by declaring the parameter as ‘Comparable’:
```java
    @Override
    public String doSharding(final Collection<String> availableTargetNames, final PreciseShardingValue<Comparable<?>> shardingValue) {
        for (String each : availableTargetNames) {
            if (each.endsWith(String.valueOf(Long.valueOf(shardingValue.getValue().toString()) % 2 + 1))) {
                return each;
            }
        }
        return null;
    }
```

**Comment by marker-wu** [comment] 2021-09-17 07:01
it worked !
3Q

**Comment by RaigorJiang** [comment] 2021-09-26 13:00
Because the question was resolved, I will close this issue.

**Closed by RaigorJiang** 2021-09-26 13:00 UTC
Labels: in: proxy, feature: sharding
