### ISSUE TITLE
postgresql parse package error

### ISSUE THREAD

**Issue by JoinWDT** [apache/shardingsphere#11453] opened 2021-07-22 09:12 UTC
### Which version of ShardingSphere did you use?
5.0.0-alpha

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Reason analyze (If you can)
1. It can be seen by capturing the packet 

![image](https://user-images.githubusercontent.com/26700541/126614788-b4c08b73-a286-4678-b11a-4142f58a1357.png)
Type OID : 0

Execute in ShardingSphere-Proxy
![image](https://user-images.githubusercontent.com/26700541/126615374-b117cd05-c990-4740-a9ea-8cdc3fcdb1d7.png)

After consulting the relevant information, I found [here](https://www.postgresql.org/docs/14/protocol-flow.html)

![image](https://user-images.githubusercontent.com/26700541/126615559-9a7a29cc-89ff-4603-8d9e-86d04e82ba79.png)

How do I deal with this situation?

### Example codes for reproduce this issue (such as a github link).
I use ShardingSphere-Proxy in [redmine](https://github.com/redmine/redmine)

**Comment by menghaoranss** [comment] 2021-07-23 03:37
The version 5.0.0-beta has better support for PG, could you try with the latest version again?

**Comment by JoinWDT** [comment] 2021-07-23 03:47
thank you for your reply
I checked on the latest marst branch,And no further processing
When typeOID is equal to 0, 
GetTextParameters in [PostgreSQLComBindPacket](https://github.com/apache/shardingsphere/blob/master/shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/binary/bind/PostgreSQLComBindPacket.java)
Will enter POSTGRESQL_TYPE_UNSPECIFIED,
![image](https://user-images.githubusercontent.com/26700541/126735250-363ef052-209b-4cfe-8149-ec1fe7385b43.png)

The result is still the same

**Comment by TeslaCN** [comment] 2021-09-23 02:50
Hi @JoinWDT 
Sorry for the delay.
I wrote some code, but I could not reproduce this problem in master branch. The query worked.
```
            try (Statement statement = connection.createStatement()) {
                statement.execute("create table if not exists t_b (id bigint primary key, a boolean not null, b boolean not null)");
            }
            try (PreparedStatement preparedStatement = connection.prepareStatement("insert into t_b values (?, ?, ?)")) {
                preparedStatement.setLong(1, System.nanoTime());
                preparedStatement.setBoolean(2, true);
                preparedStatement.setBoolean(3, false);
                preparedStatement.addBatch();
                preparedStatement.setLong(1, System.nanoTime());
                preparedStatement.setBoolean(2, true);
                preparedStatement.setBoolean(3, false);
                preparedStatement.addBatch();
                preparedStatement.executeBatch();
            }
            try (PreparedStatement preparedStatement = connection.prepareStatement("select * from t_b where a = ? and b = ? ")) {
                preparedStatement.getParameterMetaData();
                preparedStatement.setObject(1, "true", Types.OTHER);
                preparedStatement.setObject(2, "false", Types.OTHER);
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    printResultSet(resultSet);
                }
            }
```

![image](https://user-images.githubusercontent.com/20503072/134447367-63601536-82cf-42c4-824d-e50231db05e5.png)

![image](https://user-images.githubusercontent.com/20503072/134447383-84401457-863a-4691-9f72-2f70077ee9b0.png)

And I tried revert #10691 in master branch and the following error occurred.
```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 27
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at icu.wwj.hello.jdbc.BooleanType.main(BooleanType.java:37)
```

I'm not familiar with Ruby. Could you provide more info about this issue?

**Comment by JoinWDT** [comment] 2021-09-23 03:06
@TeslaCN Thank you very much for your reply.
In [PostgreSQLTypeUnspecifiedSQLParameter](https://github.com/apache/shardingsphere/blob/master/shardingsphere-db-protocol/shardingsphere-db-protocol-postgresql/src/main/java/org/apache/shardingsphere/db/protocol/postgresql/packet/command/query/binary/bind/PostgreSQLTypeUnspecifiedSQLParameter.java), the default is to treat it as a string. When inserting data, if it is other data types, such as time, will it fail to insert?

**Comment by TeslaCN** [comment] 2021-09-23 03:20
Hi @JoinWDT 
Maybe your question is related to this issue https://github.com/apache/shardingsphere/issues/10646.

**Comment by TeslaCN** [comment] 2021-09-29 08:53
Hi @JoinWDT 
I think this issue has been done. I'm closing this.

**Closed by TeslaCN** 2021-09-29 08:53 UTC
Labels: in: proxy, db: PostgreSQL, status: need more info
