### ISSUE TITLE
Add more unit test for YamlSQLParserRuleConfigurationSwapper

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#21020] opened 2022-09-16 09:43 UTC
Hi community,

This issue is for https://github.com/apache/shardingsphere/issues/20305.

### Aim
Add more unit tests for `YamlSQLParserRuleConfigurationSwapper` to test its public functions to improve unit test coverage.

Unit test coverage can be viewed at: https://app.codecov.io/gh/apache/shardingsphere

### Basic Qualifications
Java
Maven
Junit

**Comment by abhinav-koppula** [comment] 2022-10-01 13:52
@strongduanmu / @FlyingZC - Is this issue duplicate of #20400 ?

**Comment by strongduanmu** [comment] 2022-10-02 06:58
Yes, this issue is duplicated with #20400, I will close this issue.

**Closed by strongduanmu** 2022-10-02 06:58 UTC
Labels: in: test, hacktoberfest
