### ISSUE TITLE
Why same query sql is executed by two times?

### ISSUE THREAD

**Issue by boyjoy1127** [apache/shardingsphere#22443] opened 2022-11-26 11:33 UTC
## Why same query sql is executed by two times?

What is the differentce betwen assertExecuteQuery() and assertExecute() in GeneralDQLIT.

Same query sql is executed by assertExecuteQuery() and assertExecute() two times.
<img width="1285" alt="WechatIMG505" src="https://user-images.githubusercontent.com/101028753/204086557-861c6da3-dc41-4e85-b7c1-2233932b02bf.png">

<img width="1028" alt="WechatIMG507" src="https://user-images.githubusercontent.com/101028753/204086562-21f77f35-37e2-4089-bd4b-b13016fa9616.png">

**Comment by strongduanmu** [comment] 2022-11-26 11:36
This is to cover more jdbc interfaces, and both execute and executeQuery can execute select statements.

**Comment by strongduanmu** [comment] 2022-11-28 02:58
Since this is not a bug, I will close this issue.

**Closed by strongduanmu** 2022-11-28 02:58 UTC
Labels: type: question
