### ISSUE TITLE
Is sharding-jdbc supported postgresql array?Can I customize and implents it? 

### ISSUE THREAD

**Issue by zzujustme** [apache/shardingsphere#3954] opened 2020-01-13 08:17 UTC
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Comment by terrymanu** [comment] 2020-02-13 04:57
Yes, welcome try to do it

**Comment by SteNicholas** [comment] 2020-02-28 10:14
@terrymanu I will try it.

**Comment by sandynz** [comment] 2020-07-28 05:30
Hi, I'd like try to solve it.

**Comment by tuohai666** [comment] 2020-07-28 05:43
For Sharding-JDBC, it supports array column.
For Sharding-Proxy, it will be resolved via https://github.com/apache/shardingsphere/issues/6408 .

**Comment by sandynz** [comment] 2020-07-28 15:23
> 
> 
> For Sharding-JDBC, @sandynz , can you reproduce this problem?
> For Sharding-Proxy, it will be resolved via #6408 .

Reproduced.

Verified with ShardingSphere 5.0.0-RC1-SNAPSHOT , revision: cf3b2eda .
DataSource is created via: YamlShardingSphereDataSourceFactory.createDataSource(getResourceAsFile("META-INF/sharding-tables-pg-jdbc.yaml")) .
Exception thrown when querying, logs:
```
[main] INFO ShardingSphere-SQL - Actual SQL: ds ::: select * from array_tc_1 where id = ? ::: [3]
Exception in thread "main" java.sql.SQLFeatureNotSupportedException: getArray
	at org.apache.shardingsphere.driver.jdbc.unsupported.AbstractUnsupportedOperationResultSet.getArray(AbstractUnsupportedOperationResultSet.java:191)
	at test.shardingsphere.sharding.pg.array.PgArrayTcDao.query(PgArrayTcDao.java:46)
	at test.shardingsphere.sharding.pg.array.ShardingPgArrayJdbcTest.main(ShardingPgArrayJdbcTest.java:17)
```
Since ShardingSphereResultSet has't implement java.sql.ResultSet.getArray(columnLabel) method:
```
    public final Array getArray(final String columnLabel) throws SQLException {
        throw new SQLFeatureNotSupportedException("getArray");
    }
```

**Closed** 2020-07-30 09:13 UTC
Labels: PostgreSQL, bug, jdbc

**Comment by hebing0625** [comment] 2021-01-25 09:58
hi,  

There still has a issue when I try to deal with connect:

`Connection conn = shardingDataSource.getConnection();`
`conn.createArrayOf("int8", new Long[]{1L, 2L, 3L});`

It will throw SQLFeatureNotSupportedException. 

I trace the codes and find such snippets in SQLFeatureNotSupportedException.java:

`   @Override
`   public final Array createArrayOf(final String typeName, final Object[] elements) throws SQLException {
`        throw new SQLFeatureNotSupportedException("createArrayOf");
`   }

Can you help me how to solve this？

**Comment by sandynz** [comment] 2021-01-27 15:37
> 
> 
> There still has a issue when I try to create array with connection as below:
> 
> `Connection conn = shardingDataSource.getConnection();`
> `conn.createArrayOf("int8", new Long[]{1L, 2L, 3L});`
> 
> A SQLFeatureNotSupportedException will be thrown.
> 
> I trace the codes and find such snippets in SQLFeatureNotSupportedException.java:
> 
> ` @Override` public final Array createArrayOf(final String typeName, final Object[] elements) throws SQLException {
> ` throw new SQLFeatureNotSupportedException("createArrayOf");` }

Hi @hebing0625 , you're right, `conn.createArrayOf` is not supported for now, and it's not easy to support it.
There is a workaround, use `java.sql.PreparedStatement.setObject`, e.g. `statement.setObject(1, new long[]{1, 2, 3})`.

The supported primitive array type:
```
long[]
int[]
short[]
byte[]
double[]
float[]
boolean[]
String[]
```
More details refrence PG JDBC driver: `PgPreparedStatement.setObject` and `PrimitiveArraySupport.isSupportedPrimitiveArray`.
