### ISSUE TITLE
The jdbcUrl property doesn't work when using DruidDatasource.

### ISSUE THREAD

**Issue by zewade** [apache/shardingsphere#23050] opened 2022-12-23 03:28 UTC
### Which version of ShardingSphere did you use?
5.3.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
When I use DruidDatasource, shardingjdbc can be loaded successfully.

### Actual behavior
Throw an Exception, Message is 'url not set'.

### Reason analyze (If you can)
When I use 'jdbcUrl' ,it doesn't work,but change to 'url' can work.  
```
dataSources:
  ds-0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://xxxx:xxx/xxxxx.   ##url: jdbc:mysql://xxxx:xxx/xxxxx
    username: root
    password:
```

**Comment by linghengqian** [comment] 2022-12-23 05:52
- Duplicate of https://github.com/apache/shardingsphere/issues/17440 . This is expected behavior.

**Closed** 2022-12-26 02:03 UTC
Labels: type: duplicate
