### ISSUE TITLE
Druid connectProperties reflect error

### ISSUE THREAD

**Issue by dkisser** [apache/shardingsphere#21937] opened 2022-11-03 11:39 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
shardingsphere-jdbc-core-spring-boot-starter 5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
when use Druid to encript password,I use connec-properties,there are two method both named "setConnectProperties"
\
![image](https://user-images.githubusercontent.com/24600271/199710434-73f6d186-cc3c-47e1-83c1-ae742a5e3151.png)
![image](https://user-images.githubusercontent.com/24600271/199711412-66adb988-d70e-4b6d-abd0-84ca59232853.png)

so when yaml use string to config connecProperties,it will throw "java.lang.String can't cast to java.util.Map",i think setter method should check fieldName and type，not only fieldName, in `org.apache.shardingsphere.infra.datasource.pool.creator.DataSourceReflection`
![image](https://user-images.githubusercontent.com/24600271/199711183-9b66cf9b-cc2a-46b8-9c9e-5eec2212547e.png)

### Reason analyze (If you can)
org.apache.shardingsphere.infra.datasource.pool.creator.DataSourceReflection

**Comment by dkisser** [comment] 2022-11-03 11:42
There is the same question in the latest version .

**Comment by linghengqian** [comment] 2022-11-03 12:36
- Your issue is essentially the same as https://github.com/apache/shardingsphere/issues/21211#issuecomment-1268667396.  If you have an idea, give it?

**Comment by dkisser** [comment] 2022-11-08 03:27
> * Your issue is essentially the same as [v5.2, If a druid datasource has some filters, then create a ShardingSphereDataSource will occur exception #21211 (comment)](https://github.com/apache/shardingsphere/issues/21211#issuecomment-1268667396).  If you have a PR, give it?

i think "whilte list" mybe a temporary way , add Druid filter in it. But the best way, shardingsphere should provide a extension way that user can deal with it in a custom way.

**Comment by RaigorJiang** [comment] 2023-01-29 03:35
Closed for duplicate of #21211.

**Closed by RaigorJiang** 2023-01-29 03:35 UTC
