### ISSUE TITLE
The 'show tables' command cannot see the newly created or deleted tables in actual resource.

### ISSUE THREAD

**Issue by zhouyouwei-0127** [apache/shardingsphere#16180] opened 2022-03-18 07:24 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
the newly added table in the actual datasource should be seen in the proxy
### Actual behavior
can't see the newly created or deleted tables if don't restart the proxy
### Reason analyze (If you can)
the proxy cached the table structure and not update when the table structure changed in actual datasource
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
config
  server.yaml:
![image](https://user-images.githubusercontent.com/64695476/158953935-7dd5b892-9666-4996-b942-db38902331cc.png)
 readwrite-splitting.yaml:
![image](https://user-images.githubusercontent.com/64695476/158954109-536885df-4b8c-4bbb-b52d-f211310571d9.png)

table strcture in actual datasource:
![image](https://user-images.githubusercontent.com/64695476/158954330-de7d0ab1-3efa-455e-9fa3-250c20b7d6ca.png)
table strcture in proxy:
![image](https://user-images.githubusercontent.com/64695476/158954382-80557e25-0f72-404b-81e9-70303277c57f.png)

when I create a table in the actual datasource like this
![image](https://user-images.githubusercontent.com/64695476/158954705-b6fd5b24-2bec-41d6-b9f5-e7a81819b1fe.png)

excute 'show tables' in proxy again,I can't see the change of table structure, but Ican query the data of the new table：
![image](https://user-images.githubusercontent.com/64695476/158955483-0ede5f41-8aae-412a-84ed-2e8737f9a636.png)

**Comment by zjcnb** [comment] 2022-03-18 07:36
@zhouyouwei-0127 Thank for your feedback, i will check it.

**Comment by RaigorJiang** [comment] 2022-03-21 02:44
Hi @zhouyouwei-0127 @zjcnb 
If you add a new table directly on the underlying database, or modify the table structure, it will not trigger the metadata refresh in Proxy. This is by design and should not be considered a bug.
It is recommended to execute DDL statements through Proxy.

In addition, there is some syntax in DistSQL RAL, which can help users to actively trigger metadata refresh in this case:
- `refresh table metadata`
- `show table metadata tableName`

**Comment by zjcnb** [comment] 2022-03-21 02:49
> Hi @zhouyouwei-0127 @zjcnb If you add a new table directly on the underlying database, or modify the table structure, it will not trigger the metadata refresh in Proxy. This is by design and should not be considered a bug. It is recommended to execute DDL statements through Proxy.
> 
> In addition, there is some syntax in DistSQL RAL, which can help users to actively trigger metadata refresh in this case:
> 
> * `refresh table metadata`
> * `show table metadata tableName`
> 
> https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/distsql/syntax/ral/

@RaigorJiang  Thank you for your answer, i see.

**Comment by zhouyouwei-0127** [comment] 2022-03-25 06:52
Thank you for you anwser @zjcnb @RaigorJiang , but I think this is a deficiency. Will it be repaired later?

**Comment by RaigorJiang** [comment] 2022-03-25 07:11
> Thank you for you anwser @zjcnb @RaigorJiang , but I think this is a deficiency. Will it be repaired later?

It's hard, as you can imagine, in the case of so many databases or tables, scanning once is very slow. This action should not be repeated for no reason.

**Comment by zhouyouwei-0127** [comment] 2022-03-28 01:27
> > Thank you for you anwser @zjcnb @RaigorJiang , but I think this is a deficiency. Will it be repaired later?
> 
> It's hard, as you can imagine, in the case of so many databases or tables, scanning once is very slow. This action should not be repeated for no reason.

OK. I see. Thank you for your answer

**Comment by RaigorJiang** [comment] 2022-03-28 06:21
@zhouyouwei-0127  You are welcome, so can we close this issue?

**Closed** 2022-04-07 13:55 UTC
Labels: type: question
