### ISSUE TITLE
Support parsing SQL Server INSERT INTO sql

### ISSUE THREAD

**Issue by FlyingZC** [apache/shardingsphere#29195] opened 2023-11-24 07:10 UTC
# Background
Hi community.
This issue is for #29149.

The ShardingSphere SQL parser engine helps users to parse SQL to create the AST (Abstract Syntax Tree) and visit the AST to get SQLStatement (Java Object). Currently, we are planning to enhance the support for `SQL Server` SQL parsing in ShardingSphere.

More details:
https://shardingsphere.apache.org/document/current/en/reference/sharding/parse/

# Task
This issue is to support more `SQL Server` sql parsing, as follows:
```sql
INSERT INTO #t VALUES (99)
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16)

```sql
INSERT INTO ##test
VALUES (1, 1)
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16)

```sql
SELECT * FROM ##test
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16)

```sql
SELECT * FROM ##test
```
[link](https://learn.microsoft.com/zh-cn/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver16)

```sql
SELECT TOP 100 id=CAST(_id as VARBINARY(1000))
FROM OPENROWSET('CosmosDB',
                'Your-account
```
[link](https://learn.microsoft.com/zh-cn/azure/cosmos-db/analytical-store-introduction)

# Process
1. First confirm that this is a correct `SQL Server` sql syntax, if not please leave a message under the issue and ignore it;
2. Compare SQL definitions in Official SQL Doc and ShardingSphere SQL Doc;
3. If there is any difference in ShardingSphere SQL Doc, please correct them by referring to the Official SQL Doc;
4. Run mvn install the current_file_module;
5. Check whether there are any exceptions. If indeed, please fix them. (Especially xxxVisitor.class);
6. Add new corresponding SQL case in SQL Cases and expected parsed result in Expected Statement XML;
7. Run SQLParserParameterizedTest to make sure no exceptions.

# Relevant Skills
1. Master JAVA language
2. Have a basic understanding of Antlr `g4` file
3. Be familiar with `SQL Server` SQLs

**Comment by professorabhay** [comment] 2023-11-24 08:26
Hey @FlyingZC ! Seems familiar to me.
I'm working on it.

**Comment by strongduanmu** [comment] 2023-11-24 09:12
@professorabhay Welcome, I will assign it to you.

**Comment by professorabhay** [comment] 2023-11-25 15:50
Hey @strongduanmu, I need some help. Please tell me some more details about implementation and the details about dir .

**Comment by strongduanmu** [comment] 2023-11-26 04:24
Hi @professorabhay, you can refer this pr - https://github.com/apache/shardingsphere/pull/29138, it's a good example.

**Comment by Eeshu-Yadav** [comment] 2023-12-28 19:30
Hey @strongduanmu ,plzz assign it to me.

**Comment by strongduanmu** [comment] 2023-12-29 02:09
@Eeshu-Yadav Assigned.

**Comment by strongduanmu** [comment] 2024-01-29 02:29
Hi @Eeshu-Yadav, does this issue has any progress?

**Comment by yydeng626** [comment] 2024-01-30 06:44
@strongduanmu Please assign to me , I can do it

**Comment by strongduanmu** [comment] 2024-01-30 06:50
@yydeng626 Good job, I just assign this issue to you.

**Comment by yydeng626** [comment] 2024-02-02 07:13
@strongduanmu The issue is merged , please help to close it

**Comment by strongduanmu** [comment] 2024-02-02 08:26
Thank you for your remind @yydeng626.

**Closed by strongduanmu** 2024-02-02 08:26 UTC
Labels: type: enhancement, in: SQL parse, good first issue, db: SQLServer
