### ISSUE TITLE
no result of select * from shardingsphere.sharding_table_statistics

### ISSUE THREAD

**Issue by hhw3KevinHou** [apache/shardingsphere#29403] opened 2023-12-14 10:08 UTC
## Bug Report
There is no result after execute select * from shardingsphere.sharding_table_statistics  using Navicat or SQLyog or Mysql client.

### Which version of ShardingSphere did you use?
5.4.1  Standalone mode
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
database info
### Actual behavior
no result
 
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![image](https://github.com/apache/shardingsphere/assets/14155363/580908a3-5339-4fea-bb8e-9989f80e8898)

 
Got error when double click the shardingsphere node:
![image](https://github.com/apache/shardingsphere/assets/14155363/6d26934c-4168-4404-87da-7ed0ffcad812)

same result when using Mysql client:
mysql> select * from sharding_table_statistics;
Empty set (0.84 sec)

**Comment by hhw3KevinHou** [comment] 2023-12-15 09:45
Reason is that I only configed a encrypt db, no sharding db.

**Comment by kanha-gupta** [comment] 2023-12-15 09:54
> Reason is that I only configed a encrypt db, no sharding db.

Does it work now ?

**Comment by strongduanmu** [comment] 2023-12-21 06:39
> Reason is that I only configed a encrypt db, no sharding db.

Yes, this table is for sharding feature.

**Comment by strongduanmu** [comment] 2023-12-21 06:40
Since this is not a bug, I will close this issue.

**Closed by strongduanmu** 2023-12-21 06:40 UTC
