### ISSUE TITLE
some datasource pool connect resolve PropertyKeys is user，but standardProperties just compare with “username”，it will throw null Point Exception

### ISSUE THREAD

**Issue by 470582416** [apache/shardingsphere#18901] opened 2022-07-06 10:19 UTC
<img width="975" alt="图片" src="https://user-images.githubusercontent.com/44893749/177528495-f2f79409-0476-479d-9727-92675820d330.png">
<img width="1534" alt="图片" src="https://user-images.githubusercontent.com/44893749/177528588-63035ee7-6d06-4ab9-bca8-2881097c7c8a.png">

**Comment by TeslaCN** [comment] 2022-07-06 11:38
For English only.

**Comment by linghengqian** [comment] 2022-07-07 05:13
I can't think of a JDBC pool that would use `user` as the username. Wouldn't it be better to implement the metadata SPI corresponding to the JDBC pool in this case to convert `user` to `username`?

**Comment by terrymanu** [comment] 2022-07-25 05:54
What is your version?

**Comment by linghengqian** [comment] 2022-07-30 07:55
I feel like this issue is a duplicate of https://github.com/apache/shardingsphere/issues/19607.

**Comment by linghengqian** [comment] 2022-10-10 07:37
- I think this issue can be closed because C3P0's metadata is already in the master branch.

**Closed** 2022-12-27 03:04 UTC
Labels: status: need more info
