### ISSUE TITLE
queryWithCipherColumn set true,but not get this plainColumn values

### ISSUE THREAD

**Issue by zhujy5** [apache/shardingsphere#13235] opened 2021-10-23 05:17 UTC
Logic SQL: select user_id,user_name,password,password_assisted from t_user where user_name=?
Actual SQL: master ::: select user_id,user_name,password_encrypt,password_assisted from t_user where user_name=? ::: [user19]
but the result is :
[
    {
        "userId": 19,
        "userName": "user19",
        "password": null,
        "passwordEncrypt": null,
        "passwordAssisted": null
    }
]

my config is 
          t_user:
            columns:
              # 逻辑列,就是写SQL里面的列，因为实体类的名字和数据库的加密列一致，所以这里都是name
              password:
                # 原文列
                plainColumn: password
                # 密文列，用来存储密文数据
                cipherColumn: password_encrypt
                # 加密器名字
                encryptor: encryptor_aes
      # 数据脱敏规则配置---end
    props:
      # 打印SQL
      sql:
        show: true
      check:
        table:
          metadata: true
          # 是否在启动时检查分表元数据一致性
          enabled: true
      query:
        with:
          cipher:
            column: true

please confirm what happened fir this result?
"password": null,   not get actual value

**Comment by strongduanmu** [comment] 2021-11-04 04:58
Since this problem has not reproduced in the master branch, I will close this issue first. If you encounter other problems, please send feedback on the issue. Thank you.

**Closed by strongduanmu** 2021-11-04 04:58 UTC
Labels: feature: encrypt, status: need more info
