### ISSUE TITLE
The new column is not displayed in proxy

### ISSUE THREAD

**Issue by cqiwencom** [apache/shardingsphere#11755] opened 2021-08-11 02:08 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ShardingSphere-Proxy 5.0.0-beta

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Before this operation, I have directly added the ntime column to the T2 table on the backend MySQL server.

After ensuring that the operation is completed, I log in through proxy to query and find that the new column is not displayed:

[root@DBR920 ~]# mysql -uroot -proot -P3307 -h127.0.0.1
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 32
Server version: 5.7.33-log-ShardingSphere-Proxy 5.0.0-beta

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> select * from testdb.t2;
+----+--------+
| id | name   |
+----+--------+
|  1 | mm     |
|  2 | gg     |
|  3 | niuniu |
|  4 | hhhh   |
+----+--------+
4 rows in set (0.01 sec)

MySQL [(none)]> use testdb
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [testdb]> select @@port;
+--------+
| @@port |
+--------+
|   3318 |
+--------+
1 row in set (0.01 sec)

MySQL [testdb]> exit
Bye

Then I directly connect to the back-end MySQL server, whose port is the back-end server port 3318 just connected by proxy：

[root@DBR920 ~]# mysql -uroot -proot -P3318 -h127.0.0.1
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 158
Server version: 5.7.33-log MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> select * from testdb.t2;
+----+--------+---------------------+
| id | name   | ntime               |
+----+--------+---------------------+
|  1 | mm     | 2021-08-11 09:36:37 |
|  2 | gg     | 2021-08-11 09:36:37 |
|  3 | niuniu | 2021-08-11 09:36:37 |
|  4 | hhhh   | 2021-08-11 09:36:37 |
+----+--------+---------------------+
4 rows in set (0.00 sec)

MySQL [(none)]>

This indicates that the ntime column exists on the back-end server. But why can't proxy query this column?

**Comment by strongduanmu** [comment] 2021-08-11 03:01
Hi @cqiwencom, you need to use proxy to add column to ensure that metadata can be refreshed normally.

**Comment by cqiwencom** [comment] 2021-08-11 03:20
How can I use proxy to add columns to a table? When I use the following command in proxy, an error occurs：

MySQL [testdb]> alter table t1 add column dtime timestamp NOT NULL DEFAULT NOW();
ERROR 1235 (42000): This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'

**Comment by cqiwencom** [comment] 2021-08-11 03:23
> Hi @cqiwencom, you need to use proxy to add column to ensure that metadata can be refreshed normally.

My proxy version is ShardingSphere-Proxy 5.0.0-beta.

**Comment by strongduanmu** [comment] 2021-08-11 03:25
@cqiwencom Thank you for your feedback, we will Investigate this problem.

**Comment by cqiwencom** [comment] 2021-08-11 03:30
> @cqiwencom Thank you for your feedback, we will Investigate this problem.

Thanks. I hope this problem can be solved as soon as possible.

**Comment by tristaZero** [comment] 2021-08-15 09:40
Hi thanks @cqiwencom 
guys, do we have any updates?

**Comment by TeslaCN** [comment] 2021-12-16 07:02
Hi @cqiwencom 
Any progress here?

**Comment by TeslaCN** [comment] 2021-12-16 07:05
I think the root cause of this issue is unsupported SQL syntax, I'm labeling this issue with `SQL parse`

**Comment by menghaoranss** [comment] 2021-12-27 11:06
@cqiwencom this issue has been fixed by #13702

**Closed by menghaoranss** 2021-12-27 11:06 UTC
Labels: type: enhancement, in: SQL parse, db: MySQL
