### ISSUE TITLE
Provider PostgreSQLDialectExceptionMapper could not be instantiated

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/shardingsphere#22544] opened 2022-11-30 13:02 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.2.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

The table can be dropped normally

### Actual behavior

> 
           java.util.ServiceConfigurationError: org.apache.shardingsphere.dialect.mapper.SQLDialectExceptionMapper: Provider 
     org.apache.shardingsphere.dialect.postgresql.mapper.PostgreSQLDialectExceptionMapper could not be instantiated
      
	      at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	      at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	      at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	      at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	      at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	      at org.apache.shardingsphere.infra.util.spi.ShardingSphereServiceLoader.load(ShardingSphereServiceLoader.java:53)
	      at org.apache.shardingsphere.infra.util.spi.ShardingSphereServiceLoader.register(ShardingSphereServiceLoader.java:47)
	      at org.apache.shardingsphere.dialect.mapper.SQLDialectExceptionMapperFactory.<clinit>(SQLDialectExceptionMapperFactory.java:34)
	      at org.apache.shardingsphere.dialect.SQLExceptionTransformEngine.toSQLException(SQLExceptionTransformEngine.java:57)
	      at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.execute(ShardingSpherePreparedStatement.java:409)
	      at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	      at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	      at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	      at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	      at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	      at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	      at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:209)
	      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	      at java.lang.reflect.Method.invoke(Method.java:498)
	      at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	      at com.sun.proxy.$Proxy71.delete(Unknown Source)
	      at org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:304)
	      at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:69)
	      at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	      at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	      at com.sun.proxy.$Proxy72.dropTable(Unknown Source)
	      at com.aolifu.shardingsphere.UserTest.dropTableTest(UserTest.java:39)
	      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	      at java.lang.reflect.Method.invoke(Method.java:498)
	      at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	      at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	      at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	      at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	      at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	      at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	      at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	      at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	      at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	      at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	      at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	      at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	      at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	      at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	      at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	      at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	      at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	      at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	      at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	      at java.util.ArrayList.forEach(ArrayList.java:1257)
	      at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	      at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	      at java.util.ArrayList.forEach(ArrayList.java:1257)
	      at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	      at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	      at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	      at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	      at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	      at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	      at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	      at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	      at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	      at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	      at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	      at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	      at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	      at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	      at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	      at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
      Caused by: java.lang.NoClassDefFoundError: org/postgresql/util/PSQLException
	      at java.lang.Class.getDeclaredConstructors0(Native Method)
	      at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	      at java.lang.Class.getConstructor0(Class.java:3075)
	      at java.lang.Class.newInstance(Class.java:412)
	      at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	      ... 96 more
      Caused by: java.lang.ClassNotFoundException: org.postgresql.util.PSQLException
	      at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	      ... 101 more

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

sql: drop table user_1

### Example codes for reproduce this issue (such as a github link).

[Unit Test](https://github.com/Oliverwqcwrw/aolifu/blob/master/shardingsphere/src/test/java/com/aolifu/shardingsphere/UserTest.java)

**Comment by strongduanmu** [comment] 2022-12-01 00:27
@Oliverwqcwrw Thank you for your feedback, we will check this issue.

**Comment by iamhucong** [comment] 2023-03-03 13:16
@strongduanmu @TeslaCN 
Hi, this error look like due to PostgreSQLDialectExceptionMapper has a dependency on the PostgreSQL package.
Whether it makes sense to replace PSQLException with SQLException?

**Comment by TeslaCN** [comment] 2023-03-07 01:40
> @strongduanmu @TeslaCN Hi, this error look like due to PostgreSQLDialectExceptionMapper has a dependency on the PostgreSQL package. Whether it makes sense to replace PSQLException with SQLException?

ShardingSphere-Proxy PostgreSQL frontend requires severity, SQLState, message and other optional fields in PSQLException. Is it possible to replace PSQLException with SQLException?

**Comment by iamhucong** [comment] 2023-03-17 02:48
> > @strongduanmu @TeslaCN Hi, this error look like due to PostgreSQLDialectExceptionMapper has a dependency on the PostgreSQL package. Whether it makes sense to replace PSQLException with SQLException?
> 
> ShardingSphere-Proxy PostgreSQL frontend requires severity, SQLState, message and other optional fields in PSQLException. Is it possible to replace PSQLException with SQLException?

@TeslaCN Hi, How about catch ServiceConfigurationError? like this commit.
Or there is another way, to deal with it like spring @ConditionalOnClass.
Please continue to guide me, thank you.

**Comment by TeslaCN** [comment] 2023-03-22 10:59
> > > @strongduanmu @TeslaCN Hi, this error look like due to PostgreSQLDialectExceptionMapper has a dependency on the PostgreSQL package. Whether it makes sense to replace PSQLException with SQLException?
> > 
> > 
> > ShardingSphere-Proxy PostgreSQL frontend requires severity, SQLState, message and other optional fields in PSQLException. Is it possible to replace PSQLException with SQLException?
> 
> @TeslaCN Hi, How about catch ServiceConfigurationError? like this commit. Or there is another way, to deal with it like spring @ConditionalOnClass. Please continue to guide me, thank you.

Actually, I wonder why ClassNotFoundException occurred without invoking `convert` method. I'm going to do some tests about this.

**Comment by TeslaCN** [comment] 2023-04-07 02:46
I've confirmed this issue.

I wrote a test. Exclude PostgreSQL JDBC Driver from classpath.
```java
import org.apache.shardingsphere.dialect.SQLExceptionTransformEngine;
import org.apache.shardingsphere.dialect.postgresql.exception.authority.InvalidPasswordException;
import org.junit.jupiter.api.Test;

class SQLExceptionTransformEngineTest {
    
    @Test
    void assertMySQLToSQLException() {
        SQLExceptionTransformEngine.toSQLException(new InvalidPasswordException("user"), "MySQL");
    }
}
```

```
java.util.ServiceConfigurationError: org.apache.shardingsphere.dialect.mapper.SQLDialectExceptionMapper: org.apache.shardingsphere.dialect.postgresql.mapper.PostgreSQLDialectExceptionMapper Unable to get public no-arg constructor

	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.apache.shardingsphere.infra.util.spi.ShardingSphereServiceLoader.load(ShardingSphereServiceLoader.java:58)
	at org.apache.shardingsphere.infra.util.spi.ShardingSphereServiceLoader.<init>(ShardingSphereServiceLoader.java:48)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.apache.shardingsphere.infra.util.spi.ShardingSphereServiceLoader.getServiceInstances(ShardingSphereServiceLoader.java:75)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.findService(TypedSPILoader.java:72)
	at org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPILoader.findService(TypedSPILoader.java:56)
	at org.apache.shardingsphere.dialect.SQLExceptionTransformEngine.toSQLException(SQLExceptionTransformEngine.java:57)
	at org.apache.shardingsphere.proxy.SQLExceptionTransformEngineTest.assertMySQLToSQLException(SQLExceptionTransformEngineTest.java:28)

Omit junit stacks...

Caused by: java.lang.NoClassDefFoundError: org/postgresql/util/PSQLException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	... 82 more
Caused by: java.lang.ClassNotFoundException: org.postgresql.util.PSQLException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 90 more
```

I changed the convert method to the following:
```java
public final class PostgreSQLDialectExceptionMapper implements SQLDialectExceptionMapper {
    
    @Override
    public SQLException convert(final SQLDialectException sqlDialectException) {
        PSQLException throwables = new PSQLException(sqlDialectException.getMessage(), PSQLState.UNEXPECTED_ERROR);
        return throwables;
//        return null;
    }
// ClassNotFoundException occurred in test.
```


```java
public final class PostgreSQLDialectExceptionMapper implements SQLDialectExceptionMapper {
    
    @Override
    public SQLException convert(final SQLDialectException sqlDialectException) {
        PSQLException throwables = new PSQLException(sqlDialectException.getMessage(), PSQLState.UNEXPECTED_ERROR);
//        return throwables;
        return null;
    }
// No error occurred in test.
```

**So this issue is caused by returning an instance of a class not in classpath.**

Adding `-Xverify:none` or `-noverify` could avoid `ClassNotFoundException`, but options `-Xverify:none` and `-noverify` were deprecated in JDK 13 and will likely be removed in a future release.

**Comment by TeslaCN** [comment] 2023-04-07 03:33
Temporary solution is introducing PostgreSQL JDBC Driver to avoid `ClassNotFoundException`.

**Comment by iamhucong** [comment] 2023-04-08 10:14
> Temporary solution is introducing PostgreSQL JDBC Driver to avoid `ClassNotFoundException`.

@TeslaCN What is the formal solution? If needed, perhaps I could offer assistance?

**Comment by TeslaCN** [comment] 2023-04-10 01:49
> > Temporary solution is introducing PostgreSQL JDBC Driver to avoid `ClassNotFoundException`.
> 
> @TeslaCN What is the formal solution? If needed, perhaps I could offer assistance?

Hi @iamhucong 
I think we could create our own `PostgreSQLException` extends SQLException and replace PSQLException with it. Would you like to submit a PR?

1. Create a `PostgreSQLException` extends SQLException.
2. Handle `PostgreSQLException` in `org.apache.shardingsphere.proxy.frontend.postgresql.err.PostgreSQLErrPacketFactory`.

**Comment by iamhucong** [comment] 2023-04-10 03:34
> > > Temporary solution is introducing PostgreSQL JDBC Driver to avoid `ClassNotFoundException`.
> > 
> > 
> > @TeslaCN What is the formal solution? If needed, perhaps I could offer assistance?
> 
> Hi @iamhucong I think we could create our own `PostgreSQLException` extends SQLException and replace PSQLException with it. Would you like to submit a PR?
> 
> 1. Create a `PostgreSQLException` extends SQLException.
> 2. Handle `PostgreSQLException` in `org.apache.shardingsphere.proxy.frontend.postgresql.err.PostgreSQLErrPacketFactory`.

@TeslaCN Of course, please assign it to me.

**Comment by iamhucong** [comment] 2023-04-11 04:08
@TeslaCN Hi, I have already submitted the pull request. Could you please review it when you have time and provide any suggestions you may have?

**Closed** 2023-04-12 06:07 UTC
Labels: type: bug, status: volunteer wanted, in: JDBC, good amateur issue
