### ISSUE TITLE
java.lang.Boolean cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by iamzxj** [apache/shardingsphere#6886] opened 2020-08-17 02:01 UTC
VERSION：4.0.0-RC2
```
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.resultset.ShardingResultSet.getInt(ShardingResultSet.java:102)
	at org.hibernate.type.descriptor.sql.IntegerTypeDescriptor$2.doExtract(IntegerTypeDescriptor.java:62)
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243)
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329)
	at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3025)
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.loadFromResultSet(EntityReferenceInitializerImpl.java:333)
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.hydrateEntityState(EntityReferenceInitializerImpl.java:261)
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.readRow(AbstractRowReader.java:109)
	at org.hibernate.loader.plan.exec.internal.EntityLoadQueryDetails$EntityLoaderRowReader.readRow(EntityLoadQueryDetails.java:254)
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:122)
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:107)
	at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:188)
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4289)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:597)
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:565)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:226)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:350)
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:127)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:93)
	at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1277)
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1149)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:682)
	at org.hibernate.type.EntityType.resolve(EntityType.java:464)
	at org.hibernate.type.ManyToOneType.resolve(ManyToOneType.java:239)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:205)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:160)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1172)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:1022)
	at org.hibernate.loader.Loader.doQuery(Loader.java:960)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:351)
	at org.hibernate.loader.Loader.doList(Loader.java:2787)
	at org.hibernate.loader.Loader.doList(Loader.java:2770)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2604)
```

**Comment by iamzxj** [comment] 2020-08-17 02:08
I upgraded to 4.1.1 and the problem was solved

**Comment by iamzxj** [comment] 2020-08-17 02:08
This version of 4.0.0-RC2 does have this problem, right?

**Comment by tristaZero** [comment] 2020-08-17 06:32
@iamzxj Hi, You means upgrade solved your problem, right?
Then, do you think it is time for you to close this one?

> I upgraded to 4.1.1 and the problem was solved

**Closed** 2020-08-24 03:54 UTC
Labels: invalid

**Comment by KSMASTERS** [comment] 2021-05-14 06:04
> @iamzxj Hi, You means upgrade solved your problem, right?
> Then, do you think it is time for you to close this one?
> 
> > I upgraded to 4.1.1 and the problem was solved

The 4.1.1 release still has this problem

**Comment by KSMASTERS** [comment] 2021-05-14 06:15
> > @iamzxj Hi, You means upgrade solved your problem, right?
> > Then, do you think it is time for you to close this one?
> > > I upgraded to 4.1.1 and the problem was solved
> 
> The 4.1.1 release still has this problem

But this is caused by a mismatch between the database field definition type and the ResultMap field map
