### ISSUE TITLE
Springboot with JPA, readwrite-splitting always on write-ds

### ISSUE THREAD

**Issue by 13612687938** [apache/shardingsphere#15629] opened 2022-02-25 06:41 UTC
## Bug Report

Current situation：
SpringBoot + Mybatis-Plus + MySQL8.0 + ShardingSphere-JDBC  ===> SUCCESS
SpringBoot + SpringDataJPA + MySQL8.0 + ShardingSphere-JDBC  ===> FAIL （read and write both on write-ds）

detail code: (an API method just contain userRepository.findAll();)
     /**
     * query all list
     *
     * @return
     */
    @GetMapping("/list")
    public List<User> list() {
        return userService.list();
    }

expect：
write on write-ds, read on read-ds.

      <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.0</version>
        </dependency>
    </dependencies>

application.properties just copy url "https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/readwrite-splitting-example/readwrite-splitting-spring-boot-jpa-example/src/main/resources/application-readwrite-splitting.properties"

`spring.shardingsphere.datasource.names=write-ds,read-ds-0,read-ds-1

spring.shardingsphere.datasource.write-ds.jdbc-url=jdbc:mysql://localhost:3306/shardingsphere-main?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.write-ds.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.write-ds.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.write-ds.username=root
spring.shardingsphere.datasource.write-ds.password=root

spring.shardingsphere.datasource.read-ds-0.jdbc-url=jdbc:mysql://localhost:3306/shardingsphere-slave1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.read-ds-0.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.read-ds-0.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.read-ds-0.username=root
spring.shardingsphere.datasource.read-ds-0.password=root

spring.shardingsphere.datasource.read-ds-1.jdbc-url=jdbc:mysql://localhost:3306/shardingsphere-slave2?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
spring.shardingsphere.datasource.read-ds-1.type=com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.read-ds-1.driver-class-name=com.mysql.jdbc.Driver
spring.shardingsphere.datasource.read-ds-1.username=root
spring.shardingsphere.datasource.read-ds-1.password=root

spring.shardingsphere.rules.readwrite-splitting.data-sources.readwrite_ds.type=Static
spring.shardingsphere.rules.readwrite-splitting.data-sources.readwrite_ds.props.write-data-source-name=write-ds
spring.shardingsphere.rules.readwrite-splitting.data-sources.readwrite_ds.props.read-data-source-names=read-ds-0,read-ds-1
spring.shardingsphere.rules.readwrite-splitting.data-sources.readwrite_ds.load-balancer-name=round_robin
spring.shardingsphere.rules.readwrite-splitting.load-balancers.round_robin.type=ROUND_ROBIN

spring.shardingsphere.props.sql-show=true`

**Comment by zjcnb** [comment] 2022-02-25 07:48
@13612687938 Hi, please refer to #14858

**Comment by 13612687938** [comment] 2022-02-25 07:51
@zjcnb Different, I just query the data, no insert operation

**Comment by zjcnb** [comment] 2022-02-25 07:57
> https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/readwrite-splitting-example/readwrite-splitting-spring-boot-jpa-example/src/main/resources/application-readwrite-splitting.properties

Can you provider a demo?

**Comment by zjcnb** [comment] 2022-02-25 07:57
> @zjcnb Different, I just query the data, no insert operation

Can you provider a demo?

**Comment by 13612687938** [comment] 2022-02-25 08:06
Yes, I create 3 database(datasource),demo include sql which just create table.
For simple testing, you can manually add XXX data to the slave-datasource1 and add YYY data to the slave-datasource2, and simply request the list interface to observe


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shardingsphere] Springboot with JPA, readwrite-splitting always on write-ds (Issue #15629)





  
https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/readwrite-splitting-example/readwrite-splitting-spring-boot-jpa-example/src/main/resources/application-readwrite-splitting.properties
  
Can you provider a demo?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zjcnb** [comment] 2022-02-25 11:02
> Yes, I create 3 database(datasource),demo include sql which just create table. For simple testing, you can manually add XXX data to the slave-datasource1 and add YYY data to the slave-datasource2, and simply request the list interface to observe
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/shardingsphere" ***@***.***&gt;; 发送时间:&nbsp;2022年2月25日(星期五) 下午3:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apache/shardingsphere] Springboot with JPA, readwrite-splitting always on write-ds (Issue #15629) https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/readwrite-splitting-example/readwrite-splitting-spring-boot-jpa-example/src/main/resources/application-readwrite-splitting.properties Can you provider a demo? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Provider demo project. Because i can't reproduce it.

**Comment by 13612687938** [comment] 2022-02-25 11:38
this is a demo, with sql for create table, without sql for create database.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/shardingsphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 晚上7:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/shardingsphere] Springboot with JPA, readwrite-splitting always on write-ds (Issue #15629)





  
Yes, I create 3 database(datasource),demo include sql which just create table. For simple testing, you can manually add XXX data to the slave-datasource1 and add YYY data to the slave-datasource2, and simply request the list interface to observe
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/shardingsphere" @.&gt;; 发送时间:&nbsp;2022年2月25日(星期五) 下午3:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [apache/shardingsphere] Springboot with JPA, readwrite-splitting always on write-ds (Issue #15629) https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/readwrite-splitting-example/readwrite-splitting-spring-boot-jpa-example/src/main/resources/application-readwrite-splitting.properties Can you provider a demo? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
Provider demo project. Because i can't reproduce it.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nekolr** [comment] 2022-03-11 02:08
Same problem, i traced the call stack and found the reason:

> refer: hibernate-core\5.6.5.Final\hibernate-core-5.6.5.Final.jar!\org\hibernate\resource\jdbc\internal\AbstractLogicalConnectionImplementor.class
```
public void begin() {
    try {
        if (!this.doConnectionsFromProviderHaveAutoCommitDisabled()) {
            log.trace("Preparing to begin transaction via JDBC Connection.setAutoCommit(false)");
            // here
            this.getConnectionForTransactionManagement().setAutoCommit(false);
            log.trace("Transaction begun via JDBC Connection.setAutoCommit(false)");
        }

        this.status = TransactionStatus.ACTIVE;
    } catch (SQLException var2) {
        throw new TransactionException("JDBC begin transaction failed: ", var2);
    }
}
```

```
setAutoCommit:129, ShardingSphereConnection (org.apache.shardingsphere.driver.jdbc.core.connection)
begin:72, AbstractLogicalConnectionImplementor (org.hibernate.resource.jdbc.internal)
begin:285, LogicalConnectionManagedImpl (org.hibernate.resource.jdbc.internal)
begin:246, JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl (org.hibernate.resource.transaction.backend.jdbc.internal)
begin:83, TransactionImpl (org.hibernate.engine.transaction.internal)
beginTransaction:164, HibernateJpaDialect (org.springframework.orm.jpa.vendor)
doBegin:421, JpaTransactionManager (org.springframework.orm.jpa)
startTransaction:400, AbstractPlatformTransactionManager (org.springframework.transaction.support)
getTransaction:373, AbstractPlatformTransactionManager (org.springframework.transaction.support)
createTransactionIfNecessary:595, TransactionAspectSupport (org.springframework.transaction.interceptor)
invokeWithinTransaction:382, TransactionAspectSupport (org.springframework.transaction.interceptor)
invoke:119, TransactionInterceptor (org.springframework.transaction.interceptor)
proceed:186, ReflectiveMethodInvocation (org.springframework.aop.framework)
invoke:137, PersistenceExceptionTranslationInterceptor (org.springframework.dao.support)
proceed:186, ReflectiveMethodInvocation (org.springframework.aop.framework)
invoke:174, CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor (org.springframework.data.jpa.repository.support)
proceed:186, ReflectiveMethodInvocation (org.springframework.aop.framework)
invoke:97, ExposeInvocationInterceptor (org.springframework.aop.interceptor)
proceed:186, ReflectiveMethodInvocation (org.springframework.aop.framework)
invoke:215, JdkDynamicAopProxy (org.springframework.aop.framework)
findById:-1, $Proxy237 (com.sun.proxy)
getUser:18, UserService (com.example.mysqlreadwrite)
getUser:20, UserController (com.example.mysqlreadwrite)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
doInvoke:205, InvocableHandlerMethod (org.springframework.web.method.support)
invokeForRequest:150, InvocableHandlerMethod (org.springframework.web.method.support)
invokeAndHandle:117, ServletInvocableHandlerMethod (org.springframework.web.servlet.mvc.method.annotation)
invokeHandlerMethod:895, RequestMappingHandlerAdapter (org.springframework.web.servlet.mvc.method.annotation)
handleInternal:808, RequestMappingHandlerAdapter (org.springframework.web.servlet.mvc.method.annotation)
handle:87, AbstractHandlerMethodAdapter (org.springframework.web.servlet.mvc.method)
doDispatch:1067, DispatcherServlet (org.springframework.web.servlet)
doService:963, DispatcherServlet (org.springframework.web.servlet)
processRequest:1006, FrameworkServlet (org.springframework.web.servlet)
doGet:898, FrameworkServlet (org.springframework.web.servlet)
service:655, HttpServlet (javax.servlet.http)
service:883, FrameworkServlet (org.springframework.web.servlet)
service:764, HttpServlet (javax.servlet.http)
internalDoFilter:227, ApplicationFilterChain (org.apache.catalina.core)
doFilter:162, ApplicationFilterChain (org.apache.catalina.core)
doFilter:53, WsFilter (org.apache.tomcat.websocket.server)
internalDoFilter:189, ApplicationFilterChain (org.apache.catalina.core)
doFilter:162, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:100, RequestContextFilter (org.springframework.web.filter)
doFilter:117, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:189, ApplicationFilterChain (org.apache.catalina.core)
doFilter:162, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:93, FormContentFilter (org.springframework.web.filter)
doFilter:117, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:189, ApplicationFilterChain (org.apache.catalina.core)
doFilter:162, ApplicationFilterChain (org.apache.catalina.core)
doFilterInternal:201, CharacterEncodingFilter (org.springframework.web.filter)
doFilter:117, OncePerRequestFilter (org.springframework.web.filter)
internalDoFilter:189, ApplicationFilterChain (org.apache.catalina.core)
doFilter:162, ApplicationFilterChain (org.apache.catalina.core)
invoke:197, StandardWrapperValve (org.apache.catalina.core)
invoke:97, StandardContextValve (org.apache.catalina.core)
invoke:540, AuthenticatorBase (org.apache.catalina.authenticator)
invoke:135, StandardHostValve (org.apache.catalina.core)
invoke:92, ErrorReportValve (org.apache.catalina.valves)
invoke:78, StandardEngineValve (org.apache.catalina.core)
service:359, CoyoteAdapter (org.apache.catalina.connector)
service:399, Http11Processor (org.apache.coyote.http11)
process:65, AbstractProcessorLight (org.apache.coyote)
process:889, AbstractProtocol$ConnectionHandler (org.apache.coyote)
doRun:1735, NioEndpoint$SocketProcessor (org.apache.tomcat.util.net)
run:49, SocketProcessorBase (org.apache.tomcat.util.net)
runWorker:1191, ThreadPoolExecutor (org.apache.tomcat.util.threads)
run:659, ThreadPoolExecutor$Worker (org.apache.tomcat.util.threads)
run:61, TaskThread$WrappingRunnable (org.apache.tomcat.util.threads)
run:748, Thread (java.lang)
```

**Comment by lsoimpe** [comment] 2022-04-05 11:54
The same problem!!!

**Comment by pxzxj** [comment] 2022-04-21 12:34
看了下上面都是国内的开发那就用中文吧，看起来方便点儿。

这个问题的根源是Spring Data JPA默认所有方法都使用了事务，当然查询是只读事务，而ShardingSphere判断使用了事务就走主库，这两点可以参考Spring Data JPA的 [SimpleJpaRepository](https://github.com/spring-projects/spring-data-jpa/blob/a70fff4515d04be2e0f6f18edbcd7c1c0bff704e/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/SimpleJpaRepository.java#L89) 类跟ShardingSphere的 [ReadwriteSplittingDataSourceRouter](https://github.com/apache/shardingsphere/blob/4354c3df905e38ca749e6ff40217037ffe2533df/shardingsphere-features/shardingsphere-readwrite-splitting/shardingsphere-readwrite-splitting-core/src/main/java/org/apache/shardingsphere/readwritesplitting/route/impl/ReadwriteSplittingDataSourceRouter.java#L56)
 类。
比较理想的方法当然是ShardingSphere这边判断事务是不是只读的，不过这个不太确定ShardingSphere的开发团队愿不愿意改，就算改也要等到下个版本了。所以我这里提供两种调整Spring Data JPA事务的方案。
### 第一种：
在Spring Boot的启动类加上 @EnableJpaRepositories(enableDefaultTransactions = false)，这样就关闭了Spring Data JPA的默认事务，但这也导致之前依赖默认事务的代码的出错，当然主要是涉及修改的操作，需要在Service或者Repository上手动添加@Transcational注解来解决报错。
所以这种方法虽然配置简单，但对老代码有侵入性，要谨慎使用。
### 第二种：
修改Spring Data JPA的事务判断，如果是只读事务(也就是readOnly=true)那就不开启事务，配置方法如下，其实就是创建 `IgnoreJPAReadOnlyTransactionBeanPostProcessor ` 类并声明为Bean

```java
public class IgnoreJPAReadOnlyTransactionBeanPostProcessor implements BeanPostProcessor {

	@Override
	public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
		if (bean instanceof JpaRepositoryFactoryBean) {
			RepositoryFactoryCustomizer customizer = new RepositoryFactoryCustomizer() {
				@Override
				public void customize(RepositoryFactorySupport repositoryFactory) {
					repositoryFactory.addRepositoryProxyPostProcessor(new IgnoreJPAReadOnlyTransactionRepositoryProxyPostProcessor());
				}
			};
			((RepositoryFactoryBeanSupport<?, ?, ?>) bean).addRepositoryFactoryCustomizer(customizer);
		}
		return bean;
	}

	private static class IgnoreJPAReadOnlyTransactionRepositoryProxyPostProcessor implements RepositoryProxyPostProcessor {

		@Override
		public void postProcess(ProxyFactory factory, RepositoryInformation repositoryInformation) {
			Advisor[] advisors = factory.getAdvisors();
			TransactionInterceptor transactionInterceptor = null;
			for(Advisor advisor : advisors) {
				if(advisor != null && advisor.getAdvice() instanceof TransactionInterceptor) {
					transactionInterceptor = (TransactionInterceptor) advisor.getAdvice();
					break;
				}
			}
			if(transactionInterceptor != null) {
				TransactionAttributeSource transactionAttributeSource = transactionInterceptor.getTransactionAttributeSource();
				TransactionAttributeSource ignoreReadOnlyDelegate = (method, targetClass) -> {
					TransactionAttribute transactionAttribute = transactionAttributeSource.getTransactionAttribute(method, targetClass);
					if(transactionAttribute != null && transactionAttribute.isReadOnly()) {
						return null;
					}
					return transactionAttribute;
				};
				transactionInterceptor.setTransactionAttributeSource(ignoreReadOnlyDelegate);
			}
		}
	}
}


@Configuration
public class WebConfig {
	@Bean
	public IgnoreJPAReadOnlyTransactionBeanPostProcessor ignoreJPAReadOnlyTransactionBeanPostProcessor() {
		return new IgnoreJPAReadOnlyTransactionBeanPostProcessor();
	}
}
```
这种方法经过测试原来代码也都能正常运行，只是禁用了只读事务，所以建议用这个方法。

**Comment by RaigorJiang** [comment] 2023-01-29 07:15
Looks like the issue has been resolved, I will close this it, thank you all!

**Closed by RaigorJiang** 2023-01-29 07:15 UTC
Labels: in: JDBC, feature: readwrite-splitting
