### ISSUE TITLE
DataSourcePropertiesValidator should catch SQLException and ShardingSphereInternalException only

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#20815] opened 2022-09-06 03:56 UTC
Catch exception is not recommended, please investigate the class  DataSourcePropertiesValidator, and try to instead of catch exception to SQLException and ShardingSphereInternalException.

Just search `// TODO check why catch exception here, can it simplify to catch SQLException and ShardingSphereInternalException?` to find the codes.

**Comment by tianhao960** [comment] 2022-09-19 00:26
hi, @terrymanu , I'd like to try this.

**Comment by strongduanmu** [comment] 2022-10-12 00:36
> hi, @terrymanu , I'd like to try this.

@tianhao960 Assigned. Could we finish this issue in 5.2.1?

**Comment by tianhao960** [comment] 2022-10-12 02:44
> > hi, @terrymanu , I'd like to try this.
> 
> @tianhao960 Assigned. Could we finish this issue in 5.2.1?

hi, I am afraid I need some time to finish this and  before 5.2.2 release, it could be done. thanks.

**Comment by tianhao960** [comment] 2022-10-27 08:10
it seems that
 `DataSourcePoolCreator.create(dataSourceProps);`
will throw Exception which caused by `@SneakyThrows(ReflectiveOperationException.class)` at class DataSourcePoolCreator and ShardingSphereServiceLoader.

and DataSourcePropertiesValidator can not catch checked exception ReflectiveOperationException.

**Comment by TeslaCN** [comment] 2022-12-01 07:21
Hi @tianhao960 
Is there any progress?

**Comment by sandynz** [comment] 2022-12-26 06:01
It's already fixed by #22217

**Closed by sandynz** 2022-12-26 06:01 UTC
Labels: in: kernel, good pro issue
