### ISSUE TITLE
Add Firebird support to testcontainers database type

### ISSUE THREAD

**Issue by TedCraft** [apache/shardingsphere#33782] opened 2024-11-24 12:17 UTC
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

Related to #33699.

### Describe the feature you would like.

Firebird has support for testcontainers (https://github.com/FirebirdSQL/firebird-testcontainers-java), but I can't find this module in the official documentation (https://java.testcontainers.org/modules/databases/jdbc/).

We will investigate this issue later, maybe i will close this issue if the module is out of date or cannot be used in ShardingSphere.

**Comment by makssent** [comment] 2024-12-07 09:57
When attempting to use the `firebird-testcontainers` library from [this repository](https://github.com/FirebirdSQL/firebird-testcontainers-java) with Firebird and ShardingSphere, the following error occurred:

> unsupported on-disk structure for file /firebird/data/TEST1.FDB; found 24588.3, support 12.2

**Cause of the Error:**
The error indicates that the library is incompatible with the current version of Firebird. The firebird-testcontainers library was designed to work with Firebird versions up to 2.5 and their corresponding On-Disk Structure (ODS) formats. However, starting from Firebird 3.0, significant changes were introduced to the database structure, including new ODS versions, which the library does not support. Since the library has not been updated to account for these changes, it cannot function with Firebird 3.0 or newer versions.

**Conclusion:**
The firebird-testcontainers library is outdated and does not support Firebird 3.0 or later versions. As a result, it is incompatible with modern Firebird configurations and cannot be used for our work.

**Comment by makssent** [comment] 2024-12-07 10:07
When attempting to use the `firebird-testcontainers` library from [this repository]([https://github.com/FirebirdSQL/firebird-testcontainers-java](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fgithub.com%2FFirebirdSQL%2Ffirebird-testcontainers-java)) with Firebird and ShardingSphere, the following error occurred:

> unsupported on-disk structure for file /firebird/data/TEST1.FDB; found 24588.3, support 12.2

According to the article on [[qa.loginom.ru](https://vk.com/away.php?utf=1&to=http%3A%2F%2Fqa.loginom.ru)]([https://qa.loginom.ru/103/oshibka-podklyucheniya-bazy-firebird-unsupported-structure](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fqa.loginom.ru%2F103%2Foshibka-podklyucheniya-bazy-firebird-unsupported-structure)), The error indicates that the library is incompatible with the current version of Firebird. The firebird-testcontainers library was designed to work with Firebird versions up to 2.5 and their corresponding On-Disk Structure (ODS) formats. However, starting from Firebird 3.0, significant changes were introduced to the database structure, including new ODS versions, which the library does not support. Since the library has not been updated to account for these changes, it cannot function with Firebird 3.0 or newer versions.

Additional Context:
The article [Firebird FAQ - FAQ #80](https://firebirdfaq.org/faq80/) discusses a similar problem. It provides instructions for extracting data from an old database using tools like gbak and migrating it to a newer Firebird version. While these methods can help recover and migrate data, they do not resolve the core issue with the outdated library. Due to its reliance on older ODS versions, the firebird-testcontainers library cannot be used with Firebird 3.0+ in test containers, even if the database is migrated.

**Conclusion:**
The firebird-testcontainers library is outdated and does not support Firebird 3.0 or later versions. As a result, it is incompatible with modern Firebird configurations and cannot be used for our work.

**Comment by TedCraft** [comment] 2024-12-07 14:57
I think we also need to update the documentation at https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/optional-plugins/testcontainers/. Maybe reopen this issue or I can create a new one.

**Comment by strongduanmu** [comment] 2024-12-08 23:53
Hi @TedCraft You can use Ref #33782 instead of Fixes #33782 next time, as it closes the issue by default.

**Comment by linghengqian** [comment] 2024-12-09 06:19
- If you need to support a new version of Firebird, you only need to implement the SPI of https://github.com/testcontainers/testcontainers-java/blob/main/modules/jdbc/src/main/java/org/testcontainers/containers/JdbcDatabaseContainerProvider.java in the downstream project. 

- There are quite a few integration modules in testcontainers that only support old versions of databases, including clickhouse in https://github.com/testcontainers/testcontainers-java/issues/8736 and presto in https://github.com/testcontainers/testcontainers-java/issues/8657 . Most downstream users actually implement `org.testcontainers.containers.JdbcDatabaseContainerProvider` themselves.

- Shardingsphere actually only requires that these `jdbc:tc:xxx:` prefixes have a corresponding OSS Maven module to facilitate further integration testing. I don't think it is necessary to try to wait for these Maven modules to update support for new versions of the database.

**Comment by makssent** [comment] 2024-12-09 07:21
At the moment, we are working on a major task, which is why we cannot fully delve into studying various issues that also concern us. Currently, I am just exploring the ShardingSphere project, looking for new features to add and implement, and gradually working on these topics. We hope to complete this task successfully by the New Year, and once it is accomplished, we will be able to fully focus on ShardingSphere. I will be able to finish everything I have planned, and your comment will be very helpful. Thank you for that!

**Comment by makssent** [comment] 2024-12-09 09:32
@strongduanmu I apologize, I made a mistake and used Ref instead of Fixes, which prevented the ticket from being closed automatically. Could you please close it? We will continue working on this topic in new issues.

**Comment by strongduanmu** [comment] 2024-12-09 09:37
@makssent This was my mistake, I modified the Fixes, I close it now. 😂

**Closed by strongduanmu** 2024-12-09 09:37 UTC
Labels: type: enhancement, db: Firebird
