### ISSUE TITLE
ShardingSphere-proxy 5.0.0+Seata 1.4.2 no roll back when exception occurs on mircoservice of Spring cloud

### ISSUE THREAD

**Issue by GreekPanda** [apache/shardingsphere#14311] opened 2021-12-25 02:15 UTC
### Which version of ShardingSphere did you use?

shardshpere 5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Work with Seata 1.4.2 can roll back correctly when use mircoservices on springcloud alibaba

### Actual behavior

Seata has been showed roll back, but shardingproxy still add a new data into MySQL

### Reason analyze (If you can)

Totally no clue on it.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1.  Build two mircroservices with springcloud and use nacos as register central
2.  One service use feign api to add a new data into other service
3.  The first service has a exception to tigger roll back of seata and it work, but the second service failed to roll back
4.  Dirty data has generated successfully 

https://github.com/GreekPanda/springcloud-sharding-seata-demo/blob/main/pics/swagger-1.jpg
https://github.com/GreekPanda/springcloud-sharding-seata-demo/blob/main/pics/exception-code.jpg
https://github.com/GreekPanda/springcloud-sharding-seata-demo/blob/main/pics/trigger-exception.jpg
https://github.com/GreekPanda/springcloud-sharding-seata-demo/blob/main/pics/no-roll-back.jpg

### Example codes for reproduce this issue (such as a github link).
https://github.com/GreekPanda/springcloud-sharding-seata-demo

**Comment by zjcnb** [comment] 2021-12-27 06:07
@GreekPanda Hi, Can you use master branch to try it again?

**Comment by zjcnb** [comment] 2021-12-27 06:13
You also download it by http://117.48.121.24:8080/

**Comment by GreekPanda** [comment] 2021-12-27 09:00
> You also download it by http://117.48.121.24:8080/

@zjcnb Hi, I'll try later, thanks a lot.

**Comment by GreekPanda** [comment] 2021-12-27 09:38
> You also download it by http://117.48.121.24:8080/
@zjcnb Hi, I've tried again and again ,I'm sure use the right version of shardingshpere-proxy-5.0.1, but the same issue, no roll back.

**Comment by challengeof** [comment] 2021-12-27 13:57
Hi @GreekPanda Can you provide reproduce example?

**Comment by GreekPanda** [comment] 2021-12-28 08:11
> Hi @GreekPanda Can you provide reproduce example?

Hi, @challengeof you can try this:  https://github.com/GreekPanda/springcloud-sharding-seata-demo

**Comment by challengeof** [comment] 2021-12-29 02:53
> > Hi @GreekPanda Can you provide reproduce example?
> 
> Hi, @challengeof you can try this: https://github.com/GreekPanda/springcloud-sharding-seata-demo

Hey @GreekPanda this example can't compile,  maybe because of some local dependencies.

Please provide a complete and simple example includes ddl.sql dml.sql......

**Comment by GreekPanda** [comment] 2021-12-30 08:31
> > > Hi @GreekPanda Can you provide reproduce example?
> > 
> > 
> > Hi, @challengeof you can try this: https://github.com/GreekPanda/springcloud-sharding-seata-demo
> 
> Hey @GreekPanda this example can't compile, maybe because of some local dependencies.
> 
> Please provide a complete and simple example includes ddl.sql dml.sql......

Hi, @challengeof it's a huge work  as you want, could you give me a email or Im? I want to send a maven tool configuration to you in private?

**Comment by challengeof** [comment] 2021-12-31 03:09
> > > > Hi @GreekPanda Can you provide reproduce example?
> > > 
> > > 
> > > Hi, @challengeof you can try this: https://github.com/GreekPanda/springcloud-sharding-seata-demo
> > 
> > 
> > Hey @GreekPanda this example can't compile, maybe because of some local dependencies.
> > Please provide a complete and simple example includes ddl.sql dml.sql......
> 
> Hi, @challengeof it's a huge work as you want, could you give me a email or Im? I want to send a maven tool configuration to you in private?

You can create a simple project and upload it to github.
Email challengeof@gmail.com

**Comment by GreekPanda** [comment] 2021-12-31 08:56
> challengeof@gmail.com

Hi, @challengeof I've sent it to you, check your email, please.

**Comment by jingshanglu** [comment] 2022-01-04 10:59
@GreekPanda You maybe should give the `SQL` from your app to `ShardingSphere-Proxy`.

**Comment by jingshanglu** [comment] 2022-01-04 11:17
@GreekPanda change `server.yaml`:
 ```sql-show: true```
then you will look the  sql from your app (include `begin`,`commit`,`rollback`)

**Comment by terrymanu** [comment] 2022-06-24 15:47
This issue is opened for long time any no feedback, I just close it.

**Closed by terrymanu** 2022-06-24 15:47 UTC
Labels: feature: transaction
