### ISSUE TITLE
Transaction not rolled back

### ISSUE THREAD

**Issue by zhoubonet** [apache/shardingsphere#10138] opened 2021-04-20 08:03 UTC
Transaction not rolled back

### Which version of ShardingSphere did you use?
5.0
![image](https://user-images.githubusercontent.com/4209701/115360087-dfde2500-a1f1-11eb-8de5-409647869318.png)
![image](https://user-images.githubusercontent.com/4209701/115360131-ec627d80-a1f1-11eb-8467-dac1155381d3.png)

**Comment by RaigorJiang** [comment] 2021-04-20 09:44
Hi @zhoubonet 
Could you provide your sharding configuration and transaction code?  Because there are so many ways to make transaction fail

**Comment by zhoubonet** [comment] 2021-04-21 01:15
1、The configuration uses Java code
2、
![image](https://user-images.githubusercontent.com/4209701/115482740-ef0cb380-a281-11eb-9825-9c2c40569cfe.png)
3、Transaction 4.0 is ok
4、class configuration
![image](https://user-images.githubusercontent.com/4209701/115482819-1cf1f800-a282-11eb-864b-8137fb2af750.png)

**Comment by zhoubonet** [comment] 2021-04-21 01:20
java configuration
![image](https://user-images.githubusercontent.com/4209701/115483087-b0c3c400-a282-11eb-9a1f-1069555e5837.png)
shardingRuleConfig not  configuration

**Comment by RaigorJiang** [comment] 2021-04-21 02:25
OK, where  is the `add` method invoked?

**Comment by zhoubonet** [comment] 2021-04-21 02:45
controller invoked

**Comment by zhoubonet** [comment] 2021-04-21 02:46
http-> controller->service

**Comment by RaigorJiang** [comment] 2021-04-21 03:28
Hi @zhoubonet 
I did not see your transaction configuration, are you using sping boot starter? 
We should config  the  `TransactionManager`  and use  `@ShardingTransactionType` annotation.

please see https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/usage/transaction/spring-boot-starter/

**Comment by zhoubonet** [comment] 2021-04-22 07:52
I use Druid datasource transaction is OK

**Comment by zhoubonet** [comment] 2021-04-22 07:53
<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>${shardingsphere.version}</version>
</dependency>

I don't rely on this library

**Comment by zhoubonet** [comment] 2021-04-22 08:40
Data write exception, not thrown

**Comment by RaigorJiang** [comment] 2021-04-25 03:08
Hi @zhoubonet , is this problem still exists?
By default, ShardingSphere will affect local transactions, I can't tell more based on the information, sorry.
Could you please provide a demo project on github?

**Comment by zhoubonet** [comment] 2021-05-06 01:24
existence

**Comment by RaigorJiang** [comment] 2021-05-12 02:25
> existence

Sorry to hear that. But the information is not enough, I can't reproduce it. 
Maybe somebody else can help.

**Comment by zhoubonet** [comment] 2021-06-05 01:04
test demo 
https://gitee.com/lhur/sharding-demo.git

**Comment by zhoubonet** [comment] 2021-06-05 01:34
1 、database script  src/main/resources/data.sql
2、database connect  src/main/resources/application.properties
3、connect object initialize src/main/java/com/dudu/config/ShardingConfiguration.java
4、Interface test  http://localhost:8090/learn/test

**Comment by zhoubonet** [comment] 2021-06-08 07:27
What's the result of the example test

**Comment by zhoubonet** [comment] 2021-06-16 02:55
@RaigorJiang Will you have time to look at this problem

**Comment by RaigorJiang** [comment] 2021-06-16 03:15
@zhoubonet  Yes!  I reproduced this exception yesterday, and I am looking for the cause.

**Comment by RaigorJiang** [comment] 2021-06-16 11:04
Hi @zhoubonet 
The cause of the exception has been found and will be fixed soon.

**Comment by RaigorJiang** [comment] 2021-06-17 09:36
Hi @zhoubonet 
You can have a test after the PR merged, thanks for your careful testing.

**Comment by zhoubonet** [comment] 2021-06-18 01:26
ok

**Closed** 2021-06-21 03:20 UTC
Labels: in: JDBC, type: bug
