### ISSUE TITLE
[ShardingSphere-Proxy] Missing return field

### ISSUE THREAD

**Issue by hongfuli** [apache/shardingsphere#18528] opened 2022-06-23 04:13 UTC
## Bug Report
`select VERSION(), @@sql_mode;`

### Which version of ShardingSphere did you use?
ShardingSphere-Proxy 5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy 5.1.2

### Expected behavior

| 5.7.34    | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

### Actual behavior
Only return the first field value:
5.7.34-ShardingSphere-Proxy 5.1.2

**Comment by terrymanu** [comment] 2022-06-23 13:08
Maybe something wrong with the implementation, does anyone want to investigate it?

**Comment by hongfuli** [comment] 2022-06-29 12:19
Anyone help to fix this bug? :)
@tristaZero

**Comment by TeslaCN** [comment] 2022-06-30 14:57
This issue is caused by the result of selecting a function is hardcoded.

https://github.com/apache/shardingsphere/blob/a3a0d3db8d419dd45cc1e0c33c64d7f81edc0655/shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/text/admin/mysql/executor/ShowVersionExecutor.java#L38-L53

**Comment by hongfuli** [comment] 2022-07-01 03:44
Can this bug be fixed in 5.1.3?

**Comment by TeslaCN** [comment] 2022-07-01 03:44
@hongfuli Are you interested in fixing this?

**Comment by hongfuli** [comment] 2022-07-01 03:47
I am familiar with the code before 5.0. Now because my company project is very busy, I haven't read the latest code for a long time, sorry

**Comment by xuup** [comment] 2022-07-13 07:14
I'am interested in this issue , could you please assign this issue to me ?

**Comment by TeslaCN** [comment] 2022-07-13 07:16
Hi @xuup 
Welcome. Do you have any idea about this?

**Comment by xuup** [comment] 2022-07-27 13:17
> Hi @xuup Welcome. Do you have any idea about this?

Hi, I hava two thoughts on this issue.
1. redirect request to real database for execution, and get response from database.
2. @@sql_mode represent mode of database  as mysql, 
```
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
represent some modes supported by the database. I think the mode should be provided  by ShardingSphere-Proxy better than database .  So, Is it necessary to add the mode configuration supported by ShardingSphere ?
I wonder what you think about that。

**Closed** 2022-07-28 11:27 UTC
Labels: in: proxy, db: MySQL, in: metadata
