### ISSUE TITLE
Support mysql jdbc's loadbalance

### ISSUE THREAD

**Issue by xunyard** [apache/shardingsphere#8736] opened 2020-12-23 09:32 UTC
## Feature Request

During  use loadbalnce in jdbc url configuration, it will cause problem (related to bug #5531 [fail to switch schema] ).

## Conditions
- Spring boot application (v2.1.6)
- @Transicational annotaion(optional)
- sharding proxy(v4.1.1)
- mysql-connector-java (v8.0.19)

## Other stuff
jdbc url config example like:

`url: jdbc:mysql:loadbalance://127.0.0.1:3307,127.0.0.1:3407/db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&tcpKeepAlive=true&autoReconnect=true`

key code in jdbc will cause problem:

`com.mysql.cj.jdbc.ha.MultiHostConnectionProxy#syncSessionState(com.mysql.cj.jdbc.JdbcConnection, com.mysql.cj.jdbc.JdbcConnection)`

`com.mysql.cj.jdbc.ha.LoadBalancedConnectionProxy#pickNewConnection`

**Comment by yu199195** [comment] 2020-12-23 11:57
now ， our not support it。

**Comment by tristaZero** [comment] 2020-12-24 06:35
@xunyard ,
Let me guess why you try to use this property. 
1. You intend to make your program visit ShardingProxy with load-balance?
2. You want ShardingProxy to visit the databases by load balance?

Which one?
Supposing the second one, You can add replica-query configuration in `/conf`. Otherwise, currently we do not support this function.

**Comment by xunyard** [comment] 2020-12-25 09:05
> @xunyard ,
> Let me guess why you try to use this property.
> 
> 1. You intend to make your program visit ShardingProxy with load-balance?
> 2. You want ShardingProxy to visit the databases by load balance?
> 
> Which one?
> Supposing the second one, You can add replica-query configuration in `/conf`. Otherwise, currently we do not support this function.

The first one. We want to use load-balance to actually make the result of HA for sharding-proxy.

**Comment by xunyard** [comment] 2020-12-25 09:17
> @xunyard ,
> Let me guess why you try to use this property.
> 
> 1. You intend to make your program visit ShardingProxy with load-balance?
> 2. You want ShardingProxy to visit the databases by load balance?
> 
> Which one?
> Supposing the second one, You can add replica-query configuration in `/conf`. Otherwise, currently we do not support this function.

The first. We want to use java jdbc's loadbance to eventually make the result of HA for sharding-proxy. It is a simple choice for  HA, so how about considering support it in future.

**Comment by tristaZero** [comment] 2020-12-28 10:02
Hi @xunyard ,

Currently, we suggest users achieve the load-balance of Sharding Proxy by `LVS` or `F5` . On the other hand, I am interested in your approach. Could you provide a more detailed log about the exception when the configuration is `mysql:loadbalance`? 
I am considering how to load balance leveraging the power of the database. Do you think PostgreSQL has a similar JDBC driver property?

**Comment by yinyanghuafa** [comment] 2020-12-31 05:17
Can shardingsphere-JDBC support loadbalance in mysql-connector-java?

**Comment by kfwang90** [comment] 2020-12-31 06:21
> Hi @xunyard ,
> 
> Currently, we suggest users achieve the load-balance of Sharding Proxy by `LVS` or `F5` . On the other hand, I am interested in your approach. Could you provide a more detailed log about the exception when the configuration is `mysql:loadbalance`?
> I am considering how to load balance leveraging the power of the database. Do you think PostgreSQL has a similar JDBC driver property?

I have a similar question, our project deployed in two data centers. PG clusters is async replication mode(**Not HA Cluster**). I try to use shardingsphere-jdbc config with this: "jdbc:postgresql://node1,node2,node3/accounting?targetServerType=master", but get exception: **UnrecognizedDatabaseURLException**. 
My purpose is one PG node down, async switch to master byhand, but the application don't have to change config and restart.

**Comment by xunyard** [comment] 2021-01-03 13:49
> Hi @xunyard ,
> 
> Currently, we suggest users achieve the load-balance of Sharding Proxy by `LVS` or `F5` . On the other hand, I am interested in your approach. Could you provide a more detailed log about the exception when the configuration is `mysql:loadbalance`?
> I am considering how to load balance leveraging the power of the database. Do you think PostgreSQL has a similar JDBC driver property?

`F5` was first used to make HA for sharding-proxy, but some problems happened. F5 was gave up, because we are not familiar with it, at the same time without enough time. 

The problem when using F5 is：
- sometimes error may occur when executing simple query SQL such as `select * from table-xxx`.

Error occur for sharding-proxy [follows](https://github.com/apache/shardingsphere/blob/master/shardingsphere-proxy/shardingsphere-proxy-backend/src/main/java/org/apache/shardingsphere/proxy/backend/communication/jdbc/connection/BackendConnection.java) line 93. Just forbidden swith schema during transaction process.

I thought this maybe some mistake between mysql's loading-balance strategy for switch schema, so follow stuff found:

- mysql's loading balance proxy [LoadBalancedConnectionProxy](https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/ha/LoadBalancedConnectionProxy.java) (line 602) will try to pick new connection after `commit` or `rollback` is called.
- sync will be executed when `target` connection chosen during [pick](https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/ha/MultiHostConnectionProxy.java) (line 405) process.
- autocommit flag still be `false` when `sync` method mentioned above is under executing, with 'change schema' followed.

conclusion:
1. `autocommit` status sync maybe drawback for loading-balance switch, or maybe the real pick could happen after a complete transaction and so on. 
2. mysql server can accept the logic of switching schema during transcation, so just considering the possibility of supporting it (I don't know about PostgreSQL, so please give your viewpoint).

Also, I will try for find more kind of adjust in client side, maybe loading-balance stratgy or other stuff. Hope for your point.

**Comment by tristaZero** [comment] 2021-01-04 04:16
@kfwang90,

Hi your issue needs a little improvement. Would you like to fix it and raise a PR? No worries, If you have no interests, we will post it to the community.

Here are some points for you.

1. Modify `pattern` in `PostgreSQLDataSourceMetaData` to support the this url `"jdbc:postgresql://node1,node2,node3/accounting?targetServerType=master"`.
2. You can refer to `pattern` in `MySQLDataSourceMetaData`
3. Since `pattern` is just a regular expression, it is easy to fix.
4. Please add unit test in `PostgreSQLDataSourceMetaDataTest`.

**Comment by tristaZero** [comment] 2021-01-04 04:35
@xunyard ,

Appreciated your clarification. 

Still, I have some questions here,

1. What's the role `LoadBalancedConnectionProxy` plays? If users use `jdbc:mysql:loadbalance:`, `LoadBalancedConnectionProxy` will take the charge of the load-balance job?
2. Why do we need to focus on the `transaction`? Not all of the requests from users will begin a transaction, right? When we configure with `jdbc:mysql:loadbalance:`, does every query trigger ShardingSphere to run into `Line 93` of `BackendConnection `?

If you do not mind, maybe we can communicate by WeChat. :) Could you send your WeChat number to panjuan@apache.org?

**Comment by xunyard** [comment] 2021-01-04 06:25
Hi @tristaZero,

Thanks, more for your problem:

1. `LoadBalancedConnectionProxy` created when `loadbalance` presents in jdbc url, during connect process. It also cover the implement of balance based on strategy, such as random(default), bestResponseTime, serverAffinity.
2. `transaction` is necessary to focus, because `switch connection` executes surely  at the end of `transaction`. Finally trigger ShardingSphere to run into Line 93 of `BackendConnection`.

Email of my WeChat qrcode already sent to your email mentioned above from xunyard@gmail.com, hoping for your reply.

**Comment by kfwang90** [comment] 2021-01-05 00:22
> @kfwang90,
> 
> Hi your issue needs a little improvement. Would you like to fix it and raise a PR? No worries, If you have no interests, we will post it to the community.
> 
> Here are some points for you.
> 
> 1. Modify `pattern` in `PostgreSQLDataSourceMetaData` to support the this url `"jdbc:postgresql://node1,node2,node3/accounting?targetServerType=master"`.
> 2. You can refer to `pattern` in `MySQLDataSourceMetaData`
> 3. Since `pattern` is just a regular expression, it is easy to fix.
> 4. Please add unit test in `PostgreSQLDataSourceMetaDataTest`.

OK. I will try to fix it.

**Comment by tristaZero** [comment] 2021-01-05 03:35
Hi @kfwang90 
Welcome,  please refer to this issue number when your PR is raised. :)

**Comment by tristaZero** [comment] 2021-01-06 03:39
Hi, community,

After some transaction tests on MySQL and a discussion with @xunyard, here comes the conclusion.

1. We recommend Java developers considering `jdbc:mysql:loadbalance` (i.e., LoadBalancedConnectionProxy) to do query load-balance on ShardingProxy instead of `F5`.
2. You are suggested to set `autocommit` = `on` to avoid unexpected behaviors when loading balance.
3. My tests and debugging of ShardingSphere convinced me it is highly possible there is a bug in `TransactionBackendHandlerFactory` when ``autocommit` = `off`,
```java
if (tclStatement instanceof SetAutoCommitStatement) {
            if (((SetAutoCommitStatement) tclStatement).isAutoCommit()) {
                return backendConnection.getTransactionStatus().isInTransaction() ? new TransactionBackendHandler(TransactionOperationType.COMMIT, backendConnection) : new SkipBackendHandler();
            }
            return new TransactionBackendHandler(TransactionOperationType.BEGIN, backendConnection);
        }
```
When users execute set` autocommit=off`, ShardingSphere will return `TransactionBackendHandler(TransactionOperationType.BEGIN, backendConnection)`. However, MySQL has a different behavior with it. Plus, after setting` autocommit=off`, MySQL still allows users to use another database, but ShardingSphere doesn't keep up with it. (Line 93 in `BackendConnection`). 

Besides, it stays the same with MySQL when setting `autocommit` again after the first one (Implicit `commit`).

I have no idea about `XA` transaction, so @yu199195 could you give more detail about these cases?

**Comment by tristaZero** [comment] 2021-09-27 13:22
Sorry there is no following feedback until now, I have to close it.

**Closed by tristaZero** 2021-09-27 13:22 UTC
Labels: status: volunteer wanted, feature: readwrite-splitting
