### ISSUE TITLE
ShardingSphere5.1.1 does not support querying JSON data from MySQL, ShardingSphere4.1.1 is available

### ISSUE THREAD

**Issue by sxlArtless** [apache/shardingsphere#21233] opened 2022-09-28 06:49 UTC
## Bug Report
select source ->>'$.sourceGiftId' from inventory_budget

This is the result of the Navicat table execution
![image](https://user-images.githubusercontent.com/40255891/192707352-fc65efb0-7cbe-4255-8b21-197602f74b66.png)

This is a parsing error for SQL execution after version 5.1.1
![image](https://user-images.githubusercontent.com/40255891/192707776-80dedc44-285e-4cef-987e-bca5e9d8b9be.png)

**Comment by KnothHe** [comment] 2022-09-28 17:26
@sxlArtless 

In my test, ShardingSphere 5.1.1  is okay, ShardingSphere 4.1.1 is run with error. The reason is incorrect parsing of SQL by the results of the test. Resulting in no routing table, query error.

For simplicity, JdbcTemplate is used

<img width="2390" alt="image" src="https://user-images.githubusercontent.com/25814839/192848610-985f9a25-da2e-4693-9af9-3e631b71a08c.png">


<img width="2089" alt="image" src="https://user-images.githubusercontent.com/25814839/192846251-340ed91d-6b48-4de8-8726-6beeabdf2b2e.png">

I have uploaded my test project, you can test it. Checkout different branch to test different sharding version.
[address](https://github.com/KnothHe/sharding-issues-21233)

**Comment by sxlArtless** [comment] 2022-09-29 06:33
These are two different ways of writing JSON, and then using JdbcTemplate is still a problem.
I used Springboot, and the corresponding Sharding dependence is this
```
<dependency>
      <groupId>org.apache.shardingsphere</groupId>
      <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
      <version>5.1.1</version>
  </dependency>

```
![image](https://user-images.githubusercontent.com/40255891/192956412-05b50fba-4348-47cd-b588-ed5fb69a12f4.png)

**Comment by KnothHe** [comment] 2022-09-29 11:48
@sxlArtless 
I reproduced, the reason is the table alias. It should be that ShardingSphere does not recognize the syntax used with aliases and json `->>`

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/25814839/193022614-03800cf9-2313-4f94-9c70-661ab2e61d1f.png">


```java
System.out.println(shardingJdbcTemplate.queryForMap("SELECT json_field ->> '$.key' FROM json_test WHERE id = ?", 2));
System.out.println(shardingJdbcTemplate.queryForMap("SELECT jt.json_field ->> '$.key' FROM json_test jt WHERE id = ?", 2));
```

With table alias, this syntax is workd.
```java
System.out.println(shardingJdbcTemplate.queryForMap("SELECT JSON_UNQUOTE(JSON_EXTRACT(jt.json_field, '$.key')) FROM json_test jt WHERE id = ?", 2));
```

**Comment by KnothHe** [comment] 2022-09-29 12:02
Error syntax is

```java
shardingJdbcTemplate.queryForMap("SELECT jt.json_field ->> '$.key' FROM json_test jt WHERE id = ?", 2);
```

My error stack, not exactly the same as @sxlArtless's screenshot:
```txt
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[guava-30.0-jre.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[guava-30.0-jre.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974) ~[guava-30.0-jre.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935) ~[guava-30.0-jre.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941) ~[guava-30.0-jre.jar:na]
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserEngine.parse(SQLStatementParserEngine.java:47) ~[shardingsphere-infra-parser-5.1.1.jar:5.1.1]
	at org.apache.shardingsphere.infra.parser.ShardingSphereSQLParserEngine.parse(ShardingSphereSQLParserEngine.java:58) ~[shardingsphere-infra-parser-5.1.1.jar:5.1.1]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:180) ~[shardingsphere-jdbc-core-5.1.1.jar:5.1.1]
	at org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement.<init>(ShardingSpherePreparedStatement.java:149) ~[shardingsphere-jdbc-core-5.1.1.jar:5.1.1]
	at org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection.prepareStatement(ShardingSphereConnection.java:80) ~[shardingsphere-jdbc-core-5.1.1.jar:5.1.1]
	at org.springframework.jdbc.core.JdbcTemplate$SimplePreparedStatementCreator.createPreparedStatement(JdbcTemplate.java:1645) ~[spring-jdbc-5.3.23.jar:5.3.23]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649) ~[spring-jdbc-5.3.23.jar:5.3.23]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713) ~[spring-jdbc-5.3.23.jar:5.3.23]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:744) ~[spring-jdbc-5.3.23.jar:5.3.23]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:757) ~[spring-jdbc-5.3.23.jar:5.3.23]
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:879) ~[spring-jdbc-5.3.23.jar:5.3.23]
	at org.springframework.jdbc.core.JdbcTemplate.queryForMap(JdbcTemplate.java:916) ~[spring-jdbc-5.3.23.jar:5.3.23]
	at me.guanglai.sharding.test.JsonQueryTest.doSomethingAfterStartup(JsonQueryTest.java:28) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.4.jar:2.7.4]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at me.guanglai.sharding.test.ShardingTestApplication.main(ShardingTestApplication.java:10) ~[classes/:na]
Caused by: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:65) ~[shardingsphere-sql-parser-engine-5.1.1.jar:5.1.1]
	at org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.parse(SQLParserExecutor.java:46) ~[shardingsphere-sql-parser-engine-5.1.1.jar:5.1.1]
	at org.apache.shardingsphere.sql.parser.api.SQLParserEngine.parse(SQLParserEngine.java:47) ~[shardingsphere-sql-parser-engine-5.1.1.jar:5.1.1]
	at org.apache.shardingsphere.infra.parser.sql.SQLStatementParserExecutor.parse(SQLStatementParserExecutor.java:48) ~[shardingsphere-infra-parser-5.1.1.jar:5.1.1]
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:41) ~[shardingsphere-infra-parser-5.1.1.jar:5.1.1]
	at org.apache.shardingsphere.infra.parser.cache.SQLStatementCacheLoader.load(SQLStatementCacheLoader.java:30) ~[shardingsphere-infra-parser-5.1.1.jar:5.1.1]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[guava-30.0-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[guava-30.0-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[guava-30.0-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[guava-30.0-jre.jar:na]
	... 39 common frames omitted
```

Both have this error:
```txt
org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor.twoPhaseParse(SQLParserExecutor.java:65) ~[shardingsphere-sql-parser-engine-5.1.1.jar:5.1.1]
	at 
```

**Comment by TeslaCN** [comment] 2022-12-28 07:22
Hi @sxlArtless 
Please try the ShardingSphere 5.3.0. MySQL Json support has been enhanced. https://github.com/apache/shardingsphere/pull/20709

**Comment by TeslaCN** [comment] 2022-12-28 07:24
I tried the ShardingSphere 5.3.0 and the SQL `SELECT jt.json_field ->> '$.key' FROM json_test jt WHERE id = ?` could be parsed. I'm closing this, please open a new issue if you have other problems.

**Closed by TeslaCN** 2022-12-28 07:24 UTC
Labels: type: question, in: SQL parse
