### ISSUE TITLE
mysql json 5.0.0-beta fail to boot

### ISSUE THREAD

**Issue by viqbgrg** [apache/shardingsphere#10900] opened 2021-06-22 03:07 UTC
### Which version of ShardingSphere did you use?
implementation 'org.apache.shardingsphere:shardingsphere-jdbc-core-spring-boot-starter:5.0.0-beta'
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Start the project
### Actual behavior
Unable to start
### Reason analyze (If you can)
A MySQL table with a JSON field will fail to boot

Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.appendDialectRemainTables(SchemaBuilder.java:120) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	... 100 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaData(MySQLTableMetaDataLoader.java:95) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadColumnMetaDataMap(MySQLTableMetaDataLoader.java:77) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.loadTableMetaDataMap(MySQLTableMetaDataLoader.java:59) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.shardingsphere.infra.metadata.schema.builder.loader.dialect.MySQLTableMetaDataLoader.load(MySQLTableMetaDataLoader.java:54) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	at org.apache.shardingsphere.infra.metadata.schema.builder.SchemaBuilder.lambda$appendDialectRemainTables$1(SchemaBuilder.java:116) ~[shardingsphere-infra-common-5.0.0-beta.jar:5.0.0-beta]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

https://github.com/viqbgrg/shardingspheredemo.git

**Comment by strongduanmu** [comment] 2021-06-24 03:22
@viqbgrg Thank you very much for using the `5.0.0-beta` version and reporting the problem. I will investigate this issue later.

**Comment by tuichenchuxin** [comment] 2021-07-13 10:23
@viqbgrg 
This problem is indeed reproduced with your demo.
This is due to mysql databaseMetaData.getTypeInfo()
JSON type cannot be obtained, resulting in subsequent nullPointerException.

append  this will be ok.
![image](https://user-images.githubusercontent.com/86938616/125435773-cfa3b889-2407-4ed4-96b2-5bac434fd0de.png)
I want a more elegant way to solve this problem.

**Comment by RaigorJiang** [comment] 2021-09-26 15:29
Fixed in master.

**Closed by RaigorJiang** 2021-09-26 15:29 UTC
Labels: type: bug, in: metadata
