### ISSUE TITLE
mybatis-plus + 5.1.2,KeyGenerateAlgorithm can not be use

### ISSUE THREAD

**Issue by williamXinCC** [apache/shardingsphere#18721] opened 2022-06-30 04:38 UTC
my key generator
@Slf4j
public final class SeeingflowKeyGenerator implements KeyGenerateAlgorithm{

    private Properties properties = new Properties();

    @Override
    public String getType() {
        return "SeeingflowKeyGenerator";
    }

//    @Override
//    public synchronized Comparable<?> generateKey() {
//        GenerationFeginClient generationFeginClient = SpringUtil.getBean(GenerationFeginClient.class);
//        return generationFeginClient.getKey();
//    }

    @Override
    public synchronized String generateKey() {
        System.out.println("==================generateKey=====================");
        GenerationFeginClient generationFeginClient = SpringUtil.getBean(GenerationFeginClient.class);
        return generationFeginClient.getKey();
    }

    @Override
    public Properties getProps() {
        System.out.println("getProps=======================================SeeingflowKeyGenerator");
        return properties;
    }

    @Override
    public void init(Properties properties) {
        System.out.println("初始化=======================================SeeingflowKeyGenerator");
    }

config
   shardingRuleConfig.setDefaultKeyGenerateStrategy(new KeyGenerateStrategyConfiguration("id","SeeingflowKeyGenerator"));
        shardingRuleConfig.getKeyGenerators().put("SeeingflowKeyGenerator", new 
   ShardingSphereAlgorithmConfiguration("SeeingflowKeyGenerator", null));

mybatis-plus po
public class EventsLog implements Serializable {

    private static final long serialVersionUID = 1L;

//    @TableId(value = "id",type = IdType.Auto)
    @ApiModelProperty(value = "事件id")
        private String id;

log alert
 2022-06-30 11:52:41.742  INFO 22732 --- [           main] o.s.s.c.ThreadPoolTaskExecutor           : Initializing ExecutorService 'applicationTaskExecutor'
2022-06-30 11:52:41.839  INFO 22732 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'Nacos-Watch-Task-Scheduler'
====================getKeyGenerators====================
{
    "SeeingflowKeyGenerator": {
        "type": "SeeingflowKeyGenerator",
        "props": {
        }
    }
}
2022-06-30 11:52:42.846  INFO 22732 --- [           main] c.a.d.p.DruidDataSource                  : {dataSource-1,db1} inited
2022-06-30 11:52:43.948  INFO 22732 --- [           main] c.a.d.p.DruidDataSource                  : {dataSource-2,db0} inited
2022-06-30 11:52:44.142  INFO 22732 --- [           main] c.a.d.p.DruidDataSource                  : {dataSource-3,db2} inited

Spi has bean loaded
So,how to use customer key generator?
mybatis-plus 3.4.3
shardingsphere 5.1.2

**Comment by strongduanmu** [comment] 2022-06-30 07:57
@williamXinCC Can you dig into the logic of mybatis plus and investigate the cause of the problem?

**Comment by terrymanu** [comment] 2022-07-01 11:16
> @strongduanmu I have sent the project to your email. If you have time, please help to have a look

Can you submit the project codes to GitHub? Handle private problem by email is not the open source way.

**Comment by terrymanu** [comment] 2022-07-09 07:40
@williamXinCC Any update?

**Comment by williamXinCC** [comment] 2022-07-13 10:51
@terrymanu nothing, could you show me same example for customer generator key by version5.1.1 or 5.1.2?

**Comment by terrymanu** [comment] 2022-07-25 06:40
@williamXinCC Sorry, I have no time to investigate and show example with 3rd party ORM libraries. Could you do it, or if you have no time too, can you just close the issue?

**Comment by lymzcq1993** [comment] 2022-08-11 05:01
mybatis plus have default ID generation  snowflake+uuid  since 3.3.0.
need ignore mybatis plus ID gengration

```
    @TableId(value = "id",type = IdType.AUTO)
    private Long id;
```

**Comment by TeslaCN** [comment] 2022-12-26 05:56
Close due to no response.

**Closed by TeslaCN** 2022-12-26 05:56 UTC
Labels: feature: sharding, status: need more info
