### ISSUE TITLE
The logical database has disappeared

### ISSUE THREAD

**Issue by Bingai077** [apache/shardingsphere#19290] opened 2022-07-17 10:38 UTC
Which version of ShardingSphere did you use?
5.1.2 （helm cluster）

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

Expected behavior

All logical databases has effected.

Actual behavior
Create and write node data(version,dataSources,rules) in ZooKeepper. Part of the old logical database has disappeared in ShardingSphere-Proxy.

**Comment by terrymanu** [comment] 2022-07-17 15:20
What is the configuration?

**Comment by Bingai077** [comment] 2022-07-18 00:57
![image](https://user-images.githubusercontent.com/51192624/179431984-ac7ba073-8118-4797-96c8-4ea2d6e05e67.png)

for this，the node configuration is the same as in DistSql.

**Comment by Bingai077** [comment] 2022-07-18 01:02
What's the difference between writing directly to ZooKeeper and DistSql？

**Comment by RaigorJiang** [comment] 2022-07-21 16:20
DistSQL provides an API for managing ShardingSphere configuration, which has been carefully designed and tested, and also has validation logic during execution.
However, directly modifying the ZK node is not a supported method. There is no test case covering this scenario, which is not recommended.

**Comment by Bingai077** [comment] 2022-07-22 01:19
Does DistSql support concurrent manipulation of logical resources?
For example, one thread adds a logical database resource and another thread modifies another logical database resource.

Will the same happen with DistSql？ refer to  https://community.sphere-ex.com/t/topic/1053

**Comment by RaigorJiang** [comment] 2022-07-22 02:43
@Bingai077 
DistSQL of course supports it, and your version may be incorrect, because I can't see several built-in databases like 'mysql', 'information_schema' from the results of `show databases`

**Comment by Bingai077** [comment] 2022-07-22 06:38
Ok, thank you. Let's try it. How does DistSQL change the schema version?

**Comment by RaigorJiang** [comment] 2022-07-22 06:46
The schema version is used to switch metadata, such as scaling, DistSQL will not directly change the schema version, which is determined by the governance feature.

**Comment by Bingai077** [comment] 2022-07-22 10:43
@RaigorJiang 
How to configure the default logical table use DistSQL？
Such as：
![image](https://user-images.githubusercontent.com/51192624/180422272-86a4e032-ca21-4f09-82d1-ea41989b14cd.png)

**Comment by RaigorJiang** [comment] 2022-07-22 12:53
Sorry, I don't understand what you mean by `default logical table`.

[Here](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/usage/sharding-rule/) is an example of creating a sharding table rule via DistSQL.

**Comment by Bingai077** [comment] 2022-07-25 02:22
The value of actualDataNodes is not required. How to do this with DistSQL?
![image](https://user-images.githubusercontent.com/51192624/180680201-a064654d-87d2-46bb-8664-238ac77db85f.png)

**Comment by RaigorJiang** [comment] 2022-07-25 02:42
@Bingai077 
Did you mean `Sharding Broadcast Table` ? 
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/syntax/rdl/rule-definition/sharding/

**Comment by Bingai077** [comment] 2022-07-25 03:16
No, I just want to shard the database, not the table.  Different databases , all table structures are identical.

**Comment by RaigorJiang** [comment] 2022-07-25 03:20
You might want to take a look at the example, which can be of practical help:
https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources

**Comment by Bingai077** [comment] 2022-07-25 06:18
My demand is the same as this demand, refer to  https://community.sphere-ex.com/t/topic/1024

**Comment by RaigorJiang** [comment] 2022-07-25 06:55
So, this issue is not clearly described (including the screenshot you provided), and it doesn't match the title.

I suggest you change the title and clarify the content, or submit another issue.

In addition, if you want to ask how to write DistSQL, please provide the complete YAML configuration, an incomplete screenshot cannot provide complete information.

**Comment by Bingai077** [comment] 2022-07-25 13:56
@RaigorJiang 
I know the cause of the problem "The logical database has disappeared".
When the rule configuration of one logical database is incomplete, all other logical database disappear.
Such as：

create database ds;
use ds;

```
ADD RESOURCE ds_abc (
    HOST=192.168.0.1,
    PORT=3306,
    DB=ds_abc,
    USER=root,
    PASSWORD=123456
);

ADD RESOURCE ds_bcd (
    HOST=192.168.0.1,
    PORT=3306,
    DB=ds_bcd,
    USER=root,
    PASSWORD=123456
);

CREATE SHARDING ALGORITHM database_inline (
	TYPE(NAME=inline,PROPERTIES("algorithm-expression"="ds_${tenant_code}"))
);

CREATE DEFAULT SHARDING DATABASE STRATEGY (
	TYPE = standard,SHARDING_COLUMN=tenant_code,SHARDING_ALGORITHM=database_inline
);

==================================================================
CREATE SHARDING TABLE RULE order_test (
	datanodes("ds_${['abc','bcd']}.order_test")
)

CREATE SHARDING TABLE RULE user_test (
	datanodes("ds_${['abc','bcd']}.user_test")
)
```
This occurs when the rules for the logical table have not been configured.

**Comment by RaigorJiang** [comment] 2022-07-26 17:12
<img width="799" alt="image" src="https://user-images.githubusercontent.com/5668787/181068507-d39951ab-a7d2-4541-a9a3-4d7f872d2bf9.png">

Version 5.1.2, I can't reproduce the problem you described.

**Comment by Bingai077** [comment] 2022-07-27 01:09
Please create more logical databases, I mean other logical databases disappear, `ds` will not disappear.

**Comment by RaigorJiang** [comment] 2022-07-27 02:17
OK, I understand.
The problem has been fixed in the master branch. You can build Proxy from master, or refer to this issue  #19461.

**Comment by Bingai077** [comment] 2022-07-27 06:02
Okay, thank you！

**Closed** 2022-07-27 08:48 UTC
Labels: mode: cluster, type: fixed

**Comment by koala775** [comment] 2022-11-01 04:59
I also have this problem,do you have resolved ?

**Comment by RaigorJiang** [comment] 2022-11-01 05:16
Hi @koala775 , what's your version of ShardingSphere, Do you use helm too?

**Comment by koala775** [comment] 2022-11-01 05:19
version:5.1.2 ShardingSphere-proxy.Not use helm .

**Comment by RaigorJiang** [comment] 2022-11-01 05:42
@koala775 So it should not be the same problem, please describe your problem and how to reproduce it in detail, thanks!

**Comment by koala775** [comment] 2022-11-01 05:58
I generate datasource and rule yml text and push them to zookeeper .When I push next logic db and it's work,but the pre doesn‘t work. It throw a exception:Unknow database.Only last push logic db and work.

**Comment by RaigorJiang** [comment] 2022-11-01 06:36
> I generate datasource and rule yml text and push them to zookeeper .When I push next logic db and it's work,but the pre doesn‘t work. It throw a exception:Unknow database.Only last push logic db and work.

Modifying governance data directly is not supported by ShardingSphere, please use YAML file or DistSQL

**Comment by koala775** [comment] 2022-11-01 06:54
In project,how do I use DistSQL with java code?

**Comment by RaigorJiang** [comment] 2022-11-01 08:14
If your application uses JDBC, it needs to be deployed with Proxy for hybrid architecture, and then **send DistSQL to Proxy**.

DistSQL https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/
Hybrid Architecture https://shardingsphere.apache.org/document/current/en/overview/#hybrid-architecture
