### ISSUE TITLE
ShardingSphere v5.1.2 XA transaction has errors, When spring boot integrations start running.

### ISSUE THREAD

**Issue by xiaotong2019** [apache/shardingsphere#19809] opened 2022-08-02 10:42 UTC
## The running logger info:
![image](https://user-images.githubusercontent.com/110440830/182355594-0cb85fc9-bc5b-4b9e-86d4-4fe48a5d4209.png)
![image](https://user-images.githubusercontent.com/110440830/182355666-8ffbbe2f-3a20-437d-9f4f-c71da61076fe.png)
![image](https://user-images.githubusercontent.com/110440830/182355753-2a167494-2f19-45dc-8d4c-eb76b7efe59c.png)
![image](https://user-images.githubusercontent.com/110440830/182355854-60e938a0-ccac-4864-a93d-a49024ae3ebd.png)

## So, How should I use XA transactions? Thanks a lot.

**Comment by linghengqian** [comment] 2022-08-02 11:18
This problem usually depends on your Spring Boot OSS version.  I feel like your issue is the same as https://github.com/apache/shardingsphere/issues/19790.

**Comment by xiaotong2019** [comment] 2022-08-02 14:27
Well, In version 5.0.0, it can be started normally, but why is there a problem with the latest version of 5.1.2?

> This problem usually depends on your Spring Boot OSS version. I feel like your issue is the same as #19790.

**Comment by linghengqian** [comment] 2022-08-02 15:24
- In fact, if you switch to Spring Boot OSS 3.0.0-M4 it works perfectly fine.  Because the atomikos version controlled by spring-boot-starter-parent in the 2.7.x branch is 4.x.  This conflicts with ShardingSphere using atomikos 5.0.8.  

- You can actively change the version controlled by springboot to 5.0.8 to solve this problem, which should be similar to atomikos.verison in pom.xml.  

- This issue is obviously a duplicate and can be closed.

**Comment by xiaotong2019** [comment] 2022-08-03 01:27
> * In fact, if you switch to Spring Boot OSS 3.0.0-M4 it works perfectly fine.  Because the atomikos version controlled by spring-boot-starter-parent in the 2.7.x branch is 4.x.  This conflicts with ShardingSphere using atomikos 5.0.8.
> * You can actively change the version controlled by springboot to 5.0.8 to solve this problem, which should be similar to atomikos.verison in pom.xml.
> * The information you provided is not enough to get a certain PR to the master branch. This issue is obviously a duplicate of [Error: com.atomikos.icatch.jta.JtaTransactionServicePlugin.beforeInit()V #19790](https://github.com/apache/shardingsphere/issues/19790) and can be closed.


Ok, thanks very much  for good replay.
In addition,  startup is successfully, but why is my XA transaction not taking effect? 

Such as:
@Transactional
@ShardingSphereTransactionType(TransactionType.XA)

**Comment by xiaotong2019** [comment] 2022-08-03 01:28
> * In fact, if you switch to Spring Boot OSS 3.0.0-M4 it works perfectly fine.  Because the atomikos version controlled by spring-boot-starter-parent in the 2.7.x branch is 4.x.  This conflicts with ShardingSphere using atomikos 5.0.8.
> * You can actively change the version controlled by springboot to 5.0.8 to solve this problem, which should be similar to atomikos.verison in pom.xml.
> * The information you provided is not enough to get a certain PR to the master branch. This issue is obviously a duplicate of [Error: com.atomikos.icatch.jta.JtaTransactionServicePlugin.beforeInit()V #19790](https://github.com/apache/shardingsphere/issues/19790) and can be closed.


Ok, thanks very much  for good replay.
In addition,  startup is successfully, but why is my XA transaction not taking effect? 

Such as:
@Transactional
@ShardingSphereTransactionType(TransactionType.XA)

**Comment by linghengqian** [comment] 2022-08-03 02:52
- I'm not sure what's going on in your local environment, at least the unit tests for the master branch all passed.  You can provide a minimal reproducible example after modifying the title and description, or close this issue and open a new issue to fill in the issue template.  

- Because I can't reproduce it at the moment, and the new information you provided is somewhat irrelevant to the title and description. Searching for unfriendly titles and descriptions will increase the time other friends discover the problem.

**Closed** 2022-08-03 15:35 UTC
Labels: feature: transaction, in: spring
