### ISSUE TITLE
  An null exception occurred when integrating seata

### ISSUE THREAD

**Issue by ulwx** [apache/shardingsphere#24735] opened 2023-03-22 06:21 UTC
```
 @Transactional(propagation = Propagation.REQUIRED)
    @GlobalTransactional
    public void updateUseAkDs() {
        TransactionTypeHolder.set(TransactionType.BASE);
        addressDao.updateMdForMaster2(1, "123");
        try {
            addressDao.updateMdForMaster1(2, "abc");
        } catch (Exception ex) {
            LOGGER.debug(ex + "");
        }

    }


```
An error is reported when integrating seata. When we use sharding-jdbc with seata, a null exception will be reported! The above is my code.

**Comment by TeslaCN** [comment] 2023-03-23 03:11
Hi @ulwx 
Please provide more information about your question.

**Comment by ulwx** [comment] 2023-03-24 03:44
@Transactional(propagation = Propagation.REQUIRED)
 @GlobalTransactional
 public void updateUseAkDs() {
     TransactionTypeHolder.set(TransactionType.BASE);
     addressDao.updateMdForMaster2(1, "123");
     try {
         addressDao.updateMdForMaster1(2, "abc");
     } catch (Exception ex) {
         LOGGER.debug(ex + "");
     }

 }

@GlobalTransactional is an annotation from seata, indicating that this is a global transaction. When TransactionTypeHolder. set (TransactionType. BASE) is used in a method（using the @ GlobalTransactional annotation）, an error will be reported. The reason is that sharding-jdbc determines in the code that if it is in a global transaction, SeataATShardingSphereTransactionManager#begin() is not executed, finally,  in the code ”SeataTransactionHolder. get(). commit()” in the SeataATShardingSphereTransactionManager#commit() method, SeataTransactionHolder. get()=null, resulting in a null exception!

**Comment by linghengqian** [comment] 2024-02-16 17:54
- I believe this is essentially a duplicate of https://github.com/apache/shardingsphere/issues/22356#issuecomment-1948463141 , and the use of annotations within `io.seata:seata-spring-boot-starter` should be avoided, including `io.seata.spring.annotation.GlobalTransactional`.
- I believe this issue involves adjustments to the Spring Boot Starter side of Seata.

**Closed** 2024-02-17 09:12 UTC
Labels: type: duplicate
