### ISSUE TITLE
After using shardingJDBC, there is a problem with the processing of the date format

### ISSUE THREAD

**Issue by lancecpdd** [apache/shardingsphere#10207] opened 2021-04-27 09:42 UTC
## After using shardingJDBC, there is a problem with the processing of the date format

A field type in mysql is datetime (ex: 2021.04.27 16:20:00)
Used tkmybatis, String used in the entity class to receive
If shardingJDBC is not used, the received result is 2021.04.27 16:20:00
If shardingJDBC is used, the result received is 2021.04.27 16:20:00.1

The field is shardingColumn

**Comment by RaigorJiang** [comment] 2021-04-27 10:16
Hi @leonTuT 
Thanks for your report.  which version do you use?  please give more details.

**Comment by leonTuT** [comment] 2021-04-29 02:49
sharding-jdbc  => 4.0.0-RC2
tk.mybatis        => 2.0.4

**Comment by RaigorJiang** [comment] 2021-04-30 02:23
OK, I am going to have a test.

**Comment by tristaZero** [comment] 2021-04-30 08:18
Hi @RaigorJiang Appreciated your comments and attention, nice. :)

**Comment by RaigorJiang** [comment] 2021-05-11 08:48
Hi @lancecpdd 
Sorry to have kept you waiting.
I found the cause of the problem, and the change appeared after the merge of the ResultSet.

![image](https://user-images.githubusercontent.com/5668787/117785075-cd965a80-b276-11eb-9cd0-b5814f1dd5b1.png)


At line 138, the datetime column is correct. But after resultSet merged at line 141, the datetime column got changed.
This problem was fixed in 4.0.0, and all subsequent versions are correct, can you try newer version?

**Comment by lancecpdd** [comment] 2021-05-12 01:16
@RaigorJiang ，Thank you for your help, I will try to update the version

**Comment by RaigorJiang** [comment] 2021-07-09 08:41
Hi @lancecpdd 
Is your problem solved? Can we close this issue?

**Comment by lancecpdd** [comment] 2021-07-16 04:16
ok!

**Closed** 2021-07-16 07:05 UTC
