### ISSUE TITLE
Improve the initialization of OptimizeContextFactory

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10678] opened 2021-06-06 12:06 UTC
Hi,

If you're interested in this one, please comment below so I can assign it to u. :)

### Background
`OptimizeContextFactory` is created in the constructor of `StandardMetaDataContexts` with `metaDataMap`.
If you dive into the constructor of `OptimizeContextFactory` and `MetaDataContextsBuilder`,  you will find both handlings of them need loading table metadata. Therefore, this issue is to reduce the unnecessary and duplicated table metadata loading.

### Expected result
- Create `OptimizeContextFactory` in `MetaDataContextsBuilder`
- Share the table metadata loading between `OptimizeContextFactory` and `Map<String, ShardingSphereMetaData>` of `StandardMetaDataContexts`

### How
- The entrance is `buildSchema()` of `MetaDataContextsBuilder`
- Change the result of `SchemaBuilder.build()` to `Map<ActualTableMetadata, LogicTableMetadata>`
In `SchemaBuilder`,
`addRuleConfiguredTables` returns `logicTableMetadata`. On the other hand `appendRemainTables(materials, result);` returns `actualTableMetadata`. So we need to call `load()` and `decorate()` of `TableMetaDataBuilder` respectively to get the acutal and logic ones.
- Assemble `ShardingSphereSchema` using the list of logic table metadata
- Create `OptimizeContextFactory` by the list of actual table metadata
- Remove the deprecated constructors of `FederateSchemaMetadata` and `FederateTableMetadata`

**Comment by totalo** [comment] 2021-06-07 07:30
Hi can I try this ？

**Comment by LeeGuoPing** [comment] 2021-06-07 07:33
please assign it to me

**Comment by sizzlecar** [comment] 2021-06-07 07:36
I can do it

**Comment by yinyichao** [comment] 2021-06-07 09:25
let me try

**Comment by liulong99** [comment] 2021-06-07 09:39
please assign it to me

**Comment by tristaZero** [comment] 2021-06-11 06:26
Hi
Thanks for your interest.
Since @totalo came first, I just want to confirm @totalo still wants to fix this one?

**Comment by totalo** [comment] 2021-06-11 07:27
> Hi
> 
> Thanks for your interest.
> 
> Since @totalo came first, I just want to confirm @totalo still wants to fix this one?

Yes，My pleasure.

**Comment by tristaZero** [comment] 2021-06-12 23:55
Hi @totalo It's yours now.

@yinyichao @sizzlecar @LeeGuoPing Thanks guys, we still have more issues for U later on, and welcome your joining.

**Comment by totalo** [comment] 2021-06-13 07:47
> Hi @totalo It's yours now.
> 
> 
> 
> @yinyichao @sizzlecar @LeeGuoPing Thanks guys, we still have more issues for U later on, and welcome your joining. 
> 
> 

Get it!

**Comment by Beyondeclipse** [comment] 2021-06-15 13:00
Hi @tristaZero, In my opinion, the "ShardingSphereDataSource" should be created and inited faster, and the "StandardMetaDataContexts" should be lazy loaded  to avoid slow down the system. Now, "ShardingSphereDataSource" will direct invoke "OptimizeContextFactory" to call "FederateLogicSchema.initTables" which slow down the system with hundreds of databases in startups. 
Can this be improved?

**Comment by tristaZero** [comment] 2021-06-17 08:35
Hi @Beyondeclipse ,

Sorry for my late reply. I am interested in what you mentioned, could you give more explanation on `lazy loading`?

**Comment by Beyondeclipse** [comment] 2021-06-22 08:27
@tristaZero I found the root cause of slowing down my system is loading all 'TableMetaData' twice:
1. ShardingSphereDataSource -> MetaDataContextsBuilder.build -> MetaDataContextsBuilder.buildMetaData -> SchemaBuilder.build
2. ShardingSphereDataSource -> MetaDataContextsBuilder.build -> StandardMetaDataContexts -> OptimizeContextFactory -> FederateSchemaMetadatas -> FederateSchemaMetadata.initTables
The first way is faster than the second one by using multi-thread and DialectTableMetaDataLoader. It seams that the simple way is to make the loading once and I create a pull request for it.

**Closed** 2021-06-24 07:39 UTC
Labels: feature: query-optimization, status: volunteer wanted, type: enhancement
