### ISSUE TITLE
Password rule does not take effect bug

### ISSUE THREAD

**Issue by Y-sir** [apache/shardingsphere#34152] opened 2024-12-26 02:14 UTC
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.5.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
After using distsql to create encryption rules, the data can be converted to ciphertext when inserted in the proxy, but when querying, the ciphertext is still queried in the proxy. Under normal conditions, it should be plaintext.
### Actual behavior
The query in the proxy is plain text
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1、Create a table called xxl_job_user

`CREATE TABLE `xxl_job_user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL COMMENT '账号',
  `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '密码',
  `role` tinyint NOT NULL COMMENT '角色：0-普通用户、1-管理员',
  `permission` varchar(255) DEFAULT NULL COMMENT '权限：执行器ID列表，多个逗号分割',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `i_username` (`username`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb3;`

2、Use distsql statements to create encryption rules for the password field

`CREATE ENCRYPT RULE xxl_job_user (
  COLUMNS ((
      NAME = `password`,
      CIPHER = `password`,
      ENCRYPT_ALGORITHM (
        TYPE (
        NAME = 'AES',
PROPERTIES ( 'aes-key-value' = '123456abc', 'digest-algorithm-name' = 'SHA-1'))))));`

3、Insert a piece of data into the proxy

`INSERT INTO `xxx`.`xxl_job_user` ( `id`, `username`, `password`, `role`, `permission` )
VALUES
  ( 4, 'admin1', '123456', 1, NULL );`

4、Query data in proxy

`SELECT * FROM `xxx`.`xxl_job_user` LIMIT 0,1000`

5、The data queried in the proxy should be 123456, but the queried data is encrypted data.

![image](https://github.com/user-attachments/assets/303b124c-23ba-4514-9b36-65183a034dc3)

**Comment by RaigorJiang** [comment] 2024-12-28 15:10
Hi @Y-sir, I can't reproduce your issue

#### In Proxy
<img width="1229" alt="image" src="https://github.com/user-attachments/assets/b525d968-c5d8-4676-8fa0-f243ff67eaab" />

#### In MySQL
<img width="921" alt="image" src="https://github.com/user-attachments/assets/69d5ca88-e447-43f1-ae5f-4bf8fce151dc" />

**Comment by Y-sir** [comment] 2024-12-31 02:36
@RaigorJiang Hello, I finally found that this bug is related to the [#34208](https://github.com/apache/shardingsphere/issues/34208) bug you sent. I tried to refresh the metadata and it was decrypted. I think the reason is that the table in the encryption rule and the table in the metadata are inconsistent.

**Comment by RaigorJiang** [comment] 2024-12-31 07:53
@Y-sir OK, so can we close this issue and focus on #34208

**Closed** 2024-12-31 09:05 UTC
Labels: type: question, feature: encrypt, status: need more info
