### ISSUE TITLE
Refactor DistSQL drop scaling jobId to clean scaling jobId

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#20275] opened 2022-08-18 12:31 UTC
Current DistSQL: drop scaling j01001;
Final DistSQL: clean scaling j01001;

There're plenty of classes and files need to be modified, include grammar files and related classes, and also DistSQL handler, unit test etc.
We could find them out by searching:
1. Class name search by text: DropMigration . Rename classes, replace `Drop` to `Clean`
2. Text search by regex: drop[ _-]*scaling . Replace text `drop` to `clean` , classes generated by ANTLR4 could be ignored

Firstly, we could change ANTLR4 grammer file, replace `drop` to `clean`:
- migration/RALStatement.g4
- MigrationDistSQLStatement.g4

Then run `mvn clean install -Dmaven.javadoc.skip=true -Djacoco.skip=true -Dspotless.apply.skip=true` in `shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-distsql` module.

And then continue to rename or replace by keyword searching.

After go through these changed files, we could basically know how to add or modify scaling DistSQL.

**Comment by sandynz** [comment] 2022-08-18 12:32
Hi @huangdx0726 , are you interesting to resolve it?

**Comment by huangdx0726** [comment] 2022-08-18 12:40
ok ， assign to me

**Comment by huangdx0726** [comment] 2022-08-18 15:09
also include docs？

**Comment by huangdx0726** [comment] 2022-08-18 15:56
@sandynz  Hi, i find some errors in `ShardingScalingRuleStatementConverter` , caused by some classes in `shardingsphere-infra-common`  are userd， but no related dependencies was found in the `pom.xml` file

**Comment by sandynz** [comment] 2022-08-19 00:33
> also include docs？

Yes

**Comment by sandynz** [comment] 2022-08-19 00:37
> @sandynz Hi, i find some errors in `ShardingScalingRuleStatementConverter` , caused by some classes in `shardingsphere-infra-common` are userd， but no related dependencies was found in the `pom.xml` file

Some classes depended by ShardingScalingRuleStatementConverter were changed recently, maybe you need to run `mvn clean install -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests -Prelease -Dspotless.apply.skip=true` again.

**Closed** 2022-08-19 05:00 UTC
Labels: type: refactor, feature: scaling, feature: DistSQL, good amateur issue
